import re

with open('web/static/js/monitor.js', 'r', encoding='utf-8') as f:
    content = f.read()

replacements = [
    ('/** 少数Model在 JSON 字符串里仍留下字面量 "\\n"; 在已解出正文后再转成换行（不误伤 Windows 盘符时极少命中）。 */', '/** Some models leave literal "\\n" inside JSON strings; convert to newlines after the body is parsed (rarely matches Windows drive letters). */'),
    ('本轮要求execute证据，但没有 completed tool execution was recorded', 'This round requires execution evidence, but no completed tool execution was recorded'),
    ('// update原始内容（给copy功能用）', '// Update original content (used by copy function)'),
    ('// 从最近的Assistant message中获取ID', '// Get ID from the most recent assistant message'),
    ('// 将进度Details集成到tool调用区域（流式阶段Assistant message不挂 MCP  records，end时在此创建，避免图二整行 MCP 芯片样式）', '// Integrate progress details into the tool call area (during streaming, assistant messages have no MCP records; created here at end to avoid full-row MCP chip style)'),
    ('// 只 flush 终态title/正文; complete后的Details回看统一走后端分 PAGE，不再copy实时 DOM 快照。', '// Only flush final-state title/body; post-completion details review goes through backend pagination, no longer copying live DOM snapshots.'),
    ('// 进度 DOM 即将remove; 先Close仍处于 running 的tool摘要status。', '// Progress DOM is about to be removed; close tool summary status that is still running first.'),
    ('// 获取Assistant message元素', '// Get assistant message element'),
    ('// 查找或创建 MCP 区域（tool栏 + Tool list + 迭代时间线）', '// Find or create the MCP area (tool bar + tool list + iteration timeline)'),
    ("if (typeof window.t !== 'function') return '回到latest迭代';", "if (typeof window.t !== 'function') return 'Return to latest iteration';"),
    ("return value && value !== 'chat.returnToLatestProcessDetail' ? value : '回到latest迭代';", "return value && value !== 'chat.returnToLatestProcessDetail' ? value : 'Return to latest iteration';"),
    ('// 只有用户真正滚到底部才restoreAuto跟随; 保留 2px 兼容亚像素滚动。', '// Only restore auto-follow when the user genuinely scrolls to the bottom; keep 2px tolerance for sub-pixel scrolling.'),
    ('// running粘底会在 MutationObserver 与下一帧滚底之间短暂离底;', '// Sticky-to-bottom during running briefly detaches between MutationObserver and the next frame;'),
    ('// 只要用户still没主动上滑 detached，就不要把"回到latest迭代"按钮闪出来。', '// As long as the user has not actively scrolled up (detached), do not flash the "Return to latest iteration" button.'),
    ("'正在加载更早记录…'", "'Loading earlier records…'"),
    ("'正在加载update记录…'", "'Loading newer records…'"),
    ("'Load failed，点击重试'", "'Load failed, click to retry'"),
    ("'加载更早记录'", "'Load earlier records'"),
    ("'加载update记录'", "'Load newer records'"),
    ('* refreshrestorerunning会话时，迭代思考区有自己独立的滚动container。', '* When restoring a running session, the iterative thinking area has its own independent scroll container.'),
    ('* 历史Details首屏、后续分帧渲染和 SSE 字符增量都会继续增高该container，', '* The initial render of history details, subsequent frame-by-frame rendering, and SSE character increments all continue to increase the height of this container,'),
    ('* 因此不能只粘住外层 #chat-messages，也不能只在首屏complete时滚动一次。', '* so it is not enough to just stick to the outer #chat-messages, nor to scroll only once when the first screen completes.'),
    ('// 第一次小幅上滑时仍可能处在"距底部 32px"阈值内，不能在同一个 scroll', '// On the first small upward scroll, the position may still be within the "32px from bottom" threshold; do not'),
    ('// 事件里刚脱离又立即restore，otherwise持续output会把视口反复拉回底部。', '// detach and immediately re-attach within the same scroll event, otherwise continuous output will repeatedly pull the viewport back to the bottom.'),
    ('// refresh后重建历史迭代会引起no 用户输入的滚动锚定变化; 这种布局滚动', '// Rebuilding history iterations after refresh causes scroll anchor changes without user input; such layout scrolling'),
    ('// 不能stop内层latest内容跟随，只有明确用户意图或已分离status才保持分离。', '// must not stop the inner latest content from following; only explicit user intent or already-detached state should maintain separation.'),
    ('// 内层迭代区与外层Chat区分别粘底; 用户上滑内层后，本status会Pause两者的Auto跟随。', '// The inner iteration area and outer chat area each stick to the bottom; after the user scrolls up in the inner area, this state pauses auto-follow for both.'),
    ("return base + '（' + attempt + '/' + maxAttempts + '）';", "return base + ' (' + attempt + '/' + maxAttempts + ')';"),
    ("return base + '（' + attempt + '）';", "return base + ' (' + attempt + ')';"),
    ('// 同一主Agent可能从"进入Model"和"检测到tool批次"两 recordspath补发同一轮次。', '// The same main agent may resend the same round from both the "enter model" and "detected tool batch" record paths.'),
    ("title = icon + ' node complete' + (label ? (' · ' + label) : '') + (status ? ('（' + status + '）') : '');", "title = icon + ' node complete' + (label ? (' · ' + label) : '') + (status ? (' (' + status + ')') : '');"),
    ("': '⚠️ Eino streaming interrupted (' + agent + '）')", "': '⚠️ Eino streaming interrupted (' + agent + ')'"),
    ('// Immediately refresh task status（executefailed时Task status会update）', '// Immediately refresh task status (updated when execution fails)'),
    ('// 清理流式outputstatus', '// Clean up streaming output state'),
    ('// 清理tool流式output占位', '// Clean up tool streaming output placeholder'),
    ('// complete，update进度title（if进度消息stillexists）', '// Completed; update progress title (if progress message still exists)'),
    ('// 检查时间线中whether 有error items', '// Check whether there are error items in the timeline'),
    ('// Immediately refresh task status（确保Task status同步）', '// Immediately refresh task status (ensure task status is synchronized)'),
    ('// 延迟再次refreshTask status（确保后端completedstatusupdate）', '// Refresh task status again after a delay (ensure backend completed status is updated)'),
    ('// complete时Autocollapse所有Details（延迟一下确保response事件已处理）', '// Auto-collapse all details on completion (slight delay to ensure response events have been handled)'),
    ('// ifcannot 获取助手ID，尝试collapse所有Details', '// If assistant ID cannot be obtained, try to collapse all details'),
    ('// if有error，确保DetailsYescollapse的（error时应该defaultcollapse）', '// If there is an error, ensure details are collapsed (should be collapsed by default on error)'),
    ('// 再次确保collapse（延迟一点确保DOM已update）', '// Ensure collapse again (slight delay to ensure DOM has been updated)'),
    ('// 仅在事件处理前用户已在底部附近时跟随滚到底部（避免上滑看历史时被拉回）', '// Only scroll to bottom if the user was already near the bottom before the event (avoid pulling back while browsing history)'),
    ("let question = hitlApprovalTemplate('hitl.requestGeneric', '允许 Kestrel 调用 {{tool}}？', { tool: rawToolName });", "let question = hitlApprovalTemplate('hitl.requestGeneric', 'Allow Kestrel to call {{tool}}?', { tool: rawToolName });"),
    ("? hitlApprovalTranslate('hitl.requestVisitLongUrl', '允许 Kestrel 访问此地址？')", "? hitlApprovalTranslate('hitl.requestVisitLongUrl', 'Allow Kestrel to visit this URL?')"),
    ("hitlApprovalTemplate('hitl.requestVisitUrl', '允许 Kestrel 访问 {{URL}}？', { URL: URL }))", "hitlApprovalTemplate('hitl.requestVisitUrl', 'Allow Kestrel to visit {{URL}}?', { URL: URL }))"),
    ("hitlApprovalTranslate('hitl.requestBrowser', '允许 Kestrel 使用浏览器？');", "hitlApprovalTranslate('hitl.requestBrowser', 'Allow Kestrel to use the browser?');"),
    ("question = hitlApprovalTranslate('hitl.requestCommand', '允许 Kestrel execute这 recordsCommand？');", "question = hitlApprovalTranslate('hitl.requestCommand', 'Allow Kestrel to execute this command?');"),
    ("? hitlApprovalTranslate('hitl.requestModifyLongPath', '允许 Kestrel 修改此文件？')", "? hitlApprovalTranslate('hitl.requestModifyLongPath', 'Allow Kestrel to modify this file?')"),
    ("hitlApprovalTemplate('hitl.requestFile', '允许 Kestrel 修改 {{path}}？', { path: path }))", "hitlApprovalTemplate('hitl.requestFile', 'Allow Kestrel to modify {{path}}?', { path: path }))"),
    ("hitlApprovalTranslate('hitl.requestFiles', '允许 Kestrel 修改文件？');", "hitlApprovalTranslate('hitl.requestFiles', 'Allow Kestrel to modify files?');"),
    ("hitlApprovalTranslate('hitl.timeoutUnlimited', '不限时等待')", "hitlApprovalTranslate('hitl.timeoutUnlimited', 'Wait indefinitely')"),
    ("hitlApprovalTranslate('hitl.timeoutAutoReject', '到期Autoreject')", "hitlApprovalTranslate('hitl.timeoutAutoReject', 'Auto-reject on expiry')"),
    ("hitlApprovalTranslate('hitl.expiredAutoRejected', 'approvalTimed out，正在Autoreject…')", "hitlApprovalTranslate('hitl.expiredAutoRejected', 'Approval timed out, auto-rejecting…')"),
    ('// warning 等类型default没有内容区域; HITL 内联approval需要可Interactcontainer', '// Warning and similar types have no content area by default; HITL inline approval needs an interactive container'),
    ("/timeout|超时/i", "/timeout/i"),
    ("statusText = tr('hitl.expiredRejected', 'Approval timeout，已Autoreject');", "statusText = tr('hitl.expiredRejected', 'Approval timed out, auto-rejected');"),
    ("(haseditedArgs ? tr('hitl.auditEditedApproved', 'Audit Agent 已修改参数并批准') : tr('hitl.auditApproved', 'Audit Agent 已批准'))", "(haseditedArgs ? tr('hitl.auditEditedApproved', 'Audit Agent edited parameters and approved') : tr('hitl.auditApproved', 'Audit Agent approved'))"),
    ("(haseditedArgs ? tr('hitl.humanEditedApproved', '已修改参数并允许') : tr('hitl.humanApproved', '已允许一次'))", "(haseditedArgs ? tr('hitl.humanEditedApproved', 'Edited parameters and allowed') : tr('hitl.humanApproved', 'Allowed once'))"),
    ("tr('hitl.viewEditedArgs', 'view修改后的参数')", "tr('hitl.viewEditedArgs', 'View edited parameters')"),
    ("tr('hitl.auditReviewEditing', 'Auto审查并校正中')", "tr('hitl.auditReviewEditing', 'Auto-reviewing and correcting')"),
    ("tr('hitl.auditReviewing', 'Autoreview中')", "tr('hitl.auditReviewing', 'Auto-reviewing')"),
    ("const explanation = tr('hitl.auditReviewExplanation', '经过谨慎hint的审查智能体正在审查此请求，approve后才会execute。');", "const explanation = tr('hitl.auditReviewExplanation', 'A carefully prompted review agent is reviewing this request; it will only execute after approval.');"),
    ("tr('hitl.waitingHumanReview', '等待manual审查')", "tr('hitl.waitingHumanReview', 'Awaiting manual review')"),
    ("tr('hitl.waitingHumanApproval', '等待Manual approval')", "tr('hitl.waitingHumanApproval', 'Awaiting manual approval')"),
    ("tr('hitl.saveEditedAndAllow', 'save修改并允许')", "tr('hitl.saveEditedAndAllow', 'Save edits and allow')"),
    ("tr('hitl.allowOnce', '允许一次')", "tr('hitl.allowOnce', 'Allow once')"),
    ("tr('hitl.editRequestDetails', 'view或修改Request parameters')", "tr('hitl.editRequestDetails', 'View or edit request parameters')"),
    ("tr('hitl.viewRequestDetails', 'view请求Details')", "tr('hitl.viewRequestDetails', 'View request details')"),
    ("tr('hitl.addApprovalComment', '添加approval备注（可选）')", "tr('hitl.addApprovalComment', 'Add approval comment (optional)')"),
    ("'例如: 仅允许只", "'e.g.: only allow read-only"),
    ("statusEl.textContent = 'JSON 参数Invalid format';", "statusEl.textContent = 'JSON parameters invalid format';"),
    ("statusEl.textContent = 'Submitfailed，请重试';", "statusEl.textContent = 'Submit failed, please try again';"),
    ("statusEl.textContent = 'approval函数未加载';", "statusEl.textContent = 'Approval function not loaded';"),
    ("const msg = decision === 'approve' ? 'approved，等待execute继续...' : 'rejected，反馈已交给Model继续迭代...';", "const msg = decision === 'approve' ? 'Approved, waiting for execution to continue...' : 'Rejected, feedback sent to model to continue iteration...';"),
    ('// 鼠标/触摸点击必须从approval按钮自身start; 键盘 Enter/Escape 的 detail 为 0，仍可normal使用。', '// Mouse/touch clicks must originate from the approval button itself; keyboard Enter/Escape have detail = 0 and still work normally.'),
    ('// 这可以Block滚动定位按钮隐藏后被浏览器重新定向到底部approval按钮的合成 click。', '// This blocks synthetic clicks that the browser redirects to the bottom approval button after the scroll-anchor button is hidden.'),
    ('// 新task尚Unbound会话 ID 时不能让otherrunningChat的迟到approval覆盖输入框。', '// When a new task has no bound conversation ID yet, late-arriving approvals from other running chats must not overwrite the input box.'),
    ('// 有明确会话 ID 的approval面板只允许显示在同一个current Chat中。', '// An approval panel with a specific conversation ID may only appear in the same current chat.'),
    ("hitlApprovalTranslate('hitl.waitingApprovalShort', '等待批准')", "hitlApprovalTranslate('hitl.waitingApprovalShort', 'Awaiting approval')"),
    ("escapeHtml(ok ? '已允许一次' : 'Manual approvalrejected')", "escapeHtml(ok ? 'Allowed once' : 'Manual approval rejected')"),
    ("'WorkflowsPause，等待你confirm", "'Workflows paused, waiting for your confirmation"),
    ('<span class="HITL-context-label">备注（可选）</span>', '<span class="HITL-context-label">Comment (optional)</span>'),
    ("statusEl.textContent = (body && body.error) ? body.error : 'Submitfailed，请重试';", "statusEl.textContent = (body && body.error) ? body.error : 'Submit failed, please try again';"),
    ("statusEl.textContent = approved ? 'approved，Workflows继续Executing…' : 'rejected';", "statusEl.textContent = approved ? 'Approved, workflows continuing…' : 'Rejected';"),
    ("statusEl.textContent = approved ? 'approved，Workflows继续execute' : 'rejected';", "statusEl.textContent = approved ? 'Approved, workflows will continue' : 'Rejected';"),
    ('* refresh或切换会话后: 根据 workflow_runs(awaiting_hitl) restoreWorkflows内联approval入口。', '* After refresh or session switch: restore the workflows inline approval entry based on workflow_runs(awaiting_hitl).'),
    ("console.error('加载过程Detailsfailed（Workflows HITL restore）:', e);", "console.error('Failed to load process details (Workflows HITL restore):', e);"),
    ('* refresh或切换会话后: 根据Pending approval记录restore时间线里的内联approval入口，并expandDetails区。', '* After refresh or session switch: restore inline approval entries in the timeline based on pending approval records, and expand the details area.'),
    ('// Task listYescurrent 进程的权威run态。service重启或taskCancel后，即使approval查询', '// The task list is the authoritative running state for the current process. After service restart or task cancellation, even if approval queries'),
    ('// 短暂读到旧 pending 记录，也不能重新挂载approval入口和倒计时。', '// briefly read old pending records, the approval entry and countdown must not be re-mounted.'),
    ("console.error('加载过程Detailsfailed（HITL restore）:', e);", "console.error('Failed to load process details (HITL restore):', e);"),
    ('* no  SSE 时（例如refresh  page后）: 从 DB 拉取最后一 recordsAssistant message的过程Details并重绘时间线，便于approvalapprove后仍能看到execute进展。', '* When there is no SSE (e.g. after page refresh): fetch the last assistant message process details from the DB and redraw the timeline, so execution progress is still visible after approval.'),
    ('// restore流程必须遍历all分 PAGE。直接请求no 参数接口只会returnEarliest 50  records，', '// The restore process must traverse all paginated pages. Requesting the no-parameter endpoint directly only returns the earliest 50 records,'),
    ('// 长taskrefresh后会表现为"旧轮次 → current 实时轮次"的中间历史缺失。', '// and after refreshing a long task this manifests as missing intermediate history between "old rounds → current live round".'),
    ('* task-events 订阅exists一个不可避免的竞态: Task list仍显示 running，但在 SSE 请求', '* task-events subscription has an unavoidable race condition: the task list still shows running, but before the SSE request'),
    ('* 真正建立前task已经complete。此时不能只stop计时，必须从数据库对账最后一 records助手正文。', '* is truly established, the task has already completed. In this case it is not enough to just stop the timer; the last assistant body must be reconciled from the database.'),
    ('* 订阅runningtask的 SSE image（GET /api/agent-loop/task-events），用于 HITL approve后主Connection disconnected时接续 UI。', '* Subscribe to the SSE stream of a running task (GET /api/agent-loop/task-events), used to resume UI when the main connection disconnects after HITL approval.'),
    ('// 先发起 SSE 请求，再加载长过程Details，避免Details分 page期间产生的增量完全错过。', '// Start the SSE request first, then load long process details, to avoid missing increments produced during details pagination.'),
    ('// Details分 page可能持续较久; 先接住网络abnormal，避免在稍后 await 前产生', '// Details pagination may take a while; catch network errors early to avoid'),
    ('// unhandledrejection，再交给current  attach 流程统一清理。', '// unhandledRejection before the subsequent await, letting the current attach flow handle cleanup uniformly.'),
    ('// running会话可能远超default 50  records; 切换时只restorelatest一 PAGE，旧记录由滚动分 page补齐。', '// Running sessions may exceed the default 50 records; on switch only restore the latest page, old records are filled in by scroll pagination.'),
    ('// 历史重绘会重建时间线节点，需重新挂载 HITL approval入口。', '// History redraw rebuilds timeline nodes; HITL approval entries need to be re-mounted.'),
    ('// task-events 补流期间持续跟随迭代思考区; 用户向上滚动Details时会立即解除。', '// Continuously follow the iterative thinking area during task-events stream catch-up; detach immediately when the user scrolls up in the details area.'),
    ('// refresh后的初始消息渲染已经滚到底部，但restorelatest一 pageDetails会再次增高 DOM。', '// The initial message rendering after refresh has already scrolled to the bottom, but restoring the latest page of details will increase the DOM height again.'),
    ('// 若用户期间没有主动上滑，complete补 page后重新精确粘底; 主动浏览历史时不抢滚动。', '// If the user did not actively scroll up during this time, re-snap precisely to the bottom after the catch-up page completes; do not compete for scrolling while browsing history.'),
    ('// taskend会Close事件总线; 若终态帧在连接竞态或拥塞中丢失，仍从 DB 对账正文。', '// Task end closes the event bus; if the final-state frame is lost due to connection race or congestion, reconcile the body from DB.'),
    ('// loadConversation 使用轻量消息接口，会把Details重新置为懒加载status;', '// loadConversation uses the lightweight message API, which resets details to lazy-load state;'),
    ('// task终态再从 DB 全量对账一次，补回订阅建立期间可能错过的事件。', '// do a full DB reconciliation once more at task end to recover any events missed while the subscription was being established.'),
    ('// 补流complete即回到终态摘要; refresh期间为展示实时迭代而Autoexpand的Details', '// Once the catch-up stream completes, return to the final-state summary; details auto-expanded during refresh to show live iterations'),
    ('// 不应继续保持expand。用户之后仍可approve"expandDetails"手动view。', '// should not remain expanded. The user can still manually expand details afterwards.'),
    ('// 最终消息和Details重绘都会增高 DOM; 仅当用户之前仍在跟随时重新粘底。', '// Both the final message and details redraw increase DOM height; re-snap to bottom only if the user was following before.'),
    ('/** 从Tool parameters提取短摘要（URL/Command等），便于同名tool批量调用时区分 */', '/** Extract a short summary from tool parameters (URL, command, etc.) to distinguish batch calls to tools with the same name */'),
    ("return '调用tool: ' + name + (tot ? ' (' + idx + '/' + tot + ')' : '');", "return 'Calling tool: ' + name + (tot ? ' (' + idx + '/' + tot + ')' : '');"),
    ('工具调用已被安全规则拦截', 'Tool call blocked by security rule'),
    ('工具调用已被Safe规则Block', 'Tool call blocked by Safe rule'),
    ('tool调用已被Safe规则Block', 'Tool call blocked by Safe rule'),
    ('/(tool已Submit到后台execute|本次等待已到达|wait_timeout|wait timeout|background execution|后台execute|仍未complete|still executing in background)/i', '/(tool has been submitted for background execution|wait limit reached|wait_timeout|wait timeout|background execution|still executing in background)/i'),
    ("return '后台Executing';", "return 'Executing in background';"),
    ("'no 结果'", "'No result'"),
    ("pendingText: state.hitlData.resolved ? 'approved，等待execute结果' : 'Awaiting approval，approve后execute'", "pendingText: state.hitlData.resolved ? 'Approved, awaiting execution result' : 'Awaiting approval, will execute after approval'"),
    ("'参数:'", "'Parameters:'"),
    ("'<span class=\"tool-args-HITL-edited\">已按 HITL 改参execute</span>'", "'<span class=\"tool-args-HITL-edited\">Executed with HITL-edited parameters</span>'"),
    ('// 实时事件、refresh后的历史记录和Language switch都复用同一套toolstatus展示。', '// Live events, post-refresh history records, and language switches all reuse the same tool status display.'),
    ('// updatetool调用status', '// Update tool call status'),
    ('// 添加时间线Project', '// Add timeline item'),
    ("const branchText = matched ? 'Yes（true）' : 'No（false）';", "const branchText = matched ? 'Yes (true)' : 'No (false)';"),
    ('<span class="workflow-agent-io-label">表达式</span>', '<span class="workflow-agent-io-label">Expression</span>'),
    ("'（empty）'", "'(empty)'"),
    ('<span class="workflow-agent-io-label">结果</span>', '<span class="workflow-agent-io-label">Result</span>'),
    ('<span class="workflow-agent-io-label">连线condition</span>', '<span class="workflow-agent-io-label">Edge condition</span>'),
    ("'已collapse前 ' + count + '  records实时过程Details，taskcomplete后可按 pageview完整记录'", "'Collapsed ' + count + ' real-time process detail records; full records can be viewed by page after task completion'"),
    ("'主AgentRound ' + minIteration + ''", "'Main agent round ' + minIteration + ''"),
    ("'主AgentRound ' + minIteration + '–' + maxIteration + ''", "'Main agent rounds ' + minIteration + '–' + maxIteration + ''"),
    ('// 始终放在已保留Details之前; 配合 sticky 样式，viewlatest内容时也能感知历史已裁剪。', '// Always placed before retained details; with sticky styling, the user can sense that history has been trimmed while viewing latest content.'),
    ('// Generate唯一ID', '// Generate unique ID'),
    ('// 记录类型与参数，便于 languagechange 时refreshtitle文案', '// Record type and parameters for refreshing title text on languagechange'),
    ("'结果记录缺失'", "'Result record missing'"),
    ('// 使用传入的createdAt时间，if没有则使用current 时间（向后兼容）', '// Use the passed createdAt time; fall back to current time if absent (backwards compatibility)'),
    ('// save事件时间 ISO，Language switch时可重算时间格式', '// Save event time as ISO string so the time format can be recalculated on language switch'),
    ('// 根据类型添加详细内容', '// Add detailed content based on type'),
    ('<span class="workflow-agent-io-label">输入</span>', '<span class="workflow-agent-io-label">Input</span>'),
    ("'No 输入Preview'", "'No input preview'"),
    ('// 主Agent每次重新进入Model才形成一轮; 子Agent的Step保留普通时间线样式，', '// Each time the main agent re-enters the model forms a new round; sub-agent steps retain the regular timeline style,'),
    ('// 避免把同一轮中的专家调用误显示成新的主迭代分组。', '// to avoid misrepresenting expert calls within the same round as a new main iteration group.'),
    ('// 对于tool调用和结果，default显示摘要', '// For tool calls and results, show summary by default'),
    ('// returnitem ID以便后续update', '// Return item ID for subsequent updates'),
    ('// 加载activeTask list', '// Load active task list'),
    ("'获取activeTask failed'", "'Failed to get active tasks'"),
    ('// servicestop、重启或Sign in失效时，旧进程task不可能仍可approval。', '// When service stops, restarts, or sign-in expires, old process tasks cannot still be approved.'),
    ('// 立即clear本地run/approval缓存，防止倒计时和按钮继续保持Available。', '// Immediately clear local run/approval cache to prevent countdown and buttons from remaining available.'),
    ("console.error('获取activeTask failed:', error);", "console.error('Failed to get active tasks:', error);"),
    ("'cannot 获取taskStatus: '", "'Cannot get task status: '"),
    ('// 用户可能在taskrefresh排队后、此微taskexecute前切换了会话。', '// The user may have switched sessions after the task refresh was queued but before this microtask executes.'),
    ('// 不允许旧会话补流Cancel或覆盖用户刚发起的target会话加载。', '// Do not allow old session catch-up streams to cancel or overwrite the target session load just initiated by the user.'),
    ('// 另一tags page已addUser message和running助手轮次; 先重载轻量历史，避免把补流挂到旧Assistant message上。', '// Another tab has already added a user message and a running assistant round; reload lightweight history first to avoid attaching the catch-up stream to an old assistant message.'),
    ("console.warn('同步othertags page的runningChatfailed:', error);", "console.warn('Failed to sync running chat from another tab:', error);"),
    ("'view会话'", "'View conversation'"),
    ('// 只有非最终status的task才显示stop按钮', '// Only show stop button for tasks that are not in a final state'),
    ('// 监控面板status', '// Monitor panel state'),
    ('// 从 localStorage 读取save的每 page显示数量，default为 20', '// Read saved per-page count from localStorage, default is 20'),
    ('// 等待本轮complete后再安排下一轮，避免 WSL 或慢网络下请求重叠。', '// Wait for the current round to complete before scheduling the next, to avoid overlapping requests on WSL or slow networks.'),
    ('// refreshMonitorPanel 已负责展示error;询仍应继续。', '// refreshMonitorPanel already handles displaying errors; polling should continue.'),
    ('// 切换到MCP监控  PAGE', '// Switch to MCP monitor page'),
    ('// 初始化每 page显示数量选择器', '// Initialize per-page count selector'),
    ('// 改变每 page显示数量', '// Change items per page'),
    ('// save到 localStorage', '// Save to localStorage'),
    ('monitorState.pagination. PAGE = 1; // Reset到First  PAGE', 'monitorState.pagination. PAGE = 1; // Reset to first page'),
    ('// refresh数据', '// Refresh data'),
    ('// 后台轮询时保留current 趋势图，避免每 3  sec重新进入加载态并触发闪烁。', '// Preserve the current trend chart during background polling to avoid re-entering loading state and flickering every 3 seconds.'),
    ("'获取监控数据failed'", "'Failed to get monitoring data'"),
    ("console.error('refresh监控面板failed:', error);", "console.error('Failed to refresh monitor panel:', error);"),
    ('// 处理toolsearch输入（防抖）', '// Handle tool search input (debounced)'),
    ('// Set a new timer，500ms后executefilter', '// Set a new timer; execute filter after 500ms'),
    ('// 当filtercondition改变时，从后端Retry数据', '// When filter conditions change, retry data from backend'),
    ('// empty列表渲染会clearexecute区，因此这种情况下也需要restore分 page控件。', '// Rendering an empty list clears the execution area, so pagination controls must also be restored in this case.'),
    ("mcpMonitorT('scopeCumulative') || '累计'", "mcpMonitorT('scopeCumulative') || 'Cumulative'"),
    ("'该时段多数时间为 0，峰值 ${peak} 次出现在 ${peakTime}'", "'Most of this period had 0 calls; peak of ${peak} at ${peakTime}'"),
    ("mcpMonitorT('timelineactiveMoments') || monitorFallback('active时段', 'active moments')", "mcpMonitorT('timelineactiveMoments') || monitorFallback('Active periods', 'active moments')"),
    ("mcpMonitorT('timelineNoData') || monitorFallback('该时段No 调用', 'No calls in this period')", "mcpMonitorT('timelineNoData') || monitorFallback('No calls in this period', 'No calls in this period')"),
    ("monitorFallback('切换Time rangeviewother时段，或在Chat/task中调用 MCP tool'", "monitorFallback('Switch the time range or invoke MCP tools in chat or tasks'"),
    ("mcpMonitorT('timelineLoading') || monitorFallback('趋势Loading…', 'Loading trend…')", "mcpMonitorT('timelineLoading') || monitorFallback('Loading trend…', 'Loading trend…')"),
    ("mcpMonitorT('timelineHint') || monitorFallback('alltool合计', 'all tools combined')", "mcpMonitorT('timelineHint') || monitorFallback('All tools combined', 'all tools combined')"),
    ("mcpMonitorT('timelineLoaderror') || monitorFallback('cannot 加载调用趋势'", "mcpMonitorT('timelineLoadError') || monitorFallback('Failed to load call trend'"),
    ("'区间内 ${summaryTotal} 次 · 峰值 ${peak}'", "'${summaryTotal} calls in range · peak ${peak}'"),
    ("mcpMonitorT('timelineTotalLegend') || '总调用'", "mcpMonitorT('timelineTotalLegend') || 'Total calls'"),
    ("mcpMonitorT('toolStatsTitle') || monitorFallback('tool统计', 'Tool statistics')", "mcpMonitorT('toolStatsTitle') || monitorFallback('Tool statistics', 'Tool statistics')"),
    ("mcpMonitorT('timelineTitle') || monitorFallback('调用趋势', 'Call trend')", "mcpMonitorT('timelineTitle') || monitorFallback('Call trend', 'Call trend')"),
    ("mcpMonitorT('toolStatshint') || monitorFallback('点击色 records或列表行filter下方execute记录'", "mcpMonitorT('toolStatsHint') || monitorFallback('Click a bar segment or list row to filter execution records below'"),
    ("已filter: ${filt", "Filtered: ${filt"),
    ("mcpMonitorT('barVolumeLegend') || ' records长表示相对调用量'", "mcpMonitorT('barVolumeLegend') || 'Bar length indicates relative call volume'"),
    ("mcpMonitorT('distTitle') || '调用分布'", "mcpMonitorT('distTitle') || 'Call distribution'"),
    ("mcpMonitorT('distClickhint') || '点击扇区filterexecute记录'", "mcpMonitorT('distClickHint') || 'Click a sector to filter execution records'"),
    ("mcpMonitorT('distClickhint') || '点击扇区filter'", "mcpMonitorT('distClickHint') || 'Click a sector to filter'"),
    ("mcpMonitorT('distothersNofilter') || 'othertoolcannot 单独filter'", "mcpMonitorT('distOthersNoFilter') || 'Other tools cannot be filtered individually'"),
    ("mcpMonitorT('distTop6Share', { n: MCP_STATS_TOP_N }) || `Top ${MCP_STATS_TOP_N} 占all调用`", "mcpMonitorT('distTop6Share', { n: MCP_STATS_TOP_N }) || `Top ${MCP_STATS_TOP_N} share of all calls`"),
    ("|| `${s.name}，占 ${s.pct}%，${s.calls} 次`)", "|| `${s.name}, ${s.pct}%, ${s.calls} calls`)"),
    ("|| `${s.name}，${s.calls} 次调用，占 ${s.pct}%`", "|| `${s.name}, ${s.calls} calls, ${s.pct}%`"),
    ("? (mcpMonitorT('distTitle') || '占比') : `Top ${MCP_STATS_TOP_N}`", "? (mcpMonitorT('distTitle') || 'Distribution') : `Top ${MCP_STATS_TOP_N}`"),
    ("? (mcpMonitorT('distTotalCalls', { n: totals.total }) || `Total ${totals.total} 次调用`)", "? (mcpMonitorT('distTotalCalls', { n: totals.total }) || `Total ${totals.total} calls`)"),
    ("`最后refresh ${timeText} · Total ${toolCount} tool`", "`Last refreshed ${timeText} · ${toolCount} tools`"),
    ("execute记录保留 ${retentionDays}  days，超期Auto清理", "Execution records retained for ${retentionDays} days, auto-purged on expiry"),
    ("mcpMonitorT('totalCalls') || monitorFallback('总调用次数', 'Total calls')", "mcpMonitorT('totalCalls') || monitorFallback('Total calls', 'Total calls')"),
    ("mcpMonitorT('successRate') || monitorFallback('success率', 'success rate')", "mcpMonitorT('successRate') || monitorFallback('Success rate', 'success rate')"),
    ("mcpMonitorT('lastCall') || monitorFallback('最近一次调用', 'Last call')", "mcpMonitorT('lastCall') || monitorFallback('Last call', 'Last call')"),
    ("`终止 ${totals.neutral}`", "`Stopped ${totals.neutral}`"),
    ("success率仅统计success和failed的调用，不包含SafeBlock和终止", "Success rate counts only successful and failed calls, excluding safe-blocked and stopped"),
    ("mcpMonitorT('columnCalls') || '调用'", "mcpMonitorT('columnCalls') || 'Calls'"),
    ("mcpMonitorT('columnShare') || '占比'", "mcpMonitorT('columnShare') || 'Share'"),
    ("mcpMonitorT('columnsuccessRate') || 'success率'", "mcpMonitorT('columnSuccessRate') || 'Success rate'"),
    ("|| `${name}，${total} 次调用，success率 ${toolRate}%`)", "|| `${name}, ${total} calls, success rate ${toolRate}%`)"),
    ("`${name}，${total} 次调用，No complete结果，点击viewexecut", "`${name}, ${total} calls, no completed results, click to view execut"),
    ('/** MCP 合并面板左侧: 堆叠占比 records + tool排行列表（no 饼图/表格套娃） */', '/** MCP combined panel left side: stacked share bar + tool ranking list (no pie chart/table nesting) */'),
    ("`Top ${MCP_STATS_TOP_N} 占 ${topNSharePct}% · Total ${totals.total} 次`", "`Top ${MCP_STATS_TOP_N} accounts for ${topNSharePct}% · Total ${totals.total} calls`"),
    ("|| `${displayName}，占 ${s.pct}%，${s.calls} 次`", "|| `${displayName}, ${s.pct}%, ${s.calls} calls`"),
    ("|| `${name}，${total} 次，success率 ${toolRate}%`)", "|| `${name}, ${total} calls, success rate ${toolRate}%`)"),
    ("mcpMonitorT('toolStatsTitle') || 'tool统计'", "mcpMonitorT('toolStatsTitle') || 'Tool statistics'"),
    ('/** @deprecated 保留供other  PAGE; MCP 监控主面板请用 renderMcpStatsToolTable */', '/** @deprecated Retained for other pages; MCP monitor main panel should use renderMcpStatsToolTable */'),
    ("mcpMonitorT('noStatsData') || monitorFallback('No 统计数据', 'No statistical data')", "mcpMonitorT('noStatsData') || monitorFallback('No statistical data', 'No statistical data')"),
    ("mcpMonitorT('noCallsYet') || monitorFallback('No 调用', 'No calls yet')", "mcpMonitorT('noCallsYet') || monitorFallback('No calls yet', 'No calls yet')"),
    ("mcpMonitorT('nocompletedYet') || monitorFallback('No 有效complete', 'No completed outcomes yet')", "mcpMonitorT('noCompletedYet') || monitorFallback('No completed outcomes yet', 'No completed outcomes yet')"),
    ("mcpMonitorT('rateHealthy') || monitorFallback('run平稳', 'running smoothly')", "mcpMonitorT('rateHealthy') || monitorFallback('Running smoothly', 'running smoothly')"),
    ("mcpMonitorT('rateCritical') || monitorFallback('failed率偏高', 'High failure rate')", "mcpMonitorT('rateCritical') || monitorFallback('High failure rate', 'High failure rate')"),
    ("monitorFallback('existsfailed调用'", "monitorFallback('Some failures detected'"),
    ('// 根据whether 有filtercondition显示不同的hint', '// Show different hints depending on whether filter conditions are active'),
    ("monitorFallback('No execute记录'", "monitorFallback('No execution records'"),
    ("monitorFallback('在Chat或task中调用 MCP tool后，exe", "monitorFallback('Execution records will appear after calling MCP tools in chat or tasks', 'exe"),
    ('// 隐藏批量操作栏', '// Hide batch action bar'),
    ('// 由于filter已经在后端complete，这里直接使用所有传入的execute记录', '// Since filtering is already done on the backend, use all passed execution records directly'),
    ('// 不再需要前端再次filter，因为后端已经return了filter后的数据', '// No need to filter on the frontend again, as the backend already returned filtered data'),
    ("'delete此execute记录'", "'Delete this execution record'"),
    ("'终止'", "'Terminate'"),
    ('// 清除"Loading..."等hint info', '// Clear "Loading..." and other hint text'),
    ("'耗时'", "'Duration'"),
    ("'操作'", "'Actions'"),
    ('// update批量操作status', '// Update batch action state'),
    ('// 以 execution ID 为 key 对账，只操作add、delete、换序或内容变化的行。', '// Reconcile using execution ID as key; only add, delete, reorder, or update rows whose content has changed.'),
    ('//询结果未变化时只原位refreshrunning记录的耗时，避免重建整张表格。', '// When query results have not changed, only refresh the duration of running records in-place, avoiding rebuilding the entire table.'),
    ('// 渲染监控面板分 page控件', '// Render monitor panel pagination controls'),
    ('// remove旧的分 page控件', '// Remove old pagination controls'),
    ('// 始终显示分 page控件', '// Always show pagination controls'),
    ('// 处理没有数据的情况', '// Handle the case where there is no data'),
    ('// deleteexecute记录', '// Delete execution record'),
    ("'OK要delete此execute记录吗？此", "'Are you sure you want to delete this execution record? This"),
    ("'deleteexecute记录failed'", "'Failed to delete execution record'"),
    ('// deleted successfully后refreshcurrent   PAGE', '// Refresh current page after successful deletion'),
    ("'execute记录已delete'", "'Execution record deleted'"),
    ("console.error('deleteexecute记录failed:', error);", "console.error('Failed to delete execution record:', error);"),
    ('// 切换单 recordsexecute记录选中status（持久化到 monitorState，避免轮询refresh后丢失）', '// Toggle single execution record selection state (persisted to monitorState to avoid loss on polling refresh)'),
    ('// updateSelect all复选框status（仅反映current  PAGE）', '// Update select-all checkbox state (reflects current page only)'),
    ('// 切换Select all', '// Toggle select all'),
    ('// 批量deleteexecute记录', '// Batch delete execution records'),
    ("'请先选择要delete的execute记录'", "'Please select execution records to delete first'"),
    ("'OK要delete选", "'Are you sure you want to delete the selected"),
    ("'批量deleteexecute记录failed'", "'Failed to batch delete execution records'"),
    ("console.error('批量deleteexecute记录failed:', error);", "console.error('Failed to batch delete execution records:', error);"),
    ("' 分'", "' min'"),
    ('* Language switch后refreshChat page已渲染的进度 records、时间线title与时间格式（避免仍显示English或 AM/PM）', '* After a language switch, refresh progress records, timeline titles, and time formats already rendered on the Chat page (to avoid displaying stale language or AM/PM).'),
    ('// 进度块内stop按钮: 未disable时统一为current Language的「stop task」（避免仍显示 stop task）', '// Stop button inside progress block: when not disabled, always show "Stop task" in the current language (avoid showing stale text).'),
    ('// 时间线 items: 按类型重算title，并重绘时间戳', '// Timeline items: recalculate title by type and redraw timestamps'),
    ('// Details区「expand/collapse」按钮', '// Details area expand/collapse button'),
]

for old, new in replacements:
    content = content.replace(old, new)

with open('web/static/js/monitor.js', 'w', encoding='utf-8') as f:
    f.write(content)

lines = content.split('\n')
hits = [(i+1, l) for i, l in enumerate(lines) if re.search(r'[\u4e00-\u9fff\u3000-\u303f\uff00-\uffef]', l)]
print(f'Remaining in monitor.js: {len(hits)}')
for n, t in hits[:30]:
    print(f'  {n}: {t.strip()[:120]}')
