#!/usr/bin/env python3
"""Translate all Chinese text in index.html to English."""
import re

# Map from Chinese text to English translation.
# These are i18n fallback texts and HTML comments in index.html.
REPLACEMENTS = [
    # Login
    ("登录", "Sign In", True),  # restricted to data-i18n contexts
    ("使用平台账号登录，默认管理员为 admin。", "Sign in with your platform account. The default admin username is admin."),
    ("用户名", "Username"),
    ("密码", "Password"),
    ("输入登录密码", "Enter login password"),
    ("密码可见性切换", "Toggle password visibility"),
    # Header
    ("当前版本", "Current version"),
    ("API 文档", "API Docs"),
    ("跟随系统", "Follow system"),
    ("中文", "Chinese"),
    ("事件通知", "Event Notifications"),
    ("全部标记已读", "Mark all as read"),
    ("暂无新事件", "No new events"),
    ("用户菜单", "User menu"),
    ("当前用户", "Current user"),
    ("绑定机器人账号", "Bind robot account"),
    ("退出登录", "Sign Out"),
    # HTML comments
    ("<!-- 主侧边栏 -->", "<!-- Main sidebar -->"),
    ("<!-- C2 侧栏入口（带子菜单） -->", "<!-- C2 sidebar entry (with sub-menu) -->"),
    ("<!-- 内容区域 -->", "<!-- Content area -->"),
    ("<!-- 仪表盘页面 -->", "<!-- Dashboard page -->"),
    ("<!-- 关键提醒条（仅当存在严重风险时渲染，默认 hidden）；右侧 × 可在 session 内忽略 -->", "<!-- Critical alert bar (rendered only when serious risk exists, hidden by default); right-side × can be dismissed within the session -->"),
    ("<!-- 第一行：核心 KPI（关键指标置顶 + 副标徽章承载次级信息） -->", "<!-- First row: core KPIs (key metrics at top + sub-label badges carry secondary info) -->"),
    ("<!-- 两列主内容区 -->", "<!-- Two-column main content area -->"),
    ("<!-- 风险概览卡：填充 donut 左侧留白；提供「结论性」洞察（风险等级/加权分/待处理计数/最新时间），", "<!-- Risk overview card: fills whitespace left of donut; provides 'conclusive' insights (risk level/weighted score/pending count/latest time),"),
    ("          与右侧 legend 的「明细」形成互补，避免和下方「最近漏洞」列表重复 -->", "          complementing the right legend's 'details', avoiding duplication with the recent-vulnerabilities list below -->"),
    ("<!-- 处置状态 + 修复进度（利用 by_status 数据，避免下半部分留白） -->", "<!-- Disposition status + fix progress (using by_status data, avoiding whitespace in the lower half) -->"),
    ("<!-- 接入概览：C2 / WebShell Tab 切换（样式同「最近漏洞 / 近期事实」） -->", "<!-- Access overview: C2 / WebShell tab switching (same style as 'Recent vulnerabilities / Recent facts') -->"),
    ("<!-- 推荐操作：基于当前数据状态智能生成（如「修复 4 个待处理严重漏洞」「审批 2 个 HITL」），", "<!-- Recommended actions: intelligently generated based on current data state (e.g. 'Fix 4 pending critical vulnerabilities', 'Approve 2 HITLs'),"),
    ("         比纯静态导航更有意义；当没有任何推荐时整个 section 隐藏 -->", "         more meaningful than static navigation; the entire section is hidden when there are no recommendations -->"),
    ("<!-- 最近事件：拉 /api/notifications/summary 取最新 3 条；空时整个隐藏 -->", "<!-- Recent events: fetches latest 3 from /api/notifications/summary; hidden entirely when empty -->"),
    ("<!-- \"开始你的安全之旅\" CTA：默认显示；当用户已经有数据（任务/漏洞/调用）后，由 JS 隐藏避免冗余 -->", '<!-- "Start your security journey" CTA: shown by default; hidden by JS once the user has data (tasks/vulnerabilities/calls) to avoid redundancy -->'),
    ("<!-- 对话页面 -->", "<!-- Chat page -->"),
    ("<!-- 历史对话侧边栏（可折叠，与主导航侧边栏类似） -->", "<!-- Conversation history sidebar (collapsible, similar to the main nav sidebar) -->"),
    ("<!-- 头部一行：折叠与「新任务」并排；任务底层复用会话数据 -->", "<!-- Header row: collapse toggle and 'New task' side by side; tasks reuse session data internally -->"),
    ("<!-- 项目搜索 -->", "<!-- Project search -->"),
    ("<!-- 项目文件夹：复用对话底部项目选择器的真实项目数据 -->", "<!-- Project folders: reuses real project data from the conversation bottom project selector -->"),
    ("<!-- 按项目筛选对话 -->", "<!-- Filter conversations by project -->"),
    ("<!-- 最近对话 -->", "<!-- Recent conversations -->"),
    ("<!-- 对话界面 -->", "<!-- Chat interface -->"),
    ("<!-- 会话顶部栏（只在有会话选中时显示） -->", "<!-- Session top bar (only shown when a session is selected) -->"),
    ("<!-- External MCP 服务器健康度：N 运行 / N 异常；只有配置过 External MCP 才显示 -->", "<!-- External MCP server health: N running / N error; only shown when External MCP has been configured -->"),
    # Nav groups and items
    ("工作台", "Workbench"),
    ("仪表盘", "Dashboard"),
    ("对话", "Chat"),
    ("安全防护", "Security"),
    ("安全作业", "Operations"),
    ("项目管理", "Projects"),
    ("资产管理", "Assets"),
    ("漏洞管理", "Vulnerabilities"),
    ("任务管理", "Tasks"),
    ("工作流", "Workflows"),
    ("WebShell管理", "WebShell"),
    ("文件管理", "Files"),
    ("能力中心", "Capabilities"),
    ("MCP状态监控", "MCP Monitor"),
    ("MCP管理", "MCP Management"),
    ("知识", "Knowledge"),
    ("检索历史", "Retrieval History"),
    ("知识管理", "Knowledge Management"),
    ("技能", "Skills"),
    ("技能状态", "Skills Status"),
    ("技能管理", "Skills Management"),
    ("智能体", "Agents"),
    ("智能体管理", "Agents Management"),
    ("角色", "Roles"),
    ("角色管理", "Role Management"),
    ("平台管理", "Administration"),
    ("平台权限", "Platform RBAC"),
    ("系统设置", "Settings"),
    # Dashboard
    ("上次更新", "Last updated"),
    ("需要关注", "Needs attention"),
    ("运行中对话", "Running conversations"),
    ("漏洞总数", "Total vulnerabilities"),
    ("严重", "Critical"),
    ("暂无新增风险", "No new risks"),
    ("工具调用次数", "Tool calls"),
    ("工具执行成功率", "Tool success rate"),
    ("Token 用量", "Token usage"),
    ("严重程度分布", "Severity distribution"),
    ("风险等级", "Risk level"),
    ("加权风险分", "Weighted risk score"),
    ("待处理紧急项", "Pending urgent items"),
    ("最近发现", "Latest finding"),
    ("严重 (Critical)", "Critical"),
    ("高 (High)", "High"),
    ("中 (Medium)", "Medium"),
    ("低 (Low)", "Low"),
    ("信息 (Info)", "Info"),
    ("处置状态", "Disposition"),
    ("修复进度", "Fix progress"),
    ("已修复", "Fixed"),
    ("处理中", "In progress"),
    ("已忽略", "Ignored"),
    ("待处理", "Pending"),
    ("最近漏洞", "Recent vulnerabilities"),
    ("近期事实", "Recent facts"),
    ("C2 监听器", "C2 Listeners"),
    ("活跃会话", "Active sessions"),
    ("已执行任务", "Executed tasks"),
    ("WebShell 连接", "WebShell connections"),
    ("推荐操作", "Recommended actions"),
    ("推荐操作提示", "Recommended actions hint"),
    ("批量任务队列", "Batch task queues"),
    ("查看全部", "View all"),
    ("执行中", "Running"),
    ("已完成", "Completed"),
    ("工具执行次数", "Tool executions"),
    ("最近事件", "Recent events"),
    ("能力总览", "Capabilities overview"),
    ("MCP 工具", "MCP tools"),
    ("外部 MCP", "External MCP"),
    ("运行中", "Running"),
    ("存在异常", "Has errors"),
    ("知识库", "Knowledge bases"),
    ("角色", "Roles"),  # duplicate OK
    ("开始你的安全之旅", "Start your security journey"),
    ("在对话中描述目标，AI 将协助执行扫描与漏洞分析。", "Describe your target in the chat, and AI will help with scanning and vulnerability analysis."),
    ("前往对话", "Go to Chat"),
    # Chat
    ("新任务", "New task"),
    ("搜索项目", "Search projects"),
    ("清除搜索", "Clear search"),
    ("项目文件夹", "Project folders"),
    ("全部项目", "All projects"),
    ("未绑定项目", "Unbound projects"),
    ("最近对话", "Recent conversations"),
    ("排序", "Sort"),
    ("按时间排序", "Sort by time"),
    ("按名称排序", "Sort by name"),
    ("批量管理", "Batch manage"),
    ("会话设置", "Session settings"),
    ("人机协同设置只影响后续新轮次，不修改历史消息。", "Human-in-the-loop settings only affect subsequent new turns, not historical messages."),
    ("人机协同", "Human-in-the-loop"),
    ("审批模式", "Approval mode"),
    ("关闭", "Off"),
    ("审批模式", "Approval mode"),
    ("审核编辑模式", "Review & edit mode"),
    ("审核人", "Reviewer"),
    ("人工审批", "Human approval"),
    ("审计 Agent", "Audit agent"),
    ("可在人工与审计 Agent 之间切换，不影响历史操作记录。", "You can switch between human and audit agent without affecting the historical operation log."),
    ("超时时间", "Timeout"),
    ("1 分钟", "1 minute"),
    ("5 分钟", "5 minutes"),
    ("10 分钟", "10 minutes"),
    ("不限制", "Unlimited"),
    ("到期未处理将自动跳过该工具调用。", "Unhandled requests will be automatically skipped when they expire."),
    ("敏感工具白名单", "Sensitive tool whitelist"),
    ("每行一个工具名，白名单内的工具将自动通过审批，不受人机协同拦截。", "One tool name per line. Tools in the whitelist will be automatically approved and bypass human-in-the-loop."),
    ("攻击链", "Attack chain"),
    ("查看攻击链", "View attack chain"),
    ("对话轮次导航", "Conversation turn navigation"),
    ("回到最新消息", "Back to latest message"),
    ("当前会话上下文", "Current session context"),
    ("无项目", "No project"),
    ("选择项目", "Select project"),
    ("新建项目", "New project"),
    ("搜索项目名称", "Search project name"),
    ("选择角色", "Select role"),
    ("默认角色", "Default role"),
    # Common
    ("刷新", "Refresh"),
    ("保存", "Save"),
    ("取消", "Cancel"),
    ("确认", "Confirm"),
    ("删除", "Delete"),
    ("编辑", "Edit"),
    ("添加", "Add"),
    ("搜索", "Search"),
    ("加载中", "Loading"),
    ("加载更多", "Load more"),
    ("操作", "Actions"),
    ("状态", "Status"),
    ("类型", "Type"),
    ("名称", "Name"),
    ("描述", "Description"),
    ("时间", "Time"),
    ("创建时间", "Created at"),
    ("更新时间", "Updated at"),
    ("暂无数据", "No data"),
    ("无数据", "No data"),
    ("已启用", "Enabled"),
    ("已禁用", "Disabled"),
    ("启用", "Enable"),
    ("禁用", "Disable"),
    ("上传", "Upload"),
    ("下载", "Download"),
    ("导出", "Export"),
    ("导入", "Import"),
    ("复制", "Copy"),
    ("粘贴", "Paste"),
    ("重置", "Reset"),
    ("提交", "Submit"),
    ("关闭", "Close"),
    ("打开", "Open"),
    ("查看", "View"),
    ("详情", "Details"),
    ("更多", "More"),
    ("返回", "Back"),
    ("下一步", "Next"),
    ("上一步", "Previous"),
    ("完成", "Done"),
    ("成功", "Success"),
    ("失败", "Failed"),
    ("错误", "Error"),
    ("警告", "Warning"),
    ("信息", "Info"),
    ("确认删除", "Confirm delete"),
    ("确认操作", "Confirm action"),
    # Notifications
    ("通知", "Notifications"),
    ("标记已读", "Mark as read"),
    # Sessions
    ("会话设置标题", "Session settings"),
    # Misc inline labels
    ("过滤所有 API", "Filter all APIs"),
]

with open("web/templates/index.html", "r", encoding="utf-8") as f:
    content = f.read()

for item in REPLACEMENTS:
    if len(item) == 2:
        zh, en = item
        content = content.replace(zh, en)
    else:
        # future: handle restricted replacements
        zh, en = item[0], item[1]
        content = content.replace(zh, en)

remaining = re.findall(r'[\u4e00-\u9fff]', content)
print(f"Remaining Chinese chars: {len(remaining)}")
if remaining:
    for i, line in enumerate(content.splitlines(), 1):
        if re.search(r'[\u4e00-\u9fff]', line):
            print(f"  L{i}: {line.strip()[:120]}")

with open("web/templates/index.html", "w", encoding="utf-8") as f:
    f.write(content)
print("Saved index.html")
