#!/usr/bin/env python3
"""
Proper JS translation - handles comments, i18n fallbacks, and string literals.
Does NOT replace individual Chinese characters mid-word.
"""
import re, os, json

# ── Load en-US.json ──────────────────────────────────────────────────────────
with open("web/static/i18n/en-US.json", "r", encoding="utf-8-sig") as f:
    en_i18n = json.load(f)

def get_en(key):
    parts = key.split(".")
    d = en_i18n
    for p in parts:
        if isinstance(d, dict) and p in d:
            d = d[p]
        else:
            return None
    return d if isinstance(d, str) else None

# Flatten i18n for reverse lookup (Chinese -> English)
def flatten_i18n(d, prefix=""):
    result = {}
    for k, v in d.items():
        full_key = f"{prefix}.{k}" if prefix else k
        if isinstance(v, dict):
            result.update(flatten_i18n(v, full_key))
        elif isinstance(v, str):
            if re.search(r"[\u4e00-\u9fff]", v):
                if v not in result:
                    result[v] = full_key
    return result

ZH_TO_KEY = flatten_i18n(en_i18n)

def zh_to_en(zh_text):
    """Look up Chinese text: first try i18n reverse lookup, then known translations."""
    if zh_text in ZH_TO_KEY:
        key = ZH_TO_KEY[zh_text]
        en = get_en(key)
        if en and not re.search(r"[\u4e00-\u9fff]", en):
            return en
    return KNOWN_TRANSLATIONS.get(zh_text)

# ── Known translations for strings NOT in i18n ───────────────────────────────
KNOWN_TRANSLATIONS = {
    # chat.js specific
    "请根据上传的文件内容进行分析。": "Please analyze the uploaded file content.",
    "【用户补充 / 中断后继续】": "[User note / continue after interrupt]",
    "审批方已保存。": "Reviewer saved.",
    "同步到服务器失败": "Failed to sync to server",
    "人机协同配置已保存并同步到服务器。": "HITL configuration saved and synced to server.",
    "人机协同默认配置已写入 config.yaml 并生效。": "HITL default configuration written to config.yaml and active.",
    "免审批工具已合并进 config.yaml 并生效。会话配置会自动保存。": "Approval-exempt tools merged into config.yaml and active. Session config will be saved automatically.",
    "已保存到本浏览器。": "Saved to local browser.",
    "Eino 单代理": "Eino single-agent",
    "跟随默认通道": "Follow default channel",
    "默认通道": "Default channel",
    "OpenAI 协议模型": "OpenAI protocol model",
    "不指定": "Not specified",
    "当前": "Current",
    "会话推理设置已更新": "Session reasoning settings updated",
    "重新获取": "Retry",
    "正在获取模型列表…": "Fetching model list…",
    "AI 通道": "AI channel",
    "推理模式": "Reasoning mode",
    "推理强度": "Reasoning effort",
    "模型": "Model",
    "默认": "Default",
    "单代理": "Single agent",
    "多代理": "Multi-agent",
    "规划执行": "Plan-execute",
    "监督者": "Supervisor",
    "深度代理": "Deep agent",
    "新对话": "New conversation",
    "新任务": "New task",
    "无标题": "Untitled",
    "未命名": "Untitled",
    "默认角色": "Default role",
    "无角色": "No role",
    "无项目": "No project",
    "选择项目": "Select project",
    "选择角色": "Select role",
    "角色": "Role",
    "项目": "Project",
    "对话": "Conversation",
    "任务": "Task",
    "攻击链": "Attack chain",
    "攻击链可视化": "Attack chain visualisation",
    "发送": "Send",
    "停止": "Stop",
    "上传文件": "Upload file",
    "打开会话设置": "Open session settings",
    "折叠/展开对话列表": "Collapse/expand conversation list",
    "展开/折叠最近对话": "Expand/collapse recent conversations",
    "新建项目": "New project",
    "会话设置": "Session settings",
    "人机协同": "Human-AI collaboration",
    "模式": "Mode",
    "审批模式": "Approval mode",
    "审查编辑": "Review & edit",
    "关闭": "Off",
    "审批方": "Reviewer",
    "人工审批": "Manual approval",
    "审计 Agent": "Audit Agent",
    "审批等待时限": "Approval timeout",
    "1 分钟": "1 minute",
    "5 分钟": "5 minutes",
    "10 分钟": "10 minutes",
    "不限制": "Unlimited",
    "白名单工具（免审批，逗号分隔）": "Whitelist tools (approval-exempt, comma-separated)",
    "人机协同设置只影响后续消息。": "HITL settings only affect subsequent messages.",
    "选择对话执行模式": "Select conversation execution mode",
    "对话模式": "Conversation mode",
    "已选择 0 项": "0 selected",
    "绑定项目后共享事实黑板（跨对话）": "Bind project to share fact board (across conversations)",
    # monitor.js specific
    "规划器": "Planner",
    "执行器": "Executor",
    "重规划": "Replan",
    "助手输出": "Assistant output",
    "规划中": "Planning",
    "最终回复检查通过": "Final reply check passed",
    "最终回复检查未通过": "Final reply check failed",
    "等待工具执行完成": "Waiting for tool execution to complete",
    "缺少完成态证据": "Missing completion evidence",
    "等待人工确认": "Waiting for manual confirmation",
    "未捕获到有效回复": "No valid reply captured",
    "缺少最终化证明": "Missing finalisation evidence",
    "仍在验证": "Still verifying",
    "检查未通过": "Check failed",
    "已验证": "Verified",
    "仍有工具执行未结束": "Tool execution still in progress",
    "未捕获到助手文本输出": "No assistant text output captured",
    "未捕获到有效最终文本": "No valid final text captured",
    # common JS UI strings
    "确定要删除吗？": "Are you sure you want to delete?",
    "确定要删除这条记录吗？": "Are you sure you want to delete this record?",
    "确定要删除选中的记录吗？": "Are you sure you want to delete the selected records?",
    "确定要清空所有日志吗？": "Are you sure you want to clear all logs?",
    "确定要清空所有记录吗？": "Are you sure you want to clear all records?",
    "确定要清空所有审计日志吗？": "Are you sure you want to clear all audit logs?",
    "此操作不可撤销": "This action cannot be undone",
    "操作不可逆": "This action is irreversible",
    "暂无数据": "No data",
    "暂无记录": "No records",
    "暂无结果": "No results",
    "正在加载...": "Loading...",
    "正在加载…": "Loading…",
    "加载中...": "Loading...",
    "加载中…": "Loading…",
    "加载失败": "Load failed",
    "加载中": "Loading",
    "加载更多": "Load more",
    "保存成功": "Saved successfully",
    "保存失败": "Save failed",
    "删除成功": "Deleted successfully",
    "删除失败": "Delete failed",
    "操作成功": "Operation successful",
    "操作失败": "Operation failed",
    "请求失败": "Request failed",
    "请求超时": "Request timed out",
    "网络错误": "Network error",
    "服务器错误": "Server error",
    "未知错误": "Unknown error",
    "复制成功": "Copied successfully",
    "复制失败": "Copy failed",
    "已复制": "Copied",
    "导入成功": "Import successful",
    "导入失败": "Import failed",
    "导出成功": "Export successful",
    "导出失败": "Export failed",
    "创建成功": "Created successfully",
    "创建失败": "Creation failed",
    "更新成功": "Updated successfully",
    "更新失败": "Update failed",
    "添加成功": "Added successfully",
    "添加失败": "Add failed",
    "连接成功": "Connected successfully",
    "连接失败": "Connection failed",
    "获取数据失败": "Failed to fetch data",
    "获取列表失败": "Failed to fetch list",
    "获取失败": "Fetch failed",
    "索引构建成功": "Index built successfully",
    "索引构建失败": "Index build failed",
    "索引重建中": "Rebuilding index",
    "构建成功": "Build successful",
    "构建失败": "Build failed",
    "构建中": "Building",
    "同步成功": "Sync successful",
    "同步失败": "Sync failed",
    "重置成功": "Reset successful",
    "重置失败": "Reset failed",
    "清空成功": "Cleared successfully",
    "清空失败": "Clear failed",
    "上传成功": "Upload successful",
    "上传失败": "Upload failed",
    "下载失败": "Download failed",
    "绑定成功": "Bound successfully",
    "绑定失败": "Binding failed",
    "解绑成功": "Unbound successfully",
    "解绑失败": "Unbinding failed",
    "生成成功": "Generated successfully",
    "生成失败": "Generation failed",
    "连接测试成功": "Connection test successful",
    "连接测试失败": "Connection test failed",
    "配置已保存": "Configuration saved",
    "配置保存失败": "Configuration save failed",
    "配置已应用": "Configuration applied",
    "确认删除": "Confirm deletion",
    "确定": "OK",
    "取消": "Cancel",
    "确认": "Confirm",
    "关闭": "Close",
    "保存": "Save",
    "编辑": "Edit",
    "删除": "Delete",
    "新增": "Add",
    "搜索": "Search",
    "刷新": "Refresh",
    "复制": "Copy",
    "重置": "Reset",
    "清空": "Clear",
    "测试": "Test",
    "预览": "Preview",
    "详情": "Details",
    "查看": "View",
    "返回": "Back",
    "提交": "Submit",
    "下载": "Download",
    "上传": "Upload",
    "导入": "Import",
    "导出": "Export",
    "生成": "Generate",
    "运行": "Run",
    "执行": "Execute",
    "停止": "Stop",
    "暂停": "Pause",
    "恢复": "Resume",
    "完成": "Complete",
    "跳过": "Skip",
    "忽略": "Ignore",
    "通过": "Approve",
    "拒绝": "Reject",
    "拦截": "Block",
    "启用": "Enable",
    "禁用": "Disable",
    "激活": "Activate",
    "全选": "Select all",
    "取消全选": "Deselect all",
    "已选中": "Selected",
    "未选中": "Not selected",
    "全部": "All",
    "更多": "More",
    "展开": "Expand",
    "折叠": "Collapse",
    "筛选": "Filter",
    "排序": "Sort",
    "分组": "Group",
    "缩放": "Zoom",
    "放大": "Zoom in",
    "缩小": "Zoom out",
    "重置缩放": "Reset zoom",
    "适应屏幕": "Fit to screen",
    "全屏": "Fullscreen",
    "退出全屏": "Exit fullscreen",
    # status strings
    "运行中": "Running",
    "已停止": "Stopped",
    "已暂停": "Paused",
    "已完成": "Completed",
    "已取消": "Cancelled",
    "已失败": "Failed",
    "已超时": "Timed out",
    "等待中": "Waiting",
    "排队中": "Queued",
    "执行中": "Executing",
    "已拦截": "Blocked",
    "已终止": "Terminated",
    "已拒绝": "Rejected",
    "已通过": "Approved",
    "已忽略": "Ignored",
    "待处理": "Open",
    "待审批": "Pending approval",
    "待审计": "Pending review",
    "审批中": "Under review",
    "已审批": "Reviewed",
    "已修复": "Fixed",
    "已确认": "Confirmed",
    "误报": "False positive",
    "待确认": "Tentative",
    "在线": "Online",
    "离线": "Offline",
    "活跃": "Active",
    "停用": "Inactive",
    "连接中": "Connecting",
    "已断开": "Disconnected",
    "正在连接": "Connecting",
    "严重": "Critical",
    "高危": "High",
    "中危": "Medium",
    "低危": "Low",
    "未知": "Unknown",
    "未设置": "Not set",
    "未绑定": "Unbound",
    "已绑定": "Bound",
    "未绑定项目": "Unbound",
    "安全": "Safe",
    # form validation
    "必填项": "Required",
    "不能为空": "Cannot be empty",
    "格式错误": "Invalid format",
    "参数错误": "Parameter error",
    "请选择": "Please select",
    "请输入": "Please enter",
    "请输入名称": "Please enter a name",
    "请输入描述": "Please enter a description",
    "请输入URL": "Please enter a URL",
    "请输入IP地址": "Please enter an IP address",
    "请输入端口": "Please enter a port",
    "请输入用户名": "Please enter a username",
    "请输入密码": "Please enter a password",
    "请输入API Key": "Please enter an API Key",
    "请输入关键词": "Please enter a keyword",
    "请输入工具名称": "Please enter a tool name",
    "请输入参数": "Please enter parameters",
    "请输入正则表达式": "Please enter a regular expression",
    "正则表达式无效": "Invalid regular expression",
    "字段不能为空": "Field cannot be empty",
    "名称不能为空": "Name cannot be empty",
    "密码不能为空": "Password cannot be empty",
    "用户名不能为空": "Username cannot be empty",
    "已经存在": "Already exists",
    "密码不匹配": "Passwords do not match",
    # pagination
    "上一页": "Previous",
    "下一页": "Next",
    "第一页": "First page",
    "最后一页": "Last page",
    "没有更多数据": "No more data",
    "到底了": "End of list",
    "正在加载更多": "Loading more",
    # notifications/events
    "暂无新事件": "No new events",
    "事件通知": "Event notifications",
    "查看全部": "View all",
    "标记已读": "Mark as read",
    "标记全部已读": "Mark all as read",
    "清空通知": "Clear notifications",
    "未读消息": "Unread messages",
    # permissions
    "权限不足": "Insufficient permissions",
    "没有权限": "No permission",
    "请先登录": "Please log in first",
    "会话已过期": "Session expired",
    "Token已过期": "Token expired",
    "登录成功": "Logged in successfully",
    "登录失败": "Login failed",
    "注销成功": "Logged out successfully",
    "验证失败": "Verification failed",
    "用户名或密码错误": "Incorrect username or password",
    "密码强度": "Password strength",
    "强": "Strong",
    "弱": "Weak",
    "中等": "Medium",
    # specific strings from various files
    "调用OpenAI失败": "OpenAI call failed",
    "获取对话列表失败": "Failed to fetch conversation list",
    "获取消息失败": "Failed to fetch messages",
    "消息发送失败": "Message send failed",
    "文件上传成功": "File uploaded successfully",
    "文件上传失败": "File upload failed",
    "文件格式不支持": "File format not supported",
    "文件大小超出限制": "File size exceeds limit",
    "请选择文件": "Please select a file",
    "尚未选择文件": "No file selected",
    "选择文件，或拖拽到此处": "Choose a file or drag and drop here",
    "拖拽到此处": "Drag and drop here",
    "上传中": "Uploading",
    "解析中": "Parsing",
    "预览": "Preview",
    "数据预览": "Data preview",
    "下载模板": "Download template",
    "下载 XLSX 模板": "Download XLSX template",
    "下载 CSV 模板": "Download CSV template",
    "导入资产": "Import assets",
    "批量导入": "Bulk import",
    "批量导入资产": "Bulk import assets",
    "批量编辑资产": "Bulk edit assets",
    "批量导入成功": "Bulk import successful",
    "批量导入失败": "Bulk import failed",
    "绑定项目": "Bind project",
    "解除项目绑定": "Unbind project",
    "创建扫描任务": "Create scan task",
    "发送到对话": "Send to chat",
    "发送到Chat": "Send to chat",
    "导出 CSV": "Export CSV",
    "导出 XLSX": "Export XLSX",
    "导出CSV": "Export CSV",
    "导出XLSX": "Export XLSX",
    "合并资产": "Merge assets",
    "删除资产": "Delete assets",
    "清除选择": "Clear selection",
    "批量操作": "Batch actions",
    "更多操作": "More actions",
    "保存当前视图": "Save current view",
    "删除视图": "Delete view",
    "保存的筛选视图": "Saved filter views",
    "应用修改": "Apply changes",
    "重置筛选": "Reset filters",
    "高级筛选": "Advanced filters",
    "风险等级": "Risk level",
    "资产类型": "Asset type",
    "资产概览": "Asset overview",
    "资产库": "Asset library",
    "端口数量": "Port count",
    "域名数量": "Domain count",
    "IP 数量": "IP count",
    "协议分布": "Protocol distribution",
    "资产占比": "Asset ratio",
    "协议名": "Protocol",
    "扫描覆盖": "Scan coverage",
    "已扫描资产": "Scanned assets",
    "近 30 天覆盖": "30-day coverage",
    "从未扫描": "Never scanned",
    "超过 30 天未扫描": "Not scanned in 30+ days",
    "总体覆盖率": "Overall coverage",
    "资产增减趋势": "Asset growth trend",
    "风险发现趋势": "Risk discovery trend",
    "态势变化": "Posture changes",
    "近 7 天发现": "Found in last 7 days",
    "资产总数": "Total assets",
    "当前纳入持续监测的资产": "Assets under continuous monitoring",
    "7 天": "7 days",
    "30 天": "30 days",
    "90 天": "90 days",
    "近7天": "Last 7 days",
    "近30天": "Last 30 days",
    "近90天": "Last 90 days",
    # Vulnerability
    "漏洞": "Vulnerability",
    "漏洞管理": "Vulnerability management",
    "漏洞详情": "Vulnerability details",
    "漏洞描述": "Vulnerability description",
    "漏洞类型": "Vulnerability type",
    "漏洞状态": "Vulnerability status",
    "漏洞名称": "Vulnerability name",
    "漏洞等级": "Vulnerability severity",
    "漏洞数量": "Vulnerability count",
    "待处理漏洞": "Open vulnerabilities",
    "最近漏洞": "Recent vulnerabilities",
    "近期漏洞": "Recent vulnerabilities",
    "漏洞总数": "Total vulnerabilities",
    "所有漏洞": "All vulnerabilities",
    "添加漏洞": "Add vulnerability",
    "编辑漏洞": "Edit vulnerability",
    "删除漏洞": "Delete vulnerability",
    "漏洞修复": "Fix vulnerability",
    "标记为修复": "Mark as fixed",
    "标记为误报": "Mark as false positive",
    "修复建议": "Remediation advice",
    "影响范围": "Impact scope",
    "POC": "PoC",
    "漏洞验证": "Vulnerability verification",
    "漏洞利用": "Vulnerability exploitation",
    "CVSS评分": "CVSS score",
    "CVE编号": "CVE ID",
    # Tasks
    "批量任务队列": "Batch task queue",
    "批量任务": "Batch task",
    "任务管理": "Task management",
    "任务详情": "Task details",
    "任务名称": "Task name",
    "任务状态": "Task status",
    "任务进度": "Task progress",
    "任务类型": "Task type",
    "任务描述": "Task description",
    "创建任务": "Create task",
    "添加任务": "Add task",
    "删除任务": "Delete task",
    "停止任务": "Stop task",
    "重试任务": "Retry task",
    "待执行": "Pending",
    "执行中": "Executing",
    "执行失败": "Execution failed",
    "执行成功": "Execution successful",
    "执行超时": "Execution timeout",
    "执行记录": "Execution records",
    "执行详情": "Execution details",
    "执行结果": "Execution result",
    "执行状态": "Execution status",
    "孤儿任务": "Orphaned task",
    "工具调用次数": "Tool call count",
    "工具执行成功率": "Tool success rate",
    "Token 用量": "Token usage",
    "Token用量": "Token usage",
    "运行中对话": "Running conversations",
    "运行平稳": "Healthy",
    "运行中监听器": "Running listeners",
    "活跃连接": "Active connections",
    "在线会话": "Online sessions",
    "待审 / 排队任务": "Pending / queued tasks",
    # MCP / Tools
    "工具": "Tool",
    "工具名称": "Tool name",
    "工具参数": "Tool parameters",
    "工具描述": "Tool description",
    "工具配置": "Tool configuration",
    "工具管理": "Tool management",
    "工具调用": "Tool call",
    "工具执行": "Tool execution",
    "工具搜索": "Search tools",
    "工具状态监控": "Tool status monitor",
    "工具拦截": "Tool blocking",
    "拦截规则": "Block rules",
    "拦截策略": "Block policy",
    "拦截提醒": "Block message",
    "调用拦截": "Call interception",
    "试运行": "Dry run",
    "试运行结果": "Dry run result",
    "试运行通过": "Dry run passed",
    "全部规则验证": "Validate all rules",
    "规则验证通过": "Rule validation passed",
    "规则验证失败": "Rule validation failed",
    "没有匹配的规则": "No matching rules",
    "规则名称": "Rule name",
    "规则描述": "Rule description",
    "添加规则": "Add rule",
    "删除规则": "Delete rule",
    "编辑规则": "Edit rule",
    "规则列表": "Rule list",
    "启用规则": "Enable rule",
    "禁用规则": "Disable rule",
    "已启用": "Enabled",
    "已停用": "Disabled",
    "已禁用": "Disabled",
    "全部规则": "All rules",
    "已启用的工具": "Enabled tools",
    "已停用的工具": "Disabled tools",
    "全部工具": "All tools",
    "外部 MCP": "External MCP",
    "外部MCP": "External MCP",
    "添加外部MCP": "Add external MCP",
    "删除外部MCP": "Delete external MCP",
    "MCP服务器": "MCP server",
    "MCP状态监控": "MCP status monitor",
    "MCP管理": "MCP management",
    "最新执行记录": "Latest execution records",
    "内置工具": "Built-in tools",
    "执行孤儿任务": "Orphaned task",
    "已完成": "Completed",
    "排队中": "Queued",
    "执行中": "Running",
    "已拦截": "Blocked",
    "执行超时": "Timed out",
    "已终止": "Cancelled",
    "孤儿任务": "Orphaned",
    # Knowledge
    "知识库": "Knowledge base",
    "知识管理": "Knowledge management",
    "知识检索": "Knowledge retrieval",
    "知识项": "Knowledge item",
    "检索历史": "Retrieval history",
    "知识详情": "Knowledge details",
    "构建索引": "Build index",
    "重建索引": "Rebuild index",
    "全量重建": "Full rebuild",
    "增量构建": "Incremental build",
    "分类": "Category",
    "分类筛选": "Category filter",
    "总知识项": "Total knowledge items",
    "分类数": "Category count",
    "总内容": "Total content",
    "检索次数": "Retrieval count",
    "成功检索": "Successful retrievals",
    "总检索次数": "Total retrievals",
    "检索成功率": "Retrieval success rate",
    "检索到知识项": "Retrieved knowledge items",
    "对话ID": "Conversation ID",
    "消息ID": "Message ID",
    "检索日志": "Retrieval log",
    # Roles / Skills / Agents
    "角色管理": "Role management",
    "角色名称": "Role name",
    "角色描述": "Role description",
    "角色配置": "Role configuration",
    "创建角色": "Create role",
    "编辑角色": "Edit role",
    "删除角色": "Delete role",
    "技能管理": "Skill management",
    "技能状态": "Skill status",
    "技能描述": "Skill description",
    "技能名称": "Skill name",
    "技能配置": "Skill configuration",
    "创建技能": "Create skill",
    "编辑技能": "Edit skill",
    "删除技能": "Delete skill",
    "智能体管理": "Agent management",
    "智能体名称": "Agent name",
    "智能体描述": "Agent description",
    "创建智能体": "Create agent",
    "编辑智能体": "Edit agent",
    "删除智能体": "Delete agent",
    # RBAC
    "平台权限": "Platform permissions",
    "权限管理": "Permission management",
    "用户管理": "User management",
    "访问控制": "Access control",
    "全局权限": "Global permissions",
    "资源权限": "Resource permissions",
    "创建用户": "Create user",
    "编辑用户": "Edit user",
    "删除用户": "Delete user",
    "重置密码": "Reset password",
    "管理员": "Administrator",
    "普通用户": "Regular user",
    "平台用户": "Platform user",
    "分配资源": "Assign resource",
    "撤销授权": "Revoke grant",
    "权限变更历史": "Permission change history",
    "审计事件": "Audit event",
    "所有类型": "All types",
    "所有操作": "All actions",
    "所有资源类型": "All resource types",
    "全部权限类型": "All permission types",
    # Projects / Facts
    "项目管理": "Project management",
    "项目名称": "Project name",
    "项目描述": "Project description",
    "项目详情": "Project details",
    "创建项目": "Create project",
    "编辑项目": "Edit project",
    "删除项目": "Delete project",
    "选择项目": "Select project",
    "无项目": "No project",
    "事实黑板": "Fact board",
    "事实": "Fact",
    "添加事实": "Add fact",
    "编辑事实": "Edit fact",
    "删除事实": "Delete fact",
    "事实详情": "Fact details",
    "摘要": "Summary",
    "关联": "Related",
    "置信度": "Confidence",
    "待确认": "Tentative",
    "已废弃": "Deprecated",
    "攻击链模板": "Attack chain template",
    "环境模板": "Environment template",
    "分类（风险类型）": "Category (risk type)",
    "索引一行": "one-line index",
    "可复现详情": "reproducible details",
    "插入攻击链模板": "Insert attack chain template",
    "插入环境模板": "Insert environment template",
    # Workflows
    "工作流": "Workflow",
    "工作流管理": "Workflow management",
    "工作流详情": "Workflow details",
    "工作流名称": "Workflow name",
    "工作流描述": "Workflow description",
    "创建工作流": "Create workflow",
    "编辑工作流": "Edit workflow",
    "删除工作流": "Delete workflow",
    "步骤": "Step",
    "节点": "Node",
    "连接": "Connection",
    "添加节点": "Add node",
    "删除节点": "Delete node",
    "添加连接": "Add connection",
    "删除连接": "Delete connection",
    "工作流包": "Workflow package",
    "工作流变量": "Workflow variables",
    "工作流配置": "Workflow configuration",
    "安装工作流": "Install workflow",
    "移除工作流": "Remove workflow",
    "工作流包管理": "Workflow package management",
    "已安装": "Installed",
    "未安装": "Not installed",
    "安装成功": "Installed successfully",
    "安装失败": "Installation failed",
    "移除成功": "Removed successfully",
    "移除失败": "Remove failed",
    "移除文件": "Remove file",
    # C2
    "C2管理": "C2 management",
    "监听器管理": "Listener management",
    "会话管理": "Session management",
    "添加监听器": "Add listener",
    "删除监听器": "Delete listener",
    "停止监听器": "Stop listener",
    "启动监听器": "Start listener",
    "监听器状态": "Listener status",
    "监听类型": "Listen type",
    "监听地址": "Listen address",
    "监听端口": "Listen port",
    "创建会话": "Create session",
    "关闭会话": "Close session",
    "活跃会话": "Active sessions",
    "在线会话": "Online sessions",
    "离线会话": "Offline sessions",
    "上线时间": "Online since",
    "最后活跃": "Last active",
    "心跳": "Heartbeat",
    "进程名": "Process name",
    "进程ID": "Process ID",
    "进程列表": "Process list",
    "主机名": "Hostname",
    "操作系统": "Operating system",
    "架构": "Architecture",
    "用户权限": "User privileges",
    "当前用户": "Current user",
    "系统信息": "System info",
    "生成载荷": "Generate payload",
    "载荷类型": "Payload type",
    "载荷配置": "Payload configuration",
    "流量伪装": "Traffic profile",
    "C2事件": "C2 events",
    "C2任务": "C2 tasks",
    "命令输出": "Command output",
    # WebShell
    "WebShell": "WebShell",
    "WebShell管理": "WebShell management",
    "WebShell连接": "WebShell connection",
    "添加WebShell": "Add WebShell",
    "删除WebShell": "Delete WebShell",
    "连接WebShell": "Connect WebShell",
    "断开WebShell": "Disconnect WebShell",
    "WebShell地址": "WebShell URL",
    "连接名称": "Connection name",
    "连接类型": "Connection type",
    "连接参数": "Connection parameters",
    "密码/密钥": "Password/Key",
    "命令执行": "Command execution",
    "文件管理": "File management",
    "拖拽调整宽度": "Drag to resize",
    "终端": "Terminal",
    "终端 1": "Terminal 1",
    # Settings
    "系统设置": "System Settings",
    "基本设置": "Basic settings",
    "高级设置": "Advanced settings",
    "安全设置": "Security settings",
    "网络设置": "Network settings",
    "代理设置": "Proxy settings",
    "通知设置": "Notification settings",
    "通道配置": "Channel configuration",
    "AI通道配置": "AI channel configuration",
    "模型配置": "Model configuration",
    "视觉分析": "Vision analysis",
    "Agent配置": "Agent configuration",
    "FOFA配置": "FOFA configuration",
    "ZoomEye配置": "ZoomEye configuration",
    "Quake配置": "Quake configuration",
    "Shodan配置": "Shodan configuration",
    "机器人设置": "Bot settings",
    "机器人配置": "Bot configuration",
    "存储清理": "Storage cleanup",
    "日志审计": "Audit log",
    "安全配置": "Security configuration",
    "应用配置": "Apply configuration",
    "保存配置": "Save configuration",
    "恢复默认": "Restore defaults",
    "重置配置": "Reset configuration",
    "测试连接": "Test connection",
    "测试API": "Test API",
    "当前配置": "Current configuration",
    "系统提示词": "System prompt",
    "推理模式": "Reasoning mode",
    "推理强度": "Reasoning effort",
    "温度": "Temperature",
    "最大Token数": "Max tokens",
    "上下文长度": "Context length",
    "超时时间": "Timeout",
    "重试次数": "Retry count",
    "并发数": "Concurrency",
    "代理地址": "Proxy address",
    "API地址": "API base URL",
    "API Key": "API Key",
    "留空则使用默认地址。": "Leave blank to use the default address.",
    "仅保存在服务器配置中（config.yaml）。": "Stored only in server configuration (config.yaml).",
    # Bot specific
    "鉴权模式": "Auth mode",
    "逐用户绑定（多人机器人推荐）": "Per-user binding (recommended for multi-user bots)",
    "专用服务账号（仅白名单发送者）": "Dedicated service account (whitelist senders only)",
    "服务账号 RBAC User ID": "Service Account RBAC User ID",
    "允许的平台发送者 ID": "Allowed platform sender IDs",
    "绑定码": "Binding code",
    "生成绑定码": "Generate binding code",
    "一次性绑定码": "One-time binding code",
    "已绑定平台账号": "Bound platform accounts",
    "绑定机器人账号": "Bind bot account",
    "解绑机器人账号": "Unbind bot account",
    "生成中": "Generating",
    "等待生成": "Waiting for generation",
    "一次性安全码": "One-time security code",
    "复制命令": "Copy command",
    "请在机器人中发送绑定命令": "Please send the binding command in the bot",
    "绑定码仅保存哈希、只能使用一次，新码会使旧码立即失效": "Binding code is stored as a hash, can only be used once; a new code immediately invalidates the old one",
    "正在加载绑定信息…": "Loading binding information…",
    "\u5982\u9700\u914d\u7f6e\u4e13\u7528\u670d\u52a1\u8d26\u53f7\uff0c\u8bf7\u524d\u5f80\u201c\u7cfb\u7edf\u8bbe\u7f6e \u2192 \u673a\u5668\u4eba\u8bbe\u7f6e\u201d\u3002": 'To configure a dedicated service account, go to "System Settings \u2192 Bot Settings".',
    # i18n.js
    "中文": "Chinese",
    "English": "English",
    "Русский": "Russian",
    # misc
    "解析失败": "Parse failed",
    "解析错误": "Parse error",
    "数据格式错误": "Invalid data format",
    "JSON格式错误": "Invalid JSON format",
    "JSON解析失败": "JSON parse failed",
    "无法解析": "Cannot parse",
    "文件解析失败": "File parse failed",
    "内容解析失败": "Content parse failed",
    "配置解析失败": "Configuration parse failed",
    "响应解析失败": "Response parse failed",
    "XML解析失败": "XML parse failed",
    "当前用户": "Current user",
    "当前角色": "Current role",
    "当前项目": "Current project",
    "当前对话": "Current conversation",
    "当前任务": "Current task",
    "当前状态": "Current status",
    "最近更新": "Last updated",
    "上次更新": "Last updated",
    "最后修改": "Last modified",
    "创建时间": "Created",
    "更新时间": "Updated",
    "修改时间": "Modified",
    "完成时间": "Completed",
    "开始时间": "Start time",
    "结束时间": "End time",
    "发现时间": "Discovery time",
    "最近发现": "Latest found",
    "首次发现": "First discovered",
    "首次发现开始": "First discovered start",
    "首次发现结束": "First discovered end",
    "最近发现开始": "Latest found start",
    "最近发现结束": "Latest found end",
    "来源": "Source",
    "目标": "Target",
    "路径": "Path",
    "大小": "Size",
    "标签": "Tags",
    "备注": "Note",
    "优先级": "Priority",
    "关联漏洞": "Related vulnerabilities",
    "关联资产": "Related assets",
    "关联任务": "Related tasks",
    "关联对话": "Related conversations",
    "负责人": "Owner",
    "部门": "Department",
    "业务系统": "Business system",
    "环境": "Environment",
    "重要性": "Criticality",
    "省份/州": "Province/State",
    "城市": "City",
    "国家/地区": "Country/Region",
    "生产": "Production",
    "预发布": "Staging",
    "测试": "Testing",
    "开发": "Development",
    "核心": "Critical",
    "重要": "Important",
    "一般": "Normal",
    "低": "Low",
    "扫描状态": "Scan status",
    "全部扫描状态": "All scan states",
    "全部风险": "All risks",
    "全部状态": "All statuses",
    "全部项目": "All projects",
    "全部环境": "All environments",
    "全部重要性": "All criticalities",
    "排序": "Sort",
    "按最近发现排序": "Sort by latest found",
    "按首次发现排序": "Sort by first discovered",
    "按更新时间排序": "Sort by updated",
    "按风险等级排序": "Sort by risk level",
    "按漏洞数量排序": "Sort by vulnerability count",
    "保存的筛选视图": "Saved filter views",
    "高级筛选": "Advanced filters",
    "重置筛选": "Reset filters",
    "更多操作": "More actions",
    "创建扫描任务": "Create scan task",
    "发送到Chat": "Send to chat",
    "导出CSV": "Export CSV",
    "导出XLSX": "Export XLSX",
    "合并资产": "Merge assets",
    "清除选择": "Clear selection",
    "选择全部结果": "Select all results",
    "应用修改": "Apply changes",
    "下载XLSX模板": "Download XLSX template",
    "下载CSV模板": "Download CSV template",
    "行号": "Row",
    "目标地址": "Target",
    "所属项目": "Project",
    "校验状态": "Validation status",
    "导入预览": "Import preview",
    "行号合法": "Valid",
    "行号非法": "Invalid",
    "正在预览": "Previewing",
    "数据预览": "Data preview",
    "选择文件，或拖拽到此处": "Choose a file or drag and drop here",
    "尚未选择文件": "No file selected",
    "资产总数": "Total assets",
    "已扫描资产": "Scanned assets",
    "协议名": "Protocol",
    "资产占比": "Asset ratio",
    "协议分布": "Protocol distribution",
    "资产增减趋势": "Asset growth trend",
    "风险发现趋势": "Risk discovery trend",
    "态势变化": "Posture changes",
    "扫描覆盖": "Scan coverage",
    "近 30 天覆盖": "30-day coverage",
    "从未扫描": "Never scanned",
    "超过 30 天未扫描": "Not scanned in 30+ days",
    "总体覆盖率": "Overall coverage",
    # Info collect
    "数据源": "Data source",
    "查询方式": "Query method",
    "自然语言（可选，AI 解析为查询语法）": "Natural language (optional, AI converts to query syntax)",
    "查询语法（可编辑，可直接查询）": "Query syntax (editable, can query directly)",
    "查询示例": "Query examples",
    "字段模板": "Field templates",
    "返回配置": "Return config",
    "解析后会弹窗展示对应数据源语法（可编辑），确认无误后再填入查询框并执行查询。": "After parsing, a popup shows the corresponding data source syntax (editable). Confirm then paste into the query box and execute.",
    "选择数据源后会显示对应查询语法提示。": "Query syntax hints will appear after selecting a data source.",
    "不同数据源的单次返回上限可能不同。": "The per-query return limit may vary by data source.",
    "支持 FOFA、ZoomEye、Quake、Shodan；API Key 可在系统设置或环境变量中配置。": "Supports FOFA, ZoomEye, Quake, Shodan; API Key can be configured in System Settings or environment variables.",
    "查询": "Query",
    "字段显示/隐藏面板": "Field show/hide panel",
    "解析": "Parse",
    "解析查询": "Parse query",
    "查询结果": "Query results",
    "查询失败": "Query failed",
    "查询中": "Querying",
    "已查询": "Queried",
    "每页显示": "Per page",
    "保存字段": "Save fields",
    "字段设置": "Field settings",
    "添加到资产": "Add to assets",
    "批量添加到资产": "Add to assets",
    "保存到资产库": "Save to asset library",
    # Dashboard
    "仪表盘": "Dashboard",
    "上次更新": "Last updated",
    "刷新数据": "Refresh data",
    "需要关注": "Needs attention",
    "运行中对话": "Running conversations",
    "漏洞总数": "Total vulnerabilities",
    "工具调用次数": "Tool call count",
    "工具执行成功率": "Tool success rate",
    "Token 用量": "Token usage",
    "漏洞严重程度分布": "Vulnerability severity distribution",
    "全部状态": "All statuses",
    "待处理": "Open",
    "已确认": "Confirmed",
    "已修复": "Fixed",
    "已忽略": "Ignored",
    "误报": "False positive",
    "查看全部 →": "View all →",
    "风险等级": "Risk level",
    "加权风险分": "Weighted risk score",
    "最近发现": "Latest found",
    "暂无": "None",
    "总漏洞数": "Total vulnerabilities",
    "修复率": "Fix rate",
    "需要关注": "Needs attention",
    "暂无新增风险": "No new risks",
    "运行平稳": "Healthy",
    "推荐操作": "Recommended actions",
    "基于当前状态自动生成": "Auto-generated from current state",
    "批量任务队列": "Batch task queue",
    "待执行": "Pending",
    "已完成": "Completed",
    "工具执行次数": "Tool execution count",
    "最近事件": "Recent events",
    "查看通知": "View notifications",
    "能力总览": "Capability overview",
    "MCP 工具": "MCP tools",
    "知识": "Knowledge",
    "角色": "Roles",
    "开始你的安全之旅": "Start your security journey",
    "前往对话": "Go to Chat",
    "在对话中描述目标，AI 将协助执行扫描与漏洞分析": "Describe your target in chat and AI will assist with scanning and vulnerability analysis",
    "外部 MCP 服务器": "External MCP servers",
    "运行中": "Running",
    "异常": "Error",
    "近期事实": "Recent facts",
    "暂无最近漏洞": "No recent vulnerabilities",
    "暂无近期事实": "No recent facts",
    "进入 C2 管理": "Go to C2",
    "WebShell 活跃连接": "WebShell active connections",
    "C2 运行中监听器": "C2 running listeners",
    "C2 在线会话": "C2 online sessions",
    "C2 待审 / 排队任务": "C2 pending / queued tasks",
    # Auth
    "登录": "Sign in",
    "退出登录": "Sign out",
    "用户名": "Username",
    "密码": "Password",
    "登录成功": "Signed in",
    "登录失败": "Sign in failed",
    "注销成功": "Signed out",
    "修改密码": "Change password",
    "旧密码": "Current password",
    "新密码": "New password",
    "确认密码": "Confirm password",
    "密码修改成功": "Password changed",
    "密码修改失败": "Password change failed",
    "用户名或密码错误": "Invalid username or password",
    "密码强度": "Password strength",
    "强": "Strong",
    "弱": "Weak",
    "中等": "Medium",
    "密码不匹配": "Passwords do not match",
    "密码太短": "Password too short",
    "密码太简单": "Password too weak",
    "不包含特殊字符": "No special characters",
    "只能是字母和数字": "Letters and numbers only",
    "密码已修改成功": "Password changed successfully",
    "密码修改失败，请检查旧密码": "Password change failed, please check your current password",
    "使用平台账号登录，默认管理员为 admin。": "Sign in with your platform account. Default admin is admin.",
    "API 文档": "API Docs",
    "登录": "Sign in",
    # Sanitize markdown / theme / misc
    "这段内容包含不安全的 HTML，已被过滤": "This content contains unsafe HTML and has been filtered",
    "包含不安全内容": "Contains unsafe content",
    "已过滤不安全内容": "Unsafe content filtered",
    "跟随系统": "Follow system",
    "暗色": "Dark",
    "亮色": "Light",
    "主题": "Theme",
    "切换主题": "Switch theme",
    "深色模式": "Dark mode",
    "浅色模式": "Light mode",
    "系统主题": "System theme",
    # Storage
    "清理对话历史": "Clear conversation history",
    "清理文件缓存": "Clear file cache",
    "清理本地存储": "Clear local storage",
    "已清理": "Cleared",
    "清理失败": "Clear failed",
    "存储清理": "Storage cleanup",
    "对话历史": "Conversation history",
    "文件缓存": "File cache",
    "本地存储": "Local storage",
    "存储空间": "Storage space",
    "磁盘空间": "Disk space",
    "内存使用": "Memory usage",
    "确认清理": "Confirm clear",
    "确认清空所有对话？": "Clear all conversations?",
    "确认删除所有文件？": "Delete all files?",
    # Notifications
    "暂无新事件": "No new events",
    "事件通知": "Event notifications",
    "查看全部": "View all",
    "标记已读": "Mark as read",
    "标记全部已读": "Mark all as read",
    "全部已读": "All read",
    "未读通知": "Unread notifications",
    "新通知": "New notification",
    "通知详情": "Notification details",
    # Router
    "仪表盘": "Dashboard",
    "对话": "Chat",
    "安全防护": "Security",
    "人机协同审批": "HITL Approval",
    "调用拦截": "Call intercept",
    "安全作业": "Operations",
    "项目管理": "Projects",
    "资产管理": "Assets",
    "资产概览": "Asset overview",
    "资产库": "Asset library",
    "信息收集": "Info collection",
    "漏洞管理": "Vulnerabilities",
    "任务管理": "Tasks",
    "工作流": "Workflows",
    "WebShell管理": "WebShell",
    "C2管理": "C2",
    "C2 监听器": "C2 Listeners",
    "C2 会话": "C2 Sessions",
    "C2 任务": "C2 Tasks",
    "C2 Payload": "C2 Payload",
    "C2 事件": "C2 Events",
    "C2 流量伪装": "C2 Profiles",
    "文件管理": "Files",
    "能力中心": "Capabilities",
    "MCP状态监控": "MCP Monitor",
    "MCP管理": "MCP",
    "知识检索历史": "Retrieval History",
    "知识管理": "Knowledge",
    "技能状态": "Skills Monitor",
    "技能管理": "Skills",
    "智能体管理": "Agents",
    "角色管理": "Roles",
    "平台管理": "Administration",
    "平台权限": "RBAC",
    "系统设置": "Settings",
    "工作台": "Workbench",
    # Fact graph
    "缩小": "Zoom out",
    "放大": "Zoom in",
    "适应": "Fit",
    "适应屏幕": "Fit to screen",
    "重置": "Reset",
    "重置视图": "Reset view",
    "事实节点": "Fact node",
    "关联关系": "Relationship",
    "无事实节点": "No fact nodes",
    "正在构建图谱": "Building graph",
    # Builtin tools
    "内置工具管理": "Built-in tool management",
    "内置工具": "Built-in tools",
    "工具已启用": "Tool enabled",
    "工具已停用": "Tool disabled",
    "全部选中": "All selected",
    "全部取消选中": "All deselected",
    "工具配置已保存": "Tool configuration saved",
    "工具配置保存失败": "Tool configuration save failed",
    # Modal
    "确认操作": "Confirm action",
    "确认要执行此操作吗？": "Are you sure you want to perform this action?",
    "此操作无法撤销": "This action cannot be undone",
    "继续": "Continue",
    "取消操作": "Cancel operation",
    # Chat plan progress
    "规划中": "Planning",
    "执行中": "Executing",
    "已完成": "Completed",
    "失败": "Failed",
    "重试中": "Retrying",
    "已取消": "Cancelled",
    "步骤": "Step",
    "计划": "Plan",
    "执行计划": "Execution plan",
    "规划步骤": "Planning step",
    "执行步骤": "Execution step",
    # Chat scroll
    "回到最新消息": "Back to latest message",
    "新消息": "New messages",
    "滚动到底部": "Scroll to bottom",
    # Terminal
    "终端": "Terminal",
    "新建终端": "New terminal",
    "关闭终端": "Close terminal",
    "清空终端": "Clear terminal",
    "终端输出": "Terminal output",
    "命令输入": "Command input",
    "执行命令": "Execute command",
    "命令历史": "Command history",
    "连接终端": "Connect terminal",
    "终端连接失败": "Terminal connection failed",
    "终端已断开": "Terminal disconnected",
    # Audit
    "日志审计": "Audit log",
    "审计日志": "Audit log",
    "审计事件": "Audit event",
    "操作类型": "Operation type",
    "操作者": "Operator",
    "操作时间": "Operation time",
    "操作结果": "Operation result",
    "事件类型": "Event type",
    "事件详情": "Event details",
    "今天": "Today",
    "本周": "This week",
    "本月": "This month",
    "最近7天": "Last 7 days",
    "最近30天": "Last 30 days",
    "最近90天": "Last 90 days",
    "自定义时间": "Custom time",
    "开始日期": "Start date",
    "结束日期": "End date",
    "全部类别": "All categories",
    "全部操作": "All actions",
    "全部结果": "All results",
    "成功": "Success",
    "失败": "Failed",
    # WeCom/bot
    "微信机器人": "WeChat bot",
    "企业微信机器人": "WeCom bot",
    "钉钉机器人": "DingTalk bot",
    "飞书机器人": "Feishu bot",
    "Telegram机器人": "Telegram bot",
    "机器人设置": "Bot settings",
    "webhook地址": "Webhook URL",
    "启用": "Enable",
    "禁用": "Disable",
    "测试发送": "Test send",
    "测试发送成功": "Test message sent",
    "测试发送失败": "Test message failed",
    "机器人命令": "Bot commands",
    "绑定": "Bind",
    "解绑": "Unbind",
    "身份验证": "Authentication",
    "发送者身份": "Sender identity",
    "允许的发送者": "Allowed senders",
    "发送": "Send",
    "接收": "Receive",
    "回复": "Reply",
    # Skill description save
    "技能描述已保存": "Skill description saved",
    "技能描述保存失败": "Skill description save failed",
    # Tool guard test
    "工具名称": "Tool name",
    "工具参数（JSON 对象）": "Tool parameters (JSON object)",
    "测试通过": "Test passed",
    "测试失败": "Test failed",
    "请输入工具名称": "Please enter a tool name",
    # Roles related
    "创建角色": "Create role",
    "角色名称": "Role name",
    "角色描述": "Role description",
    "添加角色": "Add role",
    "角色详情": "Role details",
    "角色列表": "Role list",
    "选择角色": "Select role",
    "角色不存在": "Role not found",
    "工具启用状态": "Tool enabled status",
    "在当前角色中的启用状态": "Enabled status in current role",
    "保存唯一标识符": "Save unique identifier",
    "启用的工具排在前面": "Enabled tools sorted first",
    "工具本身的启用状态": "Tool's own enabled status",
    # Api docs
    "API文档": "API documentation",
    "接口文档": "API reference",
    "接口说明": "API description",
    "请求方法": "Request method",
    "请求路径": "Request path",
    "请求参数": "Request parameters",
    "响应参数": "Response parameters",
    "请求示例": "Request example",
    "响应示例": "Response example",
    "接口列表": "API list",
    "接口详情": "API details",
    "接口名称": "API name",
    "接口地址": "API endpoint",
    "接口描述": "API description",
    "接口版本": "API version",
    "认证方式": "Authentication",
    "请求头": "Request headers",
    "响应头": "Response headers",
    "响应体": "Response body",
    "请求体": "Request body",
    "Bearer Token认证": "Bearer Token authentication",
    "Token认证": "Token authentication",
    "认证失败": "Authentication failed",
    "未授权": "Unauthorized",
    "权限不足": "Insufficient permissions",
    # rbac guards
    "权限不足，无法执行此操作": "Insufficient permissions to perform this action",
    "需要登录": "Login required",
    "页面不存在": "Page not found",
    "访问被拒绝": "Access denied",
    "功能未开放": "Feature not available",
    "请联系管理员": "Please contact the administrator",
    # hitl
    "待审计": "Pending",
    "审计策略": "Audit strategy",
    "工具白名单": "Tool whitelist",
    "审计日志": "Audit log",
    "搜索": "Search",
    "搜索应用": "Apply search",
    "决策": "Decision",
    "全部": "All",
    "审批方": "Reviewer",
    "人工": "Human",
    "审计 Agent": "Audit Agent",
    "系统": "System",
    "手动录入": "Manual entry",
    "加载中...": "Loading...",
    "加载中…": "Loading…",
    "审计策略": "Audit strategy",
    "恢复默认": "Restore defaults",
    "保存": "Save",
    "审批模式": "Approval mode",
    "审查编辑": "Review & edit",
    "白名单内工具免审批；审批模式下审计 Agent 仅裁决通过/拒绝。": "Whitelisted tools skip approval; in approval mode the audit agent only decides approve/reject.",
    "审查编辑模式下审计 Agent 可通过 edit 操作修改工具参数。": "In review-edit mode, the audit agent can modify tool parameters via the edit action.",
    "免审批工具白名单": "Approval-exempt tool whitelist",
    "保存后写入 config.yaml 全局白名单并立即生效（与聊天侧栏同步展示）。": "After saving, written to config.yaml global whitelist and takes effect immediately (synced with chat sidebar).",
    "工具": "Tool",
    "会话": "Conversation",
    "决策": "Decision",
    "时间": "Time",
    "备注": "Note",
    "载荷": "Payload",
    "关闭": "Close",
    "审计日志详情": "Audit log details",
    "人工审批": "Manual approval",
    "审计 Agent": "Audit Agent",
    "审批引擎": "Approval engine",
    "当前审批方": "Current reviewer",
    "作用于当前选中会话；未选会话时保存到本机，新建会话时沿用。切换后立即生效。": "Applies to the currently selected session; saved locally when no session selected, applied to new sessions. Takes effect immediately.",
    # misc strings found in tests
    "测试消息": "Test message",
    "示例消息": "Example message",
    "示例内容": "Example content",
    "示例数据": "Example data",
    "示例对话": "Example conversation",
    "用户消息": "User message",
    "助手消息": "Assistant message",
    "系统消息": "System message",
    "工具消息": "Tool message",
    "上传文件": "Upload file",
    "下载文件": "Download file",
    "打开文件": "Open file",
    "选择文件": "Select file",
    "预览文件": "Preview file",
    "删除文件": "Delete file",
    "重命名文件": "Rename file",
    "新建文件夹": "New folder",
    "删除文件夹": "Delete folder",
    "上传成功": "Uploaded successfully",
    "下载成功": "Downloaded successfully",
    # chat scroll test specific
    "按 Enter 发送，Shift+Enter 换行": "Press Enter to send, Shift+Enter for new line",
    "附件列表": "Attachment list",
    "当前会话上下文": "Current session context",
    "已选文件列表": "Selected files list",
    "工具提及候选": "Tool mention suggestions",
    "对话轮次导航": "Conversation turn navigation",
}

def translate_quoted_string(match):
    """Replace Chinese content inside a quoted string."""
    quote = match.group(1)
    content = match.group(2)
    close = match.group(3)
    
    if not re.search(r"[\u4e00-\u9fff]", content):
        return match.group(0)
    
    # Try exact lookup first
    en = zh_to_en(content)
    if en:
        return f"{quote}{en}{close}"
    
    # Try partial replacement of known phrases within the string
    result = content
    # Sort by length (longest first to avoid partial replacements)
    for zh, en_text in sorted(KNOWN_TRANSLATIONS.items(), key=lambda x: -len(x[0])):
        result = result.replace(zh, en_text)
    
    return f"{quote}{result}{close}"

def translate_line_comment(line):
    """Translate a comment line that starts with // or * Chinese."""
    # Extract the comment prefix and Chinese content
    match = re.match(r'^(\s*(?://|/?\*+)\s*)(.*)', line)
    if not match:
        return line
    prefix = match.group(1)
    text = match.group(2)
    
    if not re.search(r"[\u4e00-\u9fff]", text):
        return line
    
    # Try to translate the text
    en = zh_to_en(text.strip())
    if en:
        return f"{prefix}{en}"
    
    # Do word-by-word replacement
    result = text
    for zh, en_text in sorted(KNOWN_TRANSLATIONS.items(), key=lambda x: -len(x[0])):
        result = result.replace(zh, en_text)
    
    return f"{prefix}{result}"

def translate_content(content):
    """Main translation function for a JS file."""
    
    # 1. Replace strings in i18n fallback patterns like:
    #    chatTranslate('key', '中文')  or  t('key', '中文')  or  window.t('key')  or  '中文'
    # Pattern: translate('some.key', '中文fallback')
    def replace_i18n_call(m):
        key = m.group(1)
        quote = m.group(2)
        zh_text = m.group(3)
        en = get_en(key)
        if en and not re.search(r"[\u4e00-\u9fff]", en):
            return f"'{key}', {quote}{en}{quote}"
        en2 = zh_to_en(zh_text)
        if en2:
            return f"'{key}', {quote}{en2}{quote}"
        return m.group(0)
    
    content = re.sub(
        r"'([a-zA-Z][a-zA-Z0-9._]+)',\s*(['\"`])([\u4e00-\u9fff][^'\"` ]*['\"`\)].*?)\2",
        replace_i18n_call,
        content
    )
    
    # 2. Replace all quoted Chinese strings
    def repl_single(m):
        text = m.group(1)
        if not re.search(r"[\u4e00-\u9fff]", text):
            return m.group(0)
        en = zh_to_en(text)
        if en:
            return f"'{en}'"
        return f"'{translate_partial(text)}'"

    def repl_double(m):
        text = m.group(1)
        if not re.search(r"[\u4e00-\u9fff]", text):
            return m.group(0)
        en = zh_to_en(text)
        if en:
            return f'"{en}"'
        return f'"{translate_partial(text)}"'

    # Single-quoted strings
    content = re.sub(r"'((?:[^'\\]|\\.)*[\u4e00-\u9fff](?:[^'\\]|\\.)*)'", repl_single, content)
    # Double-quoted strings
    content = re.sub(r'"((?:[^"\\]|\\.)*[\u4e00-\u9fff](?:[^"\\]|\\.)*)"', repl_double, content)
    # Template literals (basic - non-nested)
    content = re.sub(r'`((?:[^`\\$]|\\.|\$(?!\{))*[\u4e00-\u9fff](?:[^`\\$]|\\.|\$(?!\{))*)`',
                     lambda m: f"`{translate_partial(m.group(1))}`", content)
    
    # 3. Replace Chinese in comments
    lines = content.split('\n')
    new_lines = []
    for line in lines:
        if not re.search(r"[\u4e00-\u9fff]", line):
            new_lines.append(line)
            continue
        
        stripped = line.lstrip()
        if stripped.startswith('//') or (stripped.startswith('*') and not stripped.startswith('*/')) or stripped.startswith('/*'):
            new_lines.append(translate_line_comment(line))
        else:
            # Inline comment: text // Chinese
            # Replace Chinese in the comment part (after //)
            def repl_inline_comment(m):
                prefix = m.group(1)
                comment = m.group(2)
                result = comment
                for zh, en_text in sorted(KNOWN_TRANSLATIONS.items(), key=lambda x: -len(x[0])):
                    result = result.replace(zh, en_text)
                return f"{prefix}{result}"
            
            new_line = re.sub(r'(//\s*)(.*[\u4e00-\u9fff].*)', repl_inline_comment, line)
            new_lines.append(new_line)
    
    return '\n'.join(new_lines)

def translate_partial(text):
    """Replace known Chinese phrases within a longer text."""
    result = text
    for zh, en_text in sorted(KNOWN_TRANSLATIONS.items(), key=lambda x: -len(x[0])):
        result = result.replace(zh, en_text)
    return result


# ── Process all files ─────────────────────────────────────────────────────────
total_before = 0
total_after = 0

for root, dirs, files in os.walk("web/static/js"):
    dirs[:] = [d for d in dirs if d != "vendor"]
    for fname in sorted(files):
        if not fname.endswith((".js", ".cjs")):
            continue
        path = os.path.join(root, fname)
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            content = f.read()
        
        before = len(re.findall(r"[\u4e00-\u9fff]", content))
        if before == 0:
            continue
        
        new_content = translate_content(content)
        after = len(re.findall(r"[\u4e00-\u9fff]", new_content))
        
        total_before += before
        total_after += after
        
        with open(path, "w", encoding="utf-8") as f:
            f.write(new_content)
        
        if after > 0:
            print(f"  PARTIAL {path}: {before} -> {after}")

print(f"\nTotal: {total_before} -> {total_after} remaining ({total_before - total_after} replaced)")
