#!/usr/bin/env python3
"""
Third-pass JS translation: handles all remaining Chinese phrases.
"""
import os, re

CHINESE_RE = re.compile(r'[\u4e00-\u9fff\u3400-\u4dbf\uff00-\uffef\u2e80-\u2eff\u3000-\u303f]')

PHRASES = [
    # ── chat.js ───────────────────────────────────────────────────────────────
    ("（/api/multi-agent/stream）", " (/api/multi-agent/stream)"),
    ("必须在渲染用户气泡和发起 POST 前做一次权威状态同步，避免Generate一轮\"a task is already executing\"伪Chat。", "must perform an authoritative state sync before rendering the user bubble and issuing the POST, to avoid generating a spurious 'task already executing' chat round."),
    ("确保 chat-input-container 有 id（若模板未写）", "Ensure chat-input-container has an id (if not written in template)"),
    ("获取Current选中的Role（从 roles.js 的函数获取）", "Get the currently selected role (from roles.js function)"),
    ("同时获取External MCP列表", "Also fetch the external MCP list"),
    ("只包含Connected且Enabled的MCP", "Only include connected and enabled MCPs"),
    ("加载External MCP列表Failed:", "Failed to load external MCP list:"),
    ("构建API URL，如果指定了Role，添加role查询参数", "Build API URL; if a role is specified, add the role query parameter"),
    ("使用唯一标识符来去重，而不Yes只使用Tool name", "Use unique identifier for deduplication, not just tool name"),
    ("OK工具在CurrentRole中的Enable状态", "Determine the tool's enabled state in the current role"),
    ("如果有 role_enabled 字段，使用它（表示指定了Role）", "If role_enabled field exists, use it (indicates a role was specified)"),
    ("No则使用 enabled 字段（表示未指定Role或使用所有工具）", "Otherwise use the enabled field (indicates no role specified or all tools used)"),
    ("工具本身的Enable状态", "Tool's own enabled state"),
    ("在CurrentRole中的Enable状态", "Enabled state in current role"),
    ("Save唯一标识符", "Save unique identifier"),
    ("加载Tool listFailed，@提及功能可能不可用:", "Failed to load tool list, @ mention feature may be unavailable:"),
    ("Auto调整输入框高度", "Auto-adjust input height"),
    ("使用requestAnimationFrame确保在DOMUpdate后立即调整，特别Yes在Delete内容时", "Use requestAnimationFrame to ensure immediate adjustment after DOM update, especially when deleting content"),
    ("Save输入内容到localStorage（防抖）", "Save input content to localStorage (debounced)"),
    ("如果正在使用输入法输入（IME），回车键应该用于Confirm候选词，而不YesSend message", "If IME input is active, Enter should confirm candidates, not send the message"),
    ("Safari 可能在Confirm候选词时先触发 compositionend，再触发 Enter keydown，", "Safari may fire compositionend before Enter keydown when confirming candidates,"),
    ("因此这里同时使用全局状态和 keyCode 229 兜底。", "so both global state and keyCode 229 are used as fallback here."),
    ("Enter 直接Send; Shift+Enter 保留 textarea 原生换行行为。", "Enter sends directly; Shift+Enter preserves textarea native newline behavior."),
    ("限制触发字符之前必须YesEmpty白或起始位置", "Require that the character before the trigger must be whitespace or start of line"),
    ("检查YesNo精确匹配External MCP名称", "Check if it exactly matches an external MCP name"),
    ("如果完全匹配MCP名称，只显示该MCP下的所有工具", "If exactly matches an MCP name, show only tools under that MCP"),
    ("检查YesNo部分匹配MCP名称", "Check if it partially matches an MCP name"),
    ("Normal匹配: 按Tool name和描述过滤，同时也匹配MCP名称", "Normal matching: filter by tool name and description, also match MCP name"),
    ("如果部分匹配到MCP名称，也包含该MCP下的所有工具", "If partially matches an MCP name, also include all tools under that MCP"),
    ("如果指定了Role，优先显示在CurrentRole中Enable的工具", "If a role is specified, prioritize showing tools enabled in the current role"),
    ("Enable的工具排在前面", "Enabled tools are listed first"),
    ("精确匹配MCP名称的工具优先显示", "Tools matching MCP name exactly are shown first"),
    ("如果指定了Role，使用 roleEnabled; No则使用 enabled", "If a role is specified, use roleEnabled; otherwise use enabled"),
    ("正在加载工具...", "Loading tools..."),
    ("没有匹配的工具", "No matching tools"),
    ("如果工具有 roleEnabled 字段（指定了Role），使用它; No则使用 enabled", "If the tool has a roleEnabled field (role was specified), use it; otherwise use enabled"),
    ("外部", "External"),
    ("内置", "Built-in"),
    ("根据工具在CurrentRole中的Enable状态显示状态标签", "Show status label based on the tool's enabled state in the current role"),
    ("可用", "Available"),
    ("已Disable（CurrentRole）", "Disabled (current role)"),
    ("已Disable", "Disabled"),
    ("来源: External MCP", "Source: External MCP"),
    ("来源: Built-in tools", "Source: Built-in tools"),
    ("来源: ", "Source: "),
    ("调整输入框高度并Save草稿", "Adjust input height and save draft"),
    ("初始化时设置正确的高度", "Set correct height on initialization"),
    ("ResumeSave的草稿（仅在输入框为Empty时Resume，避免覆盖用户输入）", "Restore saved draft (only when input is empty, to avoid overwriting user input)"),
    ("检查Chat中YesNo有最近的消息（30 sec内），如果有，说明可能YesJust nowSend的消息，不Resume草稿", "Check if there are recent messages in the chat (within 30 sec); if so, the message may have just been sent, do not restore draft"),
    ("检查最后一条消息的时间", "Check the time of the last message"),
    ("如果最后一条消息YesUser message，且时间很近，不Resume草稿", "If the last message is a user message and was very recent, do not restore draft"),
    ("检查消息时间，如果Yes最近30 sec内的，不Resume草稿", "Check message time; if within the last 30 sec, do not restore draft"),
    ("简单检查: 如果消息时间显示的YesCurrent时间（格式: HH:MM），且YesUser message，不Resume草稿", "Simple check: if message time shows current time (format: HH:MM) and is a user message, do not restore draft"),
    ("更精确的方法Yes检查消息的Created time，但需要从消息元素中获取", "More precise method is to check message creation time, but requires extracting from message element"),
    ("这里采用简单策略: 如果最后一条YesUser message，且输入框为Empty，可能Yes刚Send的，不Resume草稿", "Use simple strategy here: if the last message is a user message and the input is empty, it was likely just sent, do not restore draft"),
    ("即使不Resume草稿，也要清除localStorage中的草稿，避免下次误Resume", "Even if not restoring the draft, clear it from localStorage to avoid incorrect restoration next time"),
    ("消息计数器，确保ID唯一", "Message counter, ensuring unique IDs"),
    ("为消息气泡中的表格添加独立的滚动容器", "Add independent scroll containers for tables inside message bubbles"),
    ("检查表格YesNo已经有包装容器", "Check if the table already has a wrapper container"),
    ("创建表格包装容器", "Create table wrapper container"),
    ("将表格移动到包装容器中", "Move the table into the wrapper container"),
    ("仅限制Project名的界面展示，不修改实际Save的名称。", "Only limits the project name display in the UI, does not modify the actually saved name."),
    ("CurrentNo project，Please enter您的Test需求，System将AutoExecute相应的SafeTest。", "No current project. Please enter your test requirements and the system will automatically run the appropriate security test."),
    ("Current", "Current "),
    ("Project，Please enter您的Test需求，System将AutoExecute相应的SafeTest。", " project. Please enter your test requirements and the system will automatically run the appropriate security test."),
    ("要Test什么？", "What would you like to test?"),
    ("要在 ", "What would you like to test in "),
    (" more items目中Test什么？", "?"),
    ("Please enter您的Test需求，System将AutoExecute相应的SafeTest。", "Please enter your test requirements and the system will automatically run the appropriate security test."),
    ("Update新Chat欢迎Empty状态，并兼容Refresh旧Version遗留的System就绪消息。", "Update new chat welcome empty state, compatible with refreshing legacy system-ready messages from old versions."),
    ("Copy消息内容", "Copy message content"),
    ("添加消息（options.systemReadyMessage 为 true 时，Language switch会Refresh该条文案）", "Add message (when options.systemReadyMessage is true, language switch will refresh this text)"),
    ("创建消息内容容器", "Create message content container"),
    ("创建消息气泡", "Create message bubble"),
    ("解析 Markdown 或 HTML 格式", "Parse Markdown or HTML format"),
    ("Assistant message中的已知ChineseError前缀做国际化替换（后端固定BackChinese）", "Replace known Chinese error prefixes in assistant messages with i18n (backend always returns Chinese)"),
    ("调用OpenAIFailed:", "Failed to call OpenAI:"),
    ("对于User message，直接转义HTML，不进行Markdown解析，以保留所有特殊字符", "For user messages, escape HTML directly without Markdown parsing to preserve all special characters"),
    ("RefreshResumeRunning会话时，后端正文可能仍Yes持久化占位值\"Processing...\"。", "When refreshing and resuming a running session, the backend body may still be the persisted placeholder value 'Processing...'."),
    ("保留消息节点供迭代Details和最终回复复用，但不要把占位值显示成助手正文。", "Keep the message node for reuse in iteration details and final reply, but do not display the placeholder as the assistant body."),
    ("为每个表格添加独立的滚动容器", "Add independent scroll containers for each table"),
    ("Save原始内容到消息元素，用于Copy功能", "Save original content to the message element for copy functionality"),
    ("添加时间戳", "Add timestamp"),
    ("如果有传入的Created time，使用它; No则使用Current时间", "If a creation time is passed in, use it; otherwise use current time"),
    ("处理字符串或Date对象", "Handle string or Date object"),
    ("如果解析Failed，使用Current时间", "If parsing fails, use current time"),
    ("为用户和Assistant message添加Copy按钮（Copy整条消息内容）", "Add copy button for user and assistant messages (copies entire message content)"),
    ("有 MCP Execute记录且非流式占位消息时展示调用按钮; 带 progressId 的流式占位不挂此条（与进度卡片一致，结束时 integrate 再创建）", "Show call button when there are MCP execution records and the message is not a streaming placeholder; streaming placeholders with progressId are excluded (consistent with progress cards, created by integrate at end)"),
    ("标记「System就绪」占位消息，便于切换Language后Refresh文案", "Mark 'system ready' placeholder messages for text refresh on language switch"),
    ("Copy消息内容到剪贴板（使用原始Markdown格式）", "Copy message content to clipboard (using original Markdown format)"),
    ("获取Save的原始Markdown内容", "Get saved original Markdown content"),
    ("统一的Copy处理函数", "Unified copy handler function"),
    ("优先使用现代 Clipboard API（需要 HTTPS 或 localhost）", "Prefer modern Clipboard API (requires HTTPS or localhost)"),
    ("降级方案: 使用传统的 execCommand 方法（适用于 HTTP 环境）", "Fallback: use traditional execCommand method (for HTTP environments)"),
    ("降级Copy函数（使用 document.execCommand）", "Fallback copy function (using document.execCommand)"),
    ("降级Copy failed:", "Fallback copy failed:"),
    ("Copy failed，请手动选择内容Copy", "Copy failed, please manually select and copy content"),
    ("如果没有Save原始内容，尝试从渲染后的HTML提取（降级方案）", "If no original content was saved, try extracting from rendered HTML (fallback)"),
    ("RemoveCopy按钮本身（避免Copy按钮文本）", "Remove the copy button itself (to avoid including button text)"),
    ("提取纯文本内容", "Extract plain text content"),
    ("使用原始Markdown内容", "Use original Markdown content"),
    ("Copy消息时出错:", "Error copying message:"),
    ("显示CopiedHint", "Show copied hint"),
    ("Claude extended thinking 内部尾缀（与后端 DisplayReasoningContent 一致，UI 不展示）", "Claude extended thinking internal suffix (consistent with backend DisplayReasoningContent, not displayed in UI)"),
    ("合并 messages.reasoningContent 与 process_details 中的 reasoning_chain，两者都读、都展示（去重后）", "Merge messages.reasoningContent with reasoning_chain from process_details; both are read and displayed (after deduplication)"),
    ("最终回复到达后同样必须完整Resume过程Details; None参数接口Default仅Back前 50 条，", "After the final reply arrives, the full process details must also be restored; the no-parameter API defaults to returning only the first 50 items,"),
    ("No则这里会把 task-events Resume出的完整时间线再次覆盖成First page。", "otherwise this would overwrite the complete timeline restored by task-events back to the first page."),
    ("相邻且类型/正文/data 完全一致的过程Details只保留一条（与后端去重一致，避免时间线叠多条相同块）", "Adjacent process details that are identical in type/body/data keep only one entry (consistent with backend deduplication, avoids stacking identical blocks in the timeline)"),
    ("Eino TurnLoop 常驻多轮 runtime 已接管本轮会话。", "Eino TurnLoop persistent multi-round runtime has taken over this session."),
    ("Eino TurnLoop 已在Safe点切换到用户补充后的下一轮。", "Eino TurnLoop has switched to the next round after user supplement at a safe point."),
    ("已将用户补充推入 Eino TurnLoop，正在等待Safe点切换…", "User supplement pushed into Eino TurnLoop, waiting for safe point switch…"),
    ("workflow_node_start 已经表达了节点进入; 这些事件只用于实时状态，落到Details里会让 Agent 节点看起来重复启动。", "workflow_node_start already expresses node entry; these events are only for real-time status, adding them to details would make agent nodes appear to start repeatedly."),
    ("懒加载占位Hint可点击，与工具栏「ExpandDetails」行为一致", "Lazy-load placeholder hint is clickable, consistent with toolbar 'expand details' behavior"),
    ("渲染过程Details", "Render process details"),
    ("options.append=true 时分page追加; options.markLoaded=false 时保留 lazy 标记（分pageLoading）", "With options.append=true, append page; with options.markLoaded=false, keep the lazy marker (paginated loading)"),
    ("查找或创建 MCP 区域（工具栏 + Tool list + 迭代时间线 分区）", "Find or create the MCP area (toolbar + tool list + iteration timeline section)"),
    ("添加过程Details按钮（如果still没有）", "Add process details button (if not already present)"),
    ("创建过程Details容器（放在Tool list之后）", "Create process details container (placed after tool list)"),
    ("Created time线（即使没有processDetails也要创建，以便ExpandDetails按钮能Normal工作）", "Create timestamp line (even without processDetails, to allow expand details button to work normally)"),
    ("processDetails === null 表示\"尚未加载（懒加载）\"; messages.reasoningContent 可先展示", "processDetails === null means 'not yet loaded (lazy load)'; messages.reasoningContent can be shown first"),
    ("点击后加载迭代Details", "Click to load iteration details"),
    # ── monitor.js ────────────────────────────────────────────────────────────
    ("分page加载过程Details并增量渲染。Default全量加载供Resume流程使用;", "Load process details by page and render incrementally. Default full load is used for the resume flow;"),
    ("用户手动Expand时由Task status选择首个历史page或Latestpage，滚动到边界后Auto加载相邻page。", "when user manually expands, task status selects the first history page or latest page, and after scrolling to the boundary, auto-loads adjacent pages."),
    ("初page渲染Complete前禁止顶部哨兵抢先触发; 定位到底部后再开放Auto加载。", "Disable the top sentinel from triggering before initial page render completes; enable auto-load after positioning to the bottom."),
    ("renderProcessDetails 对大page分帧渲染; 等待一帧后再放置顶部/底部哨兵，", "renderProcessDetails renders large pages in frames; wait one frame before placing top/bottom sentinels,"),
    ("避免哨兵被后续批次插到时间线中间。", "to avoid sentinels being inserted into the middle of the timeline by subsequent batches."),
    ("renderProcessDetails 可能继续分帧追加，且Resume后的 SSE 会继续增长同一条思考文本;", "renderProcessDetails may continue appending in frames, and the resumed SSE will continue growing the same thinking text;"),
    ("为迭代Details单独建立短时粘底，而不只滚动外层Chat容器。", "establish short-lived sticky-bottom specifically for iteration details, instead of only scrolling the outer chat container."),
    ("task-events Resume流会明确给CurrentDetails容器打 is-streaming 标记。", "task-events resume stream will explicitly mark the current details container with is-streaming."),
    ("其余情况按终态/历史Details处理，从第一条开始，便于顺序复盘。", "Other cases are treated as terminal/historical details, starting from the first item for sequential review."),
    ("加载过程DetailsFailed:", "Failed to load process details:"),
    ("暂None", "No "),
    ("切换过程Details显示", "Toggle process details display"),
    ("懒加载: 首次Expand时才从后端拉取该条消息的过程Details", "Lazy load: only fetch this message's process details from backend on first expand"),
    ("滚动到Expand的Details位置（流式且用户上滑阅读时不抢主列表滚动）", "Scroll to the expanded details position (do not grab the main list scroll when streaming and user is scrolling up to read)"),
    ("StopCurrent进度: 弹出「中断并说明 / 彻底Stop」", "Stop current progress: pop up 'interrupt and explain / fully stop'"),
    ("将后端消息 UUID 绑定到助手气泡，供Delete本轮 / 过程Details懒加载（domId 为前端 msg-*）", "Bind backend message UUID to assistant bubble for deleting this round / lazy-loading process details (domId is frontend msg-*)"),
    ("将后端User message ID 绑定到最后一条尚Unbound backendMessageId 的用户气泡", "Bind backend user message ID to the last user bubble that has no bound backendMessageId"),
    ("去重合并 MCP execution id（顺序: 先 prev 后 next），用于多段 Run / 多次 SSE 同一任务。", "Dedup-merge MCP execution IDs (order: prev first then next), used for multi-segment run / multiple SSE for the same task."),
    ("重试进度: 第 ", "Retry progress: round "),
    ("/' + maxAttempts + ' 次，等待 ", "/ ' + maxAttempts + ' rounds, waiting "),
    ("原因类型", "reason type"),
    ("限流 / 请求过多", "rate limited / too many requests"),
    ("可重试 HTTP Error", "retryable HTTP error"),
    ("上游服务Error", "upstream service error"),
    ("上游繁忙", "upstream busy"),
    ("网络连接Abnormal", "network connection abnormal"),
    ("流式读取Abnormal", "streaming read abnormal"),
    ("临时Abnormal", "transient abnormal"),
    ("🔁 临时Error重试", "🔁 transient error retry"),
    ("🔁 Model调用重试", "🔁 model call retry"),
    ("原因: ", "Reason: "),
    ("🔀 切换备用Model", "🔀 switch to backup model"),
    ("通道: ", "Channel: "),
    ("Token 用量汇总", "token usage summary"),
    ("Model调用", "model calls"),
    ("输入 tokens", "input tokens"),
    ("总 tokens", "total tokens"),
    ("缓存 tokens", "cached tokens"),
    ("推理 tokens", "reasoning tokens"),
    ("处理流式事件", "Process streaming events"),
    ("不依赖进度时间线; 在首条 SSE 即可绑定User message ID", "Does not depend on progress timeline; can bind user message ID on first SSE"),
    ("终态事件（error/cancelled）优先复用现有Assistant message，避免重复追加相同报错", "Terminal events (error/cancelled) preferentially reuse existing assistant messages to avoid appending duplicate errors"),
    ("SSE 长连接保活，None需Update UI", "SSE long-connection keepalive, no UI update needed"),
    ("在Update之前，先获取任务对应的原始ChatID", "Before updating, first get the original chat ID corresponding to the task"),
    ("如果用户已经开始了新Chat（currentConversationId 为 null），", "If the user has already started a new chat (currentConversationId is null),"),
    ("且这个 conversation 事件来自旧Chat，就不Update currentConversationId", "and this conversation event is from the old chat, do not update currentConversationId"),
    ("用户已经开始了新Chat，Ignore旧Chat的 conversation 事件", "User has already started a new chat, ignoring old chat's conversation event"),
    ("但仍然UpdateTask status，以便正确显示任务Info", "but still update task status to correctly display task info"),
    ("延迟RefreshChat列表，确保User message已Save，updated_at已Update", "Delay refreshing chat list to ensure user message is saved and updated_at is updated"),
    ("这样新Chat才能正确显示在最近Chat列表的顶部", "so the new chat is correctly shown at the top of the recent chat list"),
    ("Refresh最近Chat列表", "Refresh recent chat list"),
    ("主通道进入新轮次或Workflows切换到新 Agent 节点后，不复用上一段的流式时间线条目", "After main channel enters a new round or Workflows switches to a new agent node, do not reuse the streaming timeline entry from the previous segment"),
    ("同一主Agent可能从\"进入Model\"和\"检测到工具批次\"两条路径补发同一轮次。", "The same main agent may re-send the same round via both 'entering model' and 'detected tool batch' paths."),
    ("状态缓存仍Update，但时间线只保留一个幂等条目。", "State cache still updates, but the timeline keeps only one idempotent entry."),
    ("Plan-Execute · 第 ", "Plan-Execute · Round "),
    (" 轮 · ", " · "),
    ("主Agent · 第 ", "Main Agent · Round "),
    (" 轮", ""),
    ("子Agent · ", "Sub-Agent · "),
    (" · 第 ", " · Round "),
    (" 步", ""),
    ("第 ", "Round "),
    (" 轮迭代", " iteration"),
    ("🧭 Workflows开始", "🧭 Workflows started"),
    ("▶ 节点开始", "▶ Node started"),
    ("条件判断", "condition check"),
    ("节点Complete", "node complete"),
    ("Execute分支", "execute branch"),
    ("Skip分支", "skip branch"),
    ("🔧 工具节点", "🔧 tool node"),
    ("🧑‍⚖️ 人工Confirm检查点", "🧑‍⚖️ manual confirmation checkpoint"),
    ("✅ 审批Approved", "✅ approval approved"),
    ("Manual approvalApproved，继续Execute", "Manual approval approved, continuing execution"),
    ("❌ 审批Rejected", "❌ approval rejected"),
    ("同一 streamId 重复 start: 复用已有条目，避免孤儿卡片 + 新条目重复收 delta", "Duplicate start for same streamId: reuse existing entry to avoid orphan cards + duplicate delta reception"),
    ("推理过程", "reasoning process"),
    ("AI思考", "AI thinking"),
    ("若已由 *_stream_* 聚合（带 streamId），避免重复创建 timeline item", "If already aggregated by *_stream_* (with streamId), avoid creating duplicate timeline items"),
    ("助手正文段结束、进入工具调用: 下一段 response_start 应新建时间线条目", "Assistant body segment ended, entering tool call: the next response_start should create a new timeline entry"),
    ("Final reply check passed。", "Final reply check passed."),
    ("继续验证", "Continue verification"),
    ("Tool execution已收尾", "Tool execution finalized"),
    ("Audit Agent 正在审查", "Audit Agent is reviewing"),
    ("⏸️ 用户中断并继续", "⏸️ user interrupted and continued"),
    ("⚠️ Eino 流式中断（", "⚠️ Eino streaming interrupted ("),
    ("⚠️ Eino 流式中断", "⚠️ Eino streaming interrupted"),
    ("流式读取Abnormal，System将按策略重试或结束。", "Streaming read abnormal; system will retry or end according to policy."),
    ("🔁 Auto续跑（None助手正文）", "🔁 auto-continue (no assistant body)"),
    ("会话已结束但未捕获到助手正文，正在基于轨迹Auto续跑…", "Session ended without capturing assistant body; auto-continuing based on trajectory…"),
    ("⛔ 达到迭代上限", "⛔ iteration limit reached"),
    ("已达到最大迭代次数，任务Stopped继续Auto迭代。", "Maximum iterations reached, task stopped continuing auto-iteration."),
    ("🧹 工具调用收尾补偿", "🧹 tool call finalization compensation"),
    ("检测到 ", "Detected "),
    (" 未闭合工具调用，已Auto标记为Failed并收尾。", " unclosed tool calls, automatically marked as failed and finalized."),
    ("Unknown工具", "unknown tool"),
    ("同一 toolCallId 的重复 tool_call（重试/补发）只Update状态，不重复追加条目。", "Duplicate tool_call for same toolCallId (retry/resend) only updates status, does not append duplicate entries."),
    ("如果有toolCallId，Storage映射关系以便后续Update状态", "If there is a toolCallId, store the mapping for subsequent status updates"),
    ("添加Executing状态指示器", "Add executing status indicator"),
    ("Tool execution过程不流式展示，仅等 tool_result 展示最终结果。", "Tool execution process is not shown streaming; only waits for tool_result to show final result."),
    ("工具 ", "Tool "),
    ("子Agent回复", "sub-agent reply"),
    ("Save原文，Language switch时可用 translateProgressMessage 重新套CurrentLanguage", "Save original text; on language switch, translateProgressMessage can reapply the current language"),
    ("复用已有Assistant message（若有），避免终态事件重复插入消息", "Reuse existing assistant message (if any) to avoid terminal events inserting duplicate messages"),
    ("立即RefreshTask status", "Immediately refresh task status"),
    ("如果用户已经开始了新Chat（currentConversationId 为 null），且这个事件来自旧Chat，则Ignore", "If user has already started a new chat (currentConversationId is null) and this event is from the old chat, ignore it"),
    ("多Agent模式下，迭代过程中的Output只显示在时间线中，不创建Assistant message气泡", "In multi-agent mode, output during iteration is only shown in the timeline, no assistant message bubble is created"),
    ("Eino 可能对同一段流重复发 response_start; 复用已有条目与 buffer，避免多条「Assistant output」", "Eino may send duplicate response_start for the same stream; reuse existing entry and buffer to avoid multiple 'assistant output' entries"),
    ("多Agent模式下，迭代过程中的Output只显示在时间线中", "In multi-agent mode, output during iteration is only shown in the timeline"),
    ("Updated time线条目内容", "Update timeline entry content"),
    ("流式阶段仅追加纯文本; formatTimelineStreamBody 在终态 response 时一次性处理", "Streaming phase only appends plain text; formatTimelineStreamBody processes once at terminal response"),
    ("在Update之前，先获取任务对应的原始ChatID", "Before updating, first get the original chat ID for the task"),
    ("先Update mcp ids", "First update MCP ids"),
    ("如果之前已经在 response_start/response_delta 阶段创建过占位，则复用该消息Update最终内容", "If a placeholder was previously created in response_start/response_delta phase, reuse that message to update final content"),
    ("将 response_start/response_delta 占位固化为 planning，与后端落库一致后再快照过程Details", "Solidify response_start/response_delta placeholder as planning, consistent with backend DB storage, then snapshot process details"),
    ("候选OutputMissing finalisation evidence", "Candidate output missing finalisation evidence"),
    ("最终回复时隐藏进度卡片（多Agent模式下，迭代过程已完整展示）", "Hide progress card on final reply (in multi-agent mode, iteration process is fully displayed)"),
    ("将Details入口集成到工具调用区域; 完整过程从后端分page加载，不依赖实时 DOM 快照。", "Integrate details entry into the tool call area; full process is loaded paginated from backend, not relying on real-time DOM snapshot."),
    ("显示Error", "Show error"),
    ("Update进度标题为Error状态", "Update progress title to error state"),
    ("Update进度容器为Completed状态（添加completed类）", "Update progress container to completed state (add completed class)"),
    ("Complete进度任务（标记为Failed）", "Complete progress task (mark as failed)"),
    # ── webshell.js ────────────────────────────────────────────────────────────
    ("webshell.title", "webshell.title"),
    ("webshell.addConnection", "webshell.addConnection"),
    ("webshell.cmdParam", "webshell.cmdParam"),
    ("WebShell 管理", "WebShell Management"),
    ("添加连接", "Add connection"),
    ("Command参数名", "Command parameter name"),
    # ── assets.js ─────────────────────────────────────────────────────────────
    ("目标", "target"),
    ("所属Project", "project"),
    ("标签", "tags"),
    ("完整url", "full url"),
    ("主机", "host"),
    ("ip地址", "ip address"),
    ("域名", "domain"),
    ("端口", "port"),
    ("协议", "protocol"),
    ("标题", "title"),
    ("page面标题", "page title"),
    ("服务", "service"),
    ("产品", "product"),
    ("服务指纹", "service fingerprint"),
    ("国家", "country"),
    ("国家地区", "country/region"),
    ("省份", "province"),
    ("州", "state"),
    ("城市", "city"),
    ("负责人", "responsible person"),
    ("责任人", "owner"),
    ("部门", "department"),
    ("业务System", "business system"),
    ("环境", "environment"),
    ("重要性", "criticality"),
    ("重要等级", "importance level"),
    ("状态", "status"),
    ("表格组件Load failed，请Refresh后重试", "Spreadsheet component failed to load, please refresh and try again"),
    ("Asset批量Import填写说明", "Asset batch import instructions"),
    ("必填: target，或 host / ip / domain 中至少一items", "Required: target, or at least one of host / ip / domain"),
    ("target 示例: https://example.com:443、example.com、1.1.1.1:22", "target example: https://example.com:443, example.com, 1.1.1.1:22"),
    ("project 填写System中已有的Project name或Project ID，留Empty表示不绑定", "project: enter an existing project name or project ID in the system; leave empty to not bind"),
    ("tags 使用逗号分隔，最多 30 ", "tags: use comma-separated values, max 30 "),
    ("status 仅支持 active / inactive，留EmptyDefault为 active", "status: only supports active / inactive; leave empty to default to active"),
    ('请在"Assets"工作表中填写，最多 100000 行', 'Fill in the "Assets" worksheet, max 100,000 rows'),
    ("填写说明", "Instructions"),
    ("尚未Select file", "No file selected"),
    # ── auth.js ───────────────────────────────────────────────────────────────
    ("None法持久化认证Info:", "Failed to persist authentication info:"),
    ("None法清除认证Info:", "Failed to clear authentication info:"),
    ("读取认证InfoFailed:", "Failed to read authentication info:"),
    ("隐藏Password", "Hide password"),
    ("显示Password", "Show password"),
    ("认证已过期，Please sign in again", "Authentication expired, please sign in again"),
    ("未授权访问", "Unauthorized access"),
    ("403 属于可预期的 RBAC Reject，Back Response 供调用方Approve res.ok / ensureApiOk 处理。", "403 is an expected RBAC rejection; return the Response for the caller to handle via res.ok / ensureApiOk."),
    ("multipart POST with XMLHttpRequest so upload progress is available (fetch None法可靠上报进度).", "multipart POST with XMLHttpRequest so upload progress is available (fetch cannot reliably report progress)."),
    ("Back与 fetch 类似的对象: ok、status、json()、text()", "Returns an object similar to fetch: ok, status, json(), text()"),
    ("Username cannot be empty，且不能超过 64 字", "Username cannot be empty and must not exceed 64 characters"),
    ("Sign in failed，请检查Password", "Sign in failed, please check your password"),
    ("Sign in failed，Please try again later", "Sign in failed, please try again later"),
    ("RefreshChat模式配置Failed:", "Failed to refresh chat mode configuration:"),
    ("未Sign in首屏的Project侧栏可能先收到 401 并显示Failed; 认证Complete后必须主动重试。", "The project sidebar on the pre-login screen may receive 401 and show failure first; must actively retry after authentication completes."),
    ("放在Chat/任务Refresh之后，确保最终渲染一定使用有效Sign in态且不会被早期Failed覆盖。", "Placed after chat/task refresh to ensure final rendering always uses a valid sign-in state and is not overwritten by early failures."),
    ("RefreshProject侧栏Failed:", "Failed to refresh project sidebar:"),
    ("等待 i18n 首包加载Complete后再插System就绪消息，避免清除缓存后Language显示 English 气泡仍YesChinese", "Wait for i18n initial bundle to load before inserting system-ready message, to avoid the bubble still showing Chinese after cache clear when language is English"),
    ("等待 i18n 就绪Failed，继续初始化聊天", "Failed waiting for i18n ready, continuing chat initialization"),
    ("用户菜单: {{name}}", "User menu: {{name}}"),
    ("Unknown用户", "Unknown user"),
    ("All资源", "All resources"),
    ("指定资源", "Specified resources"),
    ("自己的资源", "Own resources"),
    ("资源范围Unknown", "Resource scope unknown"),
    ("{{count}} more items权限", "{{count}} permissions"),
    ("用户菜单: {{name}}", "User menu: {{name}}"),
    ("用户菜单", "User menu"),
    ("通用工具函数", "General utility functions"),
    # ── tasks.js ──────────────────────────────────────────────────────────────
    ("Taskspage面功能", "Tasks page functionality"),
    ("插值不转 HTML 实体（避免日期里的 / 变成 &#x2F; 再被 escapeHtml 成乱码）", "Interpolation does not escape HTML entities (to prevent / in dates from becoming &#x2F; and then being garbled by escapeHtml)"),
    ("与创建队列 / API 一致的合法 agentMode", "Valid agentMode values consistent with queue creation / API"),
    ("批量队列 agentMode 展示文案（与Chat模式命名一致）", "Batch queue agentMode display text (consistent with chat mode naming)"),
    ("Cron 队列在「本轮 completed」等状态下的展示文案（底层 status 不变，仅 UI 强调循环调度）", "Cron queue display text for states like 'this round completed' (underlying status unchanged, UI only emphasizes scheduled cycle)"),
    ("队列YesNo处于「可改子Task list/文案」的Empty闲态（与后端 batch_task_manager.queueAllowsTaskListMutationLocked 对齐）", "Whether the queue is in the idle state that allows task list/text modification (aligned with backend batch_task_manager.queueAllowsTaskListMutationLocked)"),
    ("YesNo允许对指定子任务发起单条Execute（与后端 queueAllowsSingleTaskRunLocked 对齐）", "Whether single execution is allowed for a specific subtask (aligned with backend queueAllowsSingleTaskRunLocked)"),
    ("HTML转义函数（如果未定义）", "HTML escape function (if not defined)"),
    ("Tasks状态", "Tasks state"),
    ("Save最近Complete的任务历史", "Save recently completed task history"),
    ("YesNo显示历史记录", "Whether to show history"),
    ("从localStorage加载Completed任务历史", "Load completed task history from localStorage"),
    ("只保留最近24小时内Complete的任务", "Keep only tasks completed within the last 24 hours"),
    ("Save清理后的历史", "Save cleaned history"),
    ("加载Completed任务历史Failed:", "Failed to load completed task history:"),
    ("SaveCompleted任务历史到localStorage", "Save completed task history to localStorage"),
    ("SaveCompleted任务历史Failed:", "Failed to save completed task history:"),
    ("UpdateCompleted任务历史", "Update completed task history"),
    ("SaveCurrent所有任务作为快照（用于下次比较）", "Save all current tasks as snapshot (for next comparison)"),
    ("如果Yes首次加载，只需要SaveCurrent任务快照", "If this is the first load, only save current task snapshot"),
    ("找出刚Complete的任务（之前存在但现在不存在的）", "Find just-completed tasks (previously existed but now gone)"),
    ("只要任务从列表中消失了，就认为它Completed", "Once a task disappears from the list, consider it completed"),
    ("将刚Complete的任务添加到历史中", "Add just-completed tasks to history"),
    ("检查YesNo已存在（避免重复添加）", "Check if already exists (to avoid duplicate addition)"),
    ("如果Task status不Yes最终状态，标记为completed", "If task status is not a terminal state, mark as completed"),
    ("Untitled任务", "Untitled task"),
    ("限制历史记录数量（最多保留50条）", "Limit history count (keep at most 50 entries)"),
    ("加载Task list", "Load task list"),
    ("并行加载Running的任务和Completed的任务历史", "Parallel load running tasks and completed task history"),
    ("如果API不存在，Backnull", "If API does not exist, return null"),
    # ── router.js ─────────────────────────────────────────────────────────────
    ("page面Router管理", "Page router management"),
    ("chat、Vulnerabilitiespage在切换时保留Current hash 上的查询串（如 ?conversation= / ?conversation_id=）", "chat and Vulnerabilities pages retain the current hash query string (e.g. ?conversation= / ?conversation_id=) on switch"),
    ("同一事件循环内先遮住Default新Chat状态，避免网络请求Back前闪出\"No project\"。", "Within the same event loop, first mask the default new chat state to avoid flashing 'No project' before the network request returns."),
    ("Go to指定Chat: 单次切page + 单次加载，避免 hashchange 与手动 load 重复触发导致闪烁", "Go to specified chat: single page switch + single load, to avoid hashchange and manual load triggering twice and causing flicker"),
    ("初始化Router", "Initialize router"),
    ("从URL hash读取page面（如果有）", "Read page from URL hash (if present)"),
    ("Default显示Dashboard", "Show dashboard by default"),
    ("切换page面", "Switch page"),
    ("导航点击会修改 hash，随后浏览器still会触发 hashchange。", "Navigation click modifies the hash; the browser will still fire hashchange afterward."),
    ("同一page面已经Activate时不再重复初始化，避免接口重复请求和page面二次重绘。", "When the same page is already active, do not re-initialize to avoid duplicate API requests and re-rendering."),
    ("隐藏所有page面", "Hide all pages"),
    ("显示目标page面", "Show target page"),
    ("Update导航状态", "Update navigation state"),
    ("page面特定的初始化", "Page-specific initialization"),
    ("Remove所有活动状态", "Remove all active states"),
    ("设置活动状态", "Set active state"),
    ("MCP子菜单items", "MCP submenu items"),
    ("ExpandMCP子菜单", "Expand MCP submenu"),
    ("知识子菜单items", "Knowledge submenu items"),
    # ── i18n.js ───────────────────────────────────────────────────────────────
    ("前端国际化初始化（基于 i18next 浏览器Version）", "Frontend i18n initialization (based on i18next browser version)"),
    ("供 bootstrap 等逻辑等待: 避免 chat 在 t() 未就绪时用Chinese硬编码渲染，导致与Language标签不一致", "For bootstrap and similar logic to await: prevents chat from hard-coding Chinese rendering when t() is not ready, avoiding inconsistency with language labels"),
    ("None法读取Language设置:", "Failed to read language setting:"),
    ("加载Language包Failed:", "Failed to load language pack:"),
    ("加载Language包Abnormal:", "Language pack load error:"),
    ("缺键时保留模板中的后备文案，避免page面直接显示 assets.project 一类内部键名。", "Keep fallback text from template when key is missing, to avoid the page displaying internal key names like assets.project."),
    ("仅当元素None子元素（仅文本或Empty）时才替换文本，避免覆盖卡片内的数字、子节点等; input/textarea 永不设置 textContent", "Only replace text when element has no child elements (text-only or empty), to avoid overwriting numbers or child nodes inside cards; input/textarea never has textContent set"),
    ("Chat输入框: 若 value 与 placeholder 相同，Clear value 以便正确显示占位Hint", "Chat input: if value equals placeholder, clear value to correctly show placeholder hint"),
    ("Update html lang 属性", "Update html lang attribute"),
    ("None法SaveLanguage设置:", "Failed to save language setting:"),
    ("i18next 未加载，Skip前端国际化初始化", "i18next not loaded, skipping frontend i18n initialization"),
    ("Export全局函数供Other脚本调用（支持插值参数，如 _t('key', { count: 2 })）", "Export global function for other scripts (supports interpolation params, e.g. _t('key', { count: 2 }))"),
    ("Language switch下拉支持", "Language switch dropdown support"),
    ("若 chat 已在 i18n Complete前用后备Chinese渲染了System就绪消息，这里按CurrentLanguage纠正一次", "If chat already rendered the system-ready message with fallback Chinese before i18n completed, correct it once using current language"),
    ("i18n 初始化在 DOM Ready 后Execute", "i18n initialization executes after DOM Ready"),
    ("初始化国际化Failed:", "Failed to initialize i18n:"),
    # ── chat-scroll.js ────────────────────────────────────────────────────────
    ("主Chat区智能粘底滚动: 流式Output时Auto跟随，用户上滑阅读时不抢焦点。", "Main chat area smart sticky-scroll: auto-follows during streaming output, does not grab focus when user scrolls up to read."),
    ("主 POST 流（sendMessage）与Refresh后 task-events 补流Total用同一策略。", "The main POST stream (sendMessage) and the task-events supplemental stream after refresh share the same strategy."),
    ("距底部在此范围内才继续Auto跟随（宜小，避免\"差一点也被拽回去\"）", "Only continue auto-following when within this range from the bottom (should be small, to avoid 'almost there, pulled back')"),
    ("只有真正到达底部才Resume跟随; 2px 用于兼容高分屏的亚像素滚动。", "Only resume following when truly at the bottom; 2px accounts for sub-pixel scrolling on high-DPI screens."),
    ("到达此范围视为位于最后一轮", "Arriving within this range is considered to be at the last round"),
    ("用户上滑后的短暂锁，防止 SSE 与 scroll 事件竞态抢滚动", "Short lock after user scrolls up, to prevent SSE and scroll events from racing"),
    ("RefreshResume会跨越历史消息、过程Details、字体与流订阅等多轮异步布局。", "Refresh/resume will span multiple async layout rounds including history messages, process details, fonts and stream subscriptions."),
    ("用户脱离跟随后，下方YesNo有未读的新Output（不按 SSE 次数计）", "After user detaches from following, whether there is unread new output below (not counted by SSE frequency)"),
    ("最近一次由用户发起的滚动意图; 布局变化或脚本滚动不得据此Resume粘底。", "Most recent scroll intent initiated by the user; layout changes or script scrolls must not use this to resume sticky-bottom."),
    ("每条User message开始一轮，直到下一条User message前的Assistant message都归入该轮。", "Each user message starts a round; all assistant messages before the next user message belong to that round."),
    ("第 ", "Round "),
    (" 轮", ""),
    ("正在处理…", "Processing…"),
    ("新建Chat在后端Back conversationId 前，两边都为Empty，仍属于Current界面。", "Before the backend returns conversationId for a new chat, both sides are empty and still belong to the current interface."),
    ("只有Current可见Chat的主 POST 流 / task-events 补流才视为「正在Output」", "Only the main POST stream / task-events supplemental stream of the currently visible chat is considered 'currently outputting'"),
    ("已在底部时Resume following（解决: 手动滚到底但 scrollMode 仍为 detached）", "Resume following when already at the bottom (fix: manually scrolled to bottom but scrollMode is still detached)"),
    ("detached Yes用户明确上滑后的阅读状态。布局变化、流式增高和模式切换", "detached is the reading state after user explicitly scrolled up. Layout changes, stream height increases and mode switches"),
    ("即使让视口暂时接近底部，也不能自行Resume; 只有用户明确向下滚到底才Resume。", "even if the viewport temporarily approaches the bottom, must not self-resume; only resumes when user explicitly scrolls to the bottom."),
    ("该按钮会在点击后立即隐藏。阻止指针事件继续冒泡，避免长历史Chat中", "This button hides immediately after click. Prevent pointer events from bubbling, to avoid in long-history chats"),
    # ── rbac.js ───────────────────────────────────────────────────────────────
    ("平台用户", "platform user"),
    ("批量任务", "batch task"),
    ("所属Project {{id}}", "Project {{id}}"),
    ("已Copy", "Copied"),
    ("尚未Assign role", "No role assigned"),
    ("请先Assign role，再配置资源授权。NoneRole时仅可访问本人创建的数据，且大部分功能不可用。", "Please assign a role first, then configure resource authorization. Without a role, only data created by oneself is accessible and most features are unavailable."),
    ("Assign rolesNow", "Assign roles now"),
    ("高级As", "advanced as"),
    ("Current成员", "Current member"),
    ("个Role", " roles"),
    ("items授权", " authorizations"),
    ("没有匹配的成员", "No matching members"),
    ("未Assign role", "No role assigned"),
    ("资源范围", "resource scope"),
    ("内置账号", "built-in account"),
    ("CurrentRole变更尚未Save，OK放弃并切换成员吗？", "Current role changes are not saved. OK to discard and switch member?"),
    ("没有匹配的Role", "No matching roles"),
    ("None法加载权限数据", "Failed to load permission data"),
    ("Refresh中…", "Refreshing…"),
    ("有效权限明细", "Effective permission details"),
    # ── vulnerability.js ──────────────────────────────────────────────────────
    ("Vulnerabilities相关功能", "Vulnerabilities-related functionality"),
    ("从地址栏 #vulnerabilities?conversation_id= / ?task_id= / ?id= 同步Filter（Notification/Chat菜单/Tasks联动）", "Sync filter from URL hash #vulnerabilities?conversation_id= / ?task_id= / ?id= (Notification/Chat menu/Tasks linkage)"),
    ("初始化Vulnerabilitiespage面", "Initialize vulnerabilities page"),
    ("从localStorage加载每page条数设置", "Load per-page count setting from localStorage"),
    ("加载VulnerabilityFilter建议Failed", "Failed to load vulnerability filter suggestions"),
    ("加载Vulnerability统计", "Load vulnerability statistics"),
    ("检查apiFetchYesNo可用", "Check if apiFetch is available"),
    ("apiFetch未定义，请确保auth.js已加载", "apiFetch is undefined, please ensure auth.js is loaded"),
    ("apiFetch未定义", "apiFetch is undefined"),
    ("获取统计Failed:", "Failed to fetch statistics:"),
    ("加载Vulnerability统计Failed:", "Failed to load vulnerability statistics:"),
    ("统计Failed不影响列表显示，只Reset统计为0", "Statistics failure does not affect list display, only reset statistics to 0"),
    ("UpdateVulnerability统计显示", "Update vulnerability statistics display"),
    ("处理Empty值情况", "Handle empty value case"),
    ("加载Vulnerability list", "Load vulnerability list"),
    ("如果指定了page码，使用page码; No则使用Currentpage码", "If a page number is specified, use it; otherwise use the current page number"),
    ("获取Vulnerability listFailed:", "Failed to fetch vulnerability list:"),
    ("判断响应格式: 新格式（有total字段）stillYes旧格式（直接Yes数组）", "Determine response format: new format (has total field) or old format (directly an array)"),
    ("旧格式: 直接Yes数组", "Old format: directly an array"),
    ("使用数组长度作为总数（可能不准确，但至少能显示分page控件）", "Use array length as total (may be inaccurate, but at least shows pagination controls)"),
    # ── workflows.js ──────────────────────────────────────────────────────────
    ("开始", "start"),
    ("工具", "tool"),
    ("条件", "condition"),
    ("审批", "approval"),
    ("结束", "end"),
    ("子域名", "subdomain"),
    ("端口", "port scan"),
    ("Vulnerability扫描", "vulnerability scan"),
    ("目录", "directory"),
    ("路径", "path"),
    ("暴露page面", "exposed pages"),
    ("证书", "certificate"),
    ("云", "cloud"),
    ("配置审计", "config audit"),
    ("容器", "container"),
    ("镜像", "image"),
    ("情报", "intelligence"),
    ("威胁情报", "threat intelligence"),
    ("子域名发现", "subdomain discovery"),
    ("端口扫描", "port scan"),
    ("证书与域名线索收集", "certificate and domain clue collection"),
    ("云配置审计", "cloud configuration audit"),
    ("容器Safe检查", "container security check"),
    ("汇聚策略", "join strategy"),
    ("多个上游进入同一节点时如何Generate previous。", "How to generate previous when multiple upstreams enter the same node."),
    ("条件分支", "conditional branch"),
    ("审核", "review"),
    ("负责人", "responsible person"),
    ("人工", "manual"),
    ("报告", "report"),
    ("汇总", "summary"),
    ("任务", "task"),
    ("工单", "ticket"),
    ("如果", "if"),
    ("发现", "found"),
    ("存在", "exists"),
    ("Add", "add"),
    ("No则", "otherwise"),
    ("根据用户需求ExecuteSafe流程Step，并Output结构化结果: ", "Execute security process steps based on user requirements and output structured results: "),
    (" 未匹配到Enabled工具，已Generate Agent 草稿节点。", " did not match any enabled tools; an agent draft node was generated."),
    ("YesNo需要高风险处置", "Whether high-risk action is required"),
    ("YesNo满足触发条件", "Whether trigger condition is met"),
    ("Output报告", "output report"),
    ("请ConfirmYesNo允许继续Execute高风险处置: ", "Please confirm whether to allow continuing high-risk action execution: "),
    # ── skills.js ─────────────────────────────────────────────────────────────
    ("Skills管理相关功能", "Skills management functionality"),
    ("每page20条（Default值，实际从localStorage读取）", "20 per page (default value, actually read from localStorage)"),
    ("获取Save的每page显示数量", "Get saved per-page display count"),
    ("None法从localStorage读取分page设置:", "Failed to read pagination setting from localStorage:"),
    ("初始化分page设置", "Initialize pagination settings"),
    ("加载skills列表（支持分page）", "Load skills list (with pagination support)"),
    ("如果没有指定pageSize，使用Save的值或Default值", "If no pageSize specified, use saved value or default"),
    ("Update pagination state（确保使用正确的pageSize）", "Update pagination state (ensure correct pageSize is used)"),
    ("ClearSearch关键词（Normal分page加载时）", "Clear search keyword (on normal paginated load)"),
    ("构建URL（支持分page）", "Build URL (with pagination support)"),
    ("加载skills列表Failed:", "Failed to load skills list:"),
    ("渲染skills列表", "Render skills list"),
    ("后端已经CompleteSearch过滤，直接使用skillsList", "Backend has already completed search filtering, use skillsList directly"),
    ("Search时隐藏分page", "Hide pagination during search"),
    ("确保列表容器可以滚动，分page栏可见", "Ensure list container is scrollable and pagination bar is visible"),
    ("使用 setTimeout 确保 DOM UpdateComplete后再检查", "Use setTimeout to ensure check happens after DOM update completes"),
    ("确保分page栏可见", "Ensure pagination bar is visible"),
    ("渲染分page组件（参考MCPpage面样式）", "Render pagination component (referencing MCP page style)"),
    ("即使只有一page也显示分pageInfo（参考MCP样式）", "Show pagination info even for a single page (referencing MCP style)"),
    ("计算显示范围", "Calculate display range"),
    ("左侧: 显示范围Info和每page数量选择器（参考MCP样式）", "Left: display range info and per-page count selector (referencing MCP style)"),
    ("右侧: 分page按钮（参考MCP样式: First page、Previous、第X/Ypage、Next、Last page）", "Right: pagination buttons (referencing MCP style: first page, previous, page X/Y, next, last page)"),
    ("确保分page组件与列表内容区域对齐（不包括滚动条）", "Ensure pagination component aligns with list content area (excluding scrollbar)"),
    ("确保分page容器始终可见", "Ensure pagination container is always visible"),
    ("获取列表的实际内容宽度（不包括滚动条）", "Get actual content width of the list (excluding scrollbar)"),
    # ── storage.js ────────────────────────────────────────────────────────────
    ("文件管理相关功能", "File management functionality"),
    ("文件列表加载Failed:", "Failed to load file list:"),
    ("文件Delete成功", "File deleted successfully"),
    ("文件DeleteFailed:", "Failed to delete file:"),
    ("文件夹CreateFailed:", "Failed to create folder:"),
    ("文件夹Create成功", "Folder created successfully"),
    # ── terminal.js ───────────────────────────────────────────────────────────
    ("终端功能相关", "Terminal functionality"),
    ("Terminal连接Failed:", "Failed to connect terminal:"),
    ("Terminal已断开", "Terminal disconnected"),
    ("Terminal重连中...", "Terminal reconnecting..."),
    ("Terminal连接Success", "Terminal connected successfully"),
    # ── c2.js ─────────────────────────────────────────────────────────────────
    ("C2功能相关", "C2 functionality"),
    ("监听器列表加载Failed:", "Failed to load listener list:"),
    ("会话列表加载Failed:", "Failed to load session list:"),
    ("命令Execute结果:", "Command execution result:"),
    # ── audit.js ──────────────────────────────────────────────────────────────
    ("审计日志相关功能", "Audit log functionality"),
    ("审计日志加载Failed:", "Failed to load audit logs:"),
    # ── wechat-robot.js ───────────────────────────────────────────────────────
    ("微信机器人相关功能", "WeChat bot functionality"),
    ("机器人状态更新Failed:", "Failed to update bot status:"),
    ("消息发送Failed:", "Failed to send message:"),
    # ── hitl.js ───────────────────────────────────────────────────────────────
    ("人机协同相关功能", "Human-in-the-loop functionality"),
    ("审批列表加载Failed:", "Failed to load approval list:"),
    ("审批操作Failed:", "Approval operation failed:"),
    # ── notifications.js ──────────────────────────────────────────────────────
    ("通知相关功能", "Notifications functionality"),
    ("通知加载Failed:", "Failed to load notifications:"),
    ("通知标记已读Failed:", "Failed to mark notification as read:"),
    # ── info-collect.js ───────────────────────────────────────────────────────
    ("信息收集相关功能", "Information collection functionality"),
    ("收集任务加载Failed:", "Failed to load collection task:"),
    ("收集结果加载Failed:", "Failed to load collection result:"),
    # ── projects.js ───────────────────────────────────────────────────────────
    ("Projects相关功能", "Projects functionality"),
    ("项目列表加载Failed:", "Failed to load project list:"),
    ("项目Create成功", "Project created successfully"),
    ("项目CreateFailed:", "Failed to create project:"),
    # ── api-docs.js ───────────────────────────────────────────────────────────
    ("接口文档相关功能", "API documentation functionality"),
    ("接口列表加载Failed:", "Failed to load API list:"),
    # ── fact-graph.js ─────────────────────────────────────────────────────────
    ("知识图谱相关功能", "Knowledge graph functionality"),
    ("图谱加载Failed:", "Failed to load graph:"),
    # ── sanitize-markdown.js ──────────────────────────────────────────────────
    ("Markdown处理相关功能", "Markdown processing functionality"),
    ("渲染Failed:", "Render failed:"),
    # ── builtin-tools.js ──────────────────────────────────────────────────────
    ("内置工具相关功能", "Built-in tools functionality"),
    ("工具列表加载Failed:", "Failed to load tool list:"),
    # ── modal.js / chat-files.js ──────────────────────────────────────────────
    ("模态框相关功能", "Modal functionality"),
    ("文件选择相关功能", "File selection functionality"),
    # ── general fragment cleanup ──────────────────────────────────────────────
    ("None法", "cannot "),
    ("Yes外部", "is external"),
    ("Yes内部", "is internal"),
    ("YesNo", "whether "),
    ("Yes ", "is "),
    ("No则", "otherwise "),
    ("None", "no "),
    ("Empty", "empty"),
    ("Hint", "hint"),
    ("Refresh", "refresh"),
    ("Update", "update"),
    ("Remove", "remove"),
    ("Clear", "clear"),
    ("Resume", "restore"),
    ("Save", "save"),
    ("Send", "send"),
    ("Copy", "copy"),
    ("Delete", "delete"),
    ("Create", "create"),
    ("Edit", "edit"),
    ("View", "view"),
    ("Expand", "expand"),
    ("Collapse", "collapse"),
    ("Filter", "filter"),
    ("Search", "search"),
    ("Import", "import"),
    ("Export", "export"),
    ("Upload", "upload"),
    ("Download", "download"),
    ("Still", "still"),
    ("still", "still"),
    ("Confirm", "confirm"),
    ("Back", "return"),
    ("Stop", "stop"),
    ("Start", "start"),
    ("Run", "run"),
    ("Execute", "execute"),
    ("Complete", "complete"),
    ("Failed", "failed"),
    ("Success", "success"),
    ("Error", "error"),
    ("Approve", "approve"),
    ("Reject", "reject"),
    ("Enable", "enable"),
    ("Disable", "disable"),
    ("Active", "active"),
    ("Inactive", "inactive"),
    ("Normal", "normal"),
    ("Abnormal", "abnormal"),
    ("Current", "current"),
    ("Latest", "latest"),
    ("Default", "default"),
    ("All", "all"),
    ("Other", "other"),
    ("More", "more"),
    ("Skip", "skip"),
    ("Ignore", "ignore"),
    ("Bind", "bind"),
    ("Unbind", "unbind"),
    ("Stable", "stable"),
    ("Notification", "notification"),
    ("Waiting", "waiting"),
    ("Activate", "activate"),
    ("page面", " page"),
    ("page", " page"),
    ("items", " items"),
    ("Info", " info"),
    ("More items目", " target"),
    ("more items目", " target"),
    ("Target", "target"),
    ("Vulnerability", "vulnerability"),
    ("Vulnerabilities", "vulnerabilities"),
    ("Output", "output"),
    ("Input", "input"),
    ("项", " items"),
    ("条", " records"),
    ("秒", " sec"),
    ("分钟", " minutes"),
    ("小时", " hours"),
    ("天", " days"),
]

# Sort longest-first to avoid partial replacements
PHRASES.sort(key=lambda x: len(x[0]), reverse=True)

def replace_all(content):
    for cn, en in PHRASES:
        if cn in content:
            content = content.replace(cn, en)
    return content

def translate_file(path):
    text = open(path, encoding='utf-8').read()
    before = len(re.findall(r'[\u4e00-\u9fff\u3400-\u4dbf\uff00-\uffef\u2e80-\u2eff\u3000-\u303f]', text))
    if before == 0:
        return 0, 0
    new_text = replace_all(text)
    after = len(re.findall(r'[\u4e00-\u9fff\u3400-\u4dbf\uff00-\uffef\u2e80-\u2eff\u3000-\u303f]', new_text))
    if new_text != text:
        open(path, 'w', encoding='utf-8').write(new_text)
    return before, after

total_before = 0
total_after = 0

for root, dirs, files in os.walk('web/static/js'):
    dirs[:] = [d for d in dirs if d != 'vendor']
    for f in sorted(files):
        if not f.endswith('.js'):
            continue
        path = os.path.join(root, f)
        before, after = translate_file(path)
        if before > 0:
            total_before += before
            total_after += after
            reduced = before - after
            if reduced > 0:
                print(f'  {before:5d} -> {after:4d}  (-{reduced:4d})  {path}')

print(f'\nTotal: {total_before} -> {total_after} ({total_before - total_after} translated, {total_after} remaining)')
