#!/usr/bin/env python3
"""
Translate all Chinese text in web/static/js/*.js and *.test.cjs files.
Uses a comprehensive pattern-based replacement approach.
"""
import re, os, json, sys

# ── Load en-US.json for i18n key lookups ──────────────────────────────────
with open("web/static/i18n/en-US.json", "r", encoding="utf-8-sig") as f:
    en_i18n = json.load(f)

def get_en(key):
    parts = key.split(".")
    d = en_i18n
    for p in parts:
        if isinstance(d, dict) and p in d:
            d = d[p]
        else:
            return None
    return d if isinstance(d, str) else None

# ── Replace i18n key references that appear as fallback strings in JS ─────
def replace_i18n_in_js(content):
    """Replace patterns like i18n('key') or t('key') fallback strings."""
    # Pattern: some string in JS that matches an i18n key value in Chinese
    # We do a reverse lookup: find Chinese strings that equal a known i18n value
    def flatten_i18n(d, prefix=""):
        result = {}
        for k, v in d.items():
            full_key = f"{prefix}.{k}" if prefix else k
            if isinstance(v, dict):
                result.update(flatten_i18n(v, full_key))
            elif isinstance(v, str) and re.search(r'[\u4e00-\u9fff]', v):
                result[v] = full_key  # Chinese value -> key
        return result
    # Not using this for now — we use direct replacement
    return content

# ── Master replacement list ───────────────────────────────────────────────
# Format: (Chinese, English)
# Longer strings first to avoid partial replacements
REPLACEMENTS = [
    # ── Long phrases / sentences first ──────────────────────────────────
    ("确定要删除这个规则吗？", "Are you sure you want to delete this rule?"),
    ("确定要删除这条记录吗？", "Are you sure you want to delete this record?"),
    ("暂无可用工具", "No tools available"),
    ("工具调用记录为空", "No tool call records"),
    ("请输入工具名称", "Please enter a tool name"),
    ("请输入参数", "Please enter parameters"),
    ("规则验证通过", "Rule validation passed"),
    ("规则验证失败", "Rule validation failed"),
    ("没有匹配的规则", "No matching rules"),
    ("请至少选择一条记录", "Please select at least one record"),
    ("请输入正则表达式", "Please enter a regular expression"),
    ("正则表达式无效", "Invalid regular expression"),
    ("文件上传失败", "File upload failed"),
    ("文件格式不支持", "File format not supported"),
    ("文件大小超出限制", "File size exceeds limit"),
    ("网络连接失败", "Network connection failed"),
    ("会话不存在", "Session does not exist"),
    ("对话不存在", "Conversation does not exist"),
    ("任务不存在", "Task does not exist"),
    ("获取数据失败", "Failed to fetch data"),
    ("获取列表失败", "Failed to fetch list"),
    ("加载数据失败", "Failed to load data"),
    ("加载列表失败", "Failed to load list"),
    ("连接失败", "Connection failed"),
    ("连接已断开", "Connection disconnected"),
    ("正在连接", "Connecting"),
    ("连接成功", "Connected"),
    ("已断开连接", "Disconnected"),
    ("发送失败", "Send failed"),
    ("发送成功", "Sent successfully"),
    ("接收失败", "Receive failed"),
    ("解析失败", "Parse failed"),
    ("解析错误", "Parse error"),
    ("格式错误", "Format error"),
    ("参数错误", "Parameter error"),
    ("参数不能为空", "Parameter cannot be empty"),
    ("不能为空", "Cannot be empty"),
    ("密码不能为空", "Password cannot be empty"),
    ("用户名不能为空", "Username cannot be empty"),
    ("请输入用户名", "Please enter a username"),
    ("请输入密码", "Please enter a password"),
    ("登录成功", "Logged in successfully"),
    ("登录失败", "Login failed"),
    ("注销成功", "Logged out successfully"),
    ("权限不足", "Insufficient permissions"),
    ("没有权限", "No permission"),
    ("请先登录", "Please log in first"),
    ("会话已过期", "Session expired"),
    ("Token已过期", "Token expired"),
    ("验证失败", "Verification failed"),
    ("已存在", "Already exists"),
    ("不存在", "Does not exist"),
    ("创建成功", "Created successfully"),
    ("创建失败", "Creation failed"),
    ("更新成功", "Updated successfully"),
    ("更新失败", "Update failed"),
    ("添加成功", "Added successfully"),
    ("添加失败", "Add failed"),
    ("移除成功", "Removed successfully"),
    ("移除失败", "Remove failed"),
    ("导入成功", "Import successful"),
    ("导入失败", "Import failed"),
    ("导出成功", "Export successful"),
    ("导出失败", "Export failed"),
    ("下载失败", "Download failed"),
    ("上传成功", "Upload successful"),
    ("上传失败", "Upload failed"),
    ("构建成功", "Build successful"),
    ("构建失败", "Build failed"),
    ("构建中", "Building"),
    ("同步成功", "Sync successful"),
    ("同步失败", "Sync failed"),
    ("重置成功", "Reset successful"),
    ("重置失败", "Reset failed"),
    ("清空成功", "Cleared successfully"),
    ("清空失败", "Clear failed"),
    ("索引构建成功", "Index built successfully"),
    ("索引构建失败", "Index build failed"),
    ("索引重建中", "Rebuilding index"),
    ("正在构建", "Building"),
    ("正在同步", "Syncing"),
    ("正在重置", "Resetting"),
    ("正在删除", "Deleting"),
    ("正在保存", "Saving"),
    ("正在上传", "Uploading"),
    ("正在下载", "Downloading"),
    ("正在导入", "Importing"),
    ("正在导出", "Exporting"),
    ("正在处理", "Processing"),
    ("处理中", "Processing"),
    ("请稍候", "Please wait"),
    ("请稍等", "Please wait"),
    ("暂无记录", "No records"),
    ("暂无数据", "No data"),
    ("暂无内容", "No content"),
    ("暂无结果", "No results"),
    ("暂无项目", "No projects"),
    ("暂无对话", "No conversations"),
    ("暂无任务", "No tasks"),
    ("暂无漏洞", "No vulnerabilities"),
    ("暂无资产", "No assets"),
    ("暂无技能", "No skills"),
    ("暂无角色", "No roles"),
    ("暂无知识", "No knowledge items"),
    ("暂无工具", "No tools"),
    ("暂无消息", "No messages"),
    ("暂无通知", "No notifications"),
    ("暂无事件", "No events"),
    ("暂无日志", "No logs"),
    ("暂无历史", "No history"),
    ("暂无文件", "No files"),
    ("暂无连接", "No connections"),
    ("暂无会话", "No sessions"),
    ("暂无监听器", "No listeners"),
    ("暂无 Payload", "No payloads"),
    ("暂无 Profile", "No profiles"),
    ("暂无工作流", "No workflows"),
    ("暂无步骤", "No steps"),
    ("暂无执行记录", "No execution records"),
    ("暂无检索记录", "No retrieval records"),
    ("暂无审计日志", "No audit logs"),
    ("是否确认删除", "Are you sure you want to delete"),
    ("是否确定删除", "Are you sure you want to delete"),
    ("是否确认", "Are you sure"),
    ("此操作不可撤销", "This action cannot be undone"),
    ("操作不可逆", "This action is irreversible"),
    ("这条记录将被永久删除", "This record will be permanently deleted"),
    ("确定要清空", "Are you sure you want to clear"),
    ("确定要重置", "Are you sure you want to reset"),
    ("确定要停止", "Are you sure you want to stop"),
    ("确定要终止", "Are you sure you want to terminate"),
    ("确定要取消", "Are you sure you want to cancel"),
    ("确定要删除吗", "Are you sure you want to delete?"),
    ("确定要清空所有审计日志吗", "Are you sure you want to clear all audit logs?"),
    ("确定要清空所有记录吗", "Are you sure you want to clear all records?"),
    ("确定要删除选中的记录吗", "Are you sure you want to delete the selected records?"),
    ("确定删除", "Confirm delete"),
    ("确定清空", "Confirm clear"),
    ("批量删除", "Batch delete"),
    ("批量编辑", "Batch edit"),
    ("批量操作", "Batch operation"),
    ("全选", "Select all"),
    ("取消全选", "Deselect all"),
    ("已选中", "Selected"),
    ("选中", "Selected"),
    ("条数据", "records"),
    ("条记录", "records"),
    ("条消息", "messages"),
    ("共选中", "Total selected"),
    ("已选择", "Selected"),
    ("选择全部结果", "Select all results"),
    ("清除选择", "Clear selection"),
    ("没有选中任何项", "No items selected"),
    ("没有选中任何记录", "No records selected"),
    ("请至少选择一项", "Please select at least one item"),
    ("请先选择", "Please select first"),
    ("正在加载更多", "Loading more"),
    ("加载更多", "Load more"),
    ("没有更多数据", "No more data"),
    ("到底了", "No more items"),
    ("第一页", "First page"),
    ("最后一页", "Last page"),
    ("上一页", "Previous"),
    ("下一页", "Next"),
    ("页码", "Page"),
    ("共 {0} 页", "Total {0} pages"),
    ("每页显示", "Per page"),
    ("跳转到", "Go to"),
    ("输入页码", "Enter page number"),
    ("搜索结果", "Search results"),
    ("无搜索结果", "No search results"),
    ("搜索中", "Searching"),
    ("搜索工具", "Search tools"),
    ("搜索项目", "Search projects"),
    ("搜索资产", "Search assets"),
    ("搜索漏洞", "Search vulnerabilities"),
    ("搜索知识", "Search knowledge"),
    ("搜索角色", "Search roles"),
    ("搜索技能", "Search skills"),
    ("搜索对话", "Search conversations"),
    ("搜索任务", "Search tasks"),
    ("请输入搜索关键词", "Please enter a search keyword"),
    ("请输入关键词", "Please enter a keyword"),
    ("请输入名称", "Please enter a name"),
    ("请输入描述", "Please enter a description"),
    ("请输入内容", "Please enter content"),
    ("请输入标题", "Please enter a title"),
    ("请输入URL", "Please enter a URL"),
    ("请输入IP地址", "Please enter an IP address"),
    ("请输入端口", "Please enter a port"),
    ("请输入用户名或密码", "Please enter username or password"),
    ("字段不能为空", "Field cannot be empty"),
    ("必填项", "Required"),
    ("可选", "Optional"),
    ("未填写", "Not filled"),
    ("未设置", "Not set"),
    ("已设置", "Set"),
    ("未知", "Unknown"),
    ("未命名", "Untitled"),
    ("无标题", "No title"),
    ("无描述", "No description"),
    ("无内容", "No content"),
    ("无", "None"),
    ("空", "Empty"),
    ("是", "Yes"),
    ("否", "No"),
    ("开启", "Enable"),
    ("关闭", "Disable"),
    ("启用", "Enable"),
    ("停用", "Disable"),
    ("激活", "Activate"),
    ("禁用", "Disable"),
    ("在线", "Online"),
    ("离线", "Offline"),
    ("活跃", "Active"),
    ("非活跃", "Inactive"),
    ("运行中", "Running"),
    ("已停止", "Stopped"),
    ("已暂停", "Paused"),
    ("已完成", "Completed"),
    ("已取消", "Cancelled"),
    ("已失败", "Failed"),
    ("已超时", "Timed out"),
    ("等待中", "Waiting"),
    ("排队中", "Queued"),
    ("已拦截", "Blocked"),
    ("已终止", "Terminated"),
    ("已拒绝", "Rejected"),
    ("已通过", "Approved"),
    ("已忽略", "Ignored"),
    ("待处理", "Open"),
    ("待审批", "Pending approval"),
    ("待审计", "Pending review"),
    ("审批中", "Under review"),
    ("已审批", "Reviewed"),
    ("已修复", "Fixed"),
    ("已确认", "Confirmed"),
    ("误报", "False positive"),
    ("待确认", "Tentative"),
    ("严重", "Critical"),
    ("高危", "High"),
    ("中危", "Medium"),
    ("低危", "Low"),
    ("信息", "Info"),
    ("高", "High"),
    ("中", "Medium"),
    ("低", "Low"),
    ("默认", "Default"),
    ("系统默认", "System default"),
    ("自定义", "Custom"),
    ("内置", "Built-in"),
    ("外部", "External"),
    ("全局", "Global"),
    ("本地", "Local"),
    ("远程", "Remote"),
    ("手动", "Manual"),
    ("自动", "Auto"),
    ("实时", "Real-time"),
    ("离线模式", "Offline mode"),
    ("暗色模式", "Dark mode"),
    ("亮色模式", "Light mode"),
    ("系统主题", "System theme"),
    ("主题", "Theme"),
    ("语言", "Language"),
    ("中文", "Chinese"),
    ("英文", "English"),
    # Chat / conversation
    ("新任务", "New task"),
    ("新对话", "New conversation"),
    ("发送消息", "Send message"),
    ("输入消息", "Enter message"),
    ("正在输入", "Typing"),
    ("停止生成", "Stop generating"),
    ("重新生成", "Regenerate"),
    ("重试", "Retry"),
    ("继续", "Continue"),
    ("暂停", "Pause"),
    ("恢复", "Resume"),
    ("停止", "Stop"),
    ("终止", "Terminate"),
    ("执行", "Execute"),
    ("运行", "Run"),
    ("开始", "Start"),
    ("结束", "End"),
    ("完成", "Complete"),
    ("提交审批", "Submit for approval"),
    ("通过", "Approve"),
    ("拒绝", "Reject"),
    ("跳过", "Skip"),
    ("忽略", "Ignore"),
    ("标记已读", "Mark as read"),
    ("标记全部已读", "Mark all as read"),
    ("清空通知", "Clear notifications"),
    ("全部已读", "All read"),
    ("未读", "Unread"),
    ("已读", "Read"),
    ("新消息", "New message"),
    ("新通知", "New notification"),
    ("消息", "Message"),
    ("通知", "Notification"),
    ("事件", "Event"),
    ("日志", "Log"),
    ("历史", "History"),
    ("记录", "Record"),
    ("详情", "Details"),
    ("详细信息", "Details"),
    ("概览", "Overview"),
    ("统计", "Statistics"),
    ("分析", "Analysis"),
    ("报告", "Report"),
    ("摘要", "Summary"),
    ("描述", "Description"),
    ("标题", "Title"),
    ("名称", "Name"),
    ("类型", "Type"),
    ("状态", "Status"),
    ("级别", "Level"),
    ("优先级", "Priority"),
    ("创建时间", "Created"),
    ("更新时间", "Updated"),
    ("修改时间", "Modified"),
    ("完成时间", "Completed"),
    ("开始时间", "Start time"),
    ("结束时间", "End time"),
    ("时间", "Time"),
    ("日期", "Date"),
    ("操作", "Actions"),
    ("来源", "Source"),
    ("目标", "Target"),
    ("地址", "Address"),
    ("端口", "Port"),
    ("协议", "Protocol"),
    ("路径", "Path"),
    ("文件", "File"),
    ("文件夹", "Folder"),
    ("目录", "Directory"),
    ("大小", "Size"),
    ("权限", "Permission"),
    ("用户", "User"),
    ("角色", "Role"),
    ("标签", "Tags"),
    ("备注", "Note"),
    ("分类", "Category"),
    ("类别", "Category"),
    ("版本", "Version"),
    ("配置", "Configuration"),
    ("设置", "Settings"),
    ("系统设置", "System Settings"),
    ("高级设置", "Advanced settings"),
    ("基本设置", "Basic settings"),
    ("安全设置", "Security settings"),
    ("网络设置", "Network settings"),
    ("代理设置", "Proxy settings"),
    ("通知设置", "Notification settings"),
    ("密码", "Password"),
    ("旧密码", "Old password"),
    ("新密码", "New password"),
    ("确认密码", "Confirm password"),
    ("密码强度", "Password strength"),
    ("强", "Strong"),
    ("弱", "Weak"),
    ("中等", "Medium"),
    ("修改密码", "Change password"),
    ("重置密码", "Reset password"),
    ("忘记密码", "Forgot password"),
    ("登录", "Sign in"),
    ("退出登录", "Sign out"),
    ("注册", "Register"),
    ("账号", "Account"),
    ("用户名", "Username"),
    ("邮箱", "Email"),
    ("手机", "Phone"),
    ("昵称", "Nickname"),
    ("头像", "Avatar"),
    ("个人信息", "Profile"),
    ("修改信息", "Edit profile"),
    ("保存信息", "Save profile"),
    # Assets
    ("资产", "Asset"),
    ("资产库", "Asset library"),
    ("资产管理", "Asset management"),
    ("资产概览", "Asset overview"),
    ("IP地址", "IP address"),
    ("域名", "Domain"),
    ("端口号", "Port number"),
    ("开放端口", "Open ports"),
    ("服务", "Service"),
    ("组件", "Component"),
    ("漏洞", "Vulnerability"),
    ("漏洞管理", "Vulnerability management"),
    ("漏洞详情", "Vulnerability details"),
    ("漏洞描述", "Vulnerability description"),
    ("修复建议", "Remediation advice"),
    ("影响范围", "Impact scope"),
    ("扫描", "Scan"),
    ("扫描任务", "Scan task"),
    ("扫描状态", "Scan status"),
    ("扫描结果", "Scan results"),
    ("扫描时间", "Scan time"),
    ("扫描目标", "Scan target"),
    ("信息收集", "Info collection"),
    ("指纹识别", "Fingerprint"),
    ("服务识别", "Service detection"),
    ("端口扫描", "Port scan"),
    ("漏洞扫描", "Vulnerability scan"),
    # Tasks / workflows
    ("任务", "Task"),
    ("任务管理", "Task management"),
    ("任务详情", "Task details"),
    ("任务状态", "Task status"),
    ("任务名称", "Task name"),
    ("任务描述", "Task description"),
    ("任务类型", "Task type"),
    ("任务进度", "Task progress"),
    ("批量任务", "Batch task"),
    ("批量扫描", "Batch scan"),
    ("工作流", "Workflow"),
    ("工作流管理", "Workflow management"),
    ("工作流详情", "Workflow details"),
    ("步骤", "Step"),
    ("节点", "Node"),
    ("连接", "Connection"),
    # Knowledge
    ("知识库", "Knowledge base"),
    ("知识管理", "Knowledge management"),
    ("知识项", "Knowledge item"),
    ("知识检索", "Knowledge retrieval"),
    ("检索历史", "Retrieval history"),
    ("构建索引", "Build index"),
    ("重建索引", "Rebuild index"),
    ("全量重建", "Full rebuild"),
    ("增量构建", "Incremental build"),
    # Roles / RBAC
    ("角色管理", "Role management"),
    ("权限管理", "Permission management"),
    ("用户管理", "User management"),
    ("成员管理", "Member management"),
    ("访问控制", "Access control"),
    ("平台权限", "Platform permissions"),
    ("全局权限", "Global permissions"),
    ("资源权限", "Resource permissions"),
    ("读取权限", "Read permission"),
    ("写入权限", "Write permission"),
    ("管理员", "Administrator"),
    ("普通用户", "Regular user"),
    ("平台管理", "Platform admin"),
    # MCP / Tools
    ("工具", "Tool"),
    ("工具配置", "Tool configuration"),
    ("工具管理", "Tool management"),
    ("工具调用", "Tool call"),
    ("工具执行", "Tool execution"),
    ("执行记录", "Execution records"),
    ("执行历史", "Execution history"),
    ("执行详情", "Execution details"),
    ("执行结果", "Execution result"),
    ("执行状态", "Execution status"),
    ("执行成功", "Execution successful"),
    ("执行失败", "Execution failed"),
    ("执行超时", "Execution timeout"),
    ("执行中", "Executing"),
    ("已执行", "Executed"),
    ("孤儿任务", "Orphaned task"),
    ("外部MCP", "External MCP"),
    ("内置工具", "Built-in tool"),
    ("工具搜索", "Tool search"),
    ("状态筛选", "Status filter"),
    ("状态监控", "Status monitor"),
    ("MCP管理", "MCP management"),
    ("MCP监控", "MCP monitor"),
    ("MCP状态", "MCP status"),
    ("连接状态", "Connection status"),
    ("健康检查", "Health check"),
    # C2
    ("监听器", "Listener"),
    ("监听地址", "Listen address"),
    ("监听端口", "Listen port"),
    ("会话管理", "Session management"),
    ("会话列表", "Session list"),
    ("会话详情", "Session details"),
    ("活跃会话", "Active sessions"),
    ("在线会话", "Online sessions"),
    ("离线会话", "Offline sessions"),
    ("上线时间", "Online since"),
    ("最后活跃", "Last active"),
    ("心跳", "Heartbeat"),
    ("信标", "Beacon"),
    ("载荷", "Payload"),
    ("生成载荷", "Generate payload"),
    ("流量伪装", "Traffic disguise"),
    ("Profile", "Profile"),
    ("C2管理", "C2 management"),
    ("命令执行", "Command execution"),
    ("进程列表", "Process list"),
    ("文件管理", "File management"),
    ("端口转发", "Port forwarding"),
    ("屏幕截图", "Screenshot"),
    ("键盘记录", "Keylog"),
    ("权限提升", "Privilege escalation"),
    ("横向移动", "Lateral movement"),
    # WebShell
    ("WebShell管理", "WebShell management"),
    ("添加连接", "Add connection"),
    ("连接名称", "Connection name"),
    ("连接地址", "Connection address"),
    ("连接成功", "Connected successfully"),
    ("连接断开", "Connection closed"),
    ("命令输出", "Command output"),
    ("执行命令", "Execute command"),
    ("文件浏览", "File browser"),
    ("上传文件", "Upload file"),
    ("下载文件", "Download file"),
    # HITL
    ("人机协同", "Human-AI collaboration"),
    ("审批", "Approval"),
    ("审批方", "Approver"),
    ("审批日志", "Approval log"),
    ("审批策略", "Approval policy"),
    ("白名单", "Whitelist"),
    ("黑名单", "Blacklist"),
    ("工具白名单", "Tool whitelist"),
    ("免审批", "No approval needed"),
    ("审计", "Audit"),
    ("审计日志", "Audit log"),
    ("审计策略", "Audit policy"),
    ("审计 Agent", "Audit Agent"),
    ("人工审批", "Manual approval"),
    ("审批模式", "Approval mode"),
    ("审查编辑", "Review & edit"),
    ("拒绝原因", "Rejection reason"),
    ("拒绝说明", "Rejection note"),
    ("审批超时", "Approval timeout"),
    ("等待审批", "Awaiting approval"),
    ("人机协同已关闭", "Human-AI collaboration disabled"),
    # Settings
    ("通道配置", "Channel configuration"),
    ("AI通道", "AI channel"),
    ("模型配置", "Model configuration"),
    ("推理模式", "Reasoning mode"),
    ("推理强度", "Reasoning effort"),
    ("系统提示词", "System prompt"),
    ("温度", "Temperature"),
    ("最大Token", "Max tokens"),
    ("上下文长度", "Context length"),
    ("超时时间", "Timeout"),
    ("重试次数", "Retry count"),
    ("并发数", "Concurrency"),
    ("代理地址", "Proxy address"),
    ("API Key", "API Key"),
    ("API地址", "API base URL"),
    ("测试连接", "Test connection"),
    ("连接测试成功", "Connection test successful"),
    ("连接测试失败", "Connection test failed"),
    ("保存配置", "Save configuration"),
    ("应用配置", "Apply configuration"),
    ("配置已保存", "Configuration saved"),
    ("配置保存失败", "Configuration save failed"),
    ("配置已应用", "Configuration applied"),
    ("恢复默认", "Restore defaults"),
    ("重置配置", "Reset configuration"),
    ("当前配置", "Current configuration"),
    ("机器人设置", "Bot settings"),
    ("机器人配置", "Bot configuration"),
    ("机器人账号", "Bot account"),
    ("绑定机器人", "Bind bot"),
    ("解绑机器人", "Unbind bot"),
    ("绑定成功", "Bound successfully"),
    ("绑定失败", "Binding failed"),
    ("解绑成功", "Unbound successfully"),
    ("解绑失败", "Unbinding failed"),
    ("绑定码", "Binding code"),
    ("生成绑定码", "Generate binding code"),
    ("一次性绑定码", "One-time binding code"),
    ("已绑定", "Bound"),
    ("未绑定", "Unbound"),
    ("已绑定账号", "Bound accounts"),
    ("服务账号", "Service account"),
    ("发送者ID", "Sender ID"),
    # Skills / Agents
    ("技能", "Skill"),
    ("技能管理", "Skill management"),
    ("技能状态", "Skill status"),
    ("技能描述", "Skill description"),
    ("技能名称", "Skill name"),
    ("技能配置", "Skill configuration"),
    ("智能体", "Agent"),
    ("智能体管理", "Agent management"),
    ("子代理", "Sub-agent"),
    ("代理模式", "Agent mode"),
    ("对话模式", "Conversation mode"),
    # Projects
    ("项目", "Project"),
    ("项目管理", "Project management"),
    ("项目名称", "Project name"),
    ("项目描述", "Project description"),
    ("项目详情", "Project details"),
    ("项目状态", "Project status"),
    ("新建项目", "New project"),
    ("创建项目", "Create project"),
    ("选择项目", "Select project"),
    ("无项目", "No project"),
    ("未绑定项目", "Unbound project"),
    ("绑定项目", "Bind project"),
    ("解除项目绑定", "Unbind project"),
    ("事实黑板", "Fact board"),
    ("事实", "Fact"),
    ("事实详情", "Fact details"),
    ("攻击链", "Attack chain"),
    ("攻击链可视化", "Attack chain visualisation"),
    ("攻击链模板", "Attack chain template"),
    ("环境模板", "Environment template"),
    ("置信度", "Confidence"),
    # Dashboard
    ("仪表盘", "Dashboard"),
    ("风险等级", "Risk level"),
    ("风险概览", "Risk overview"),
    ("安全", "Safe"),
    ("安全状态", "Security status"),
    ("总漏洞数", "Total vulnerabilities"),
    ("修复率", "Fix rate"),
    ("待处理漏洞", "Open vulnerabilities"),
    ("最近漏洞", "Recent vulnerabilities"),
    ("近期事实", "Recent facts"),
    ("工具执行次数", "Tool executions"),
    ("工具执行成功率", "Tool success rate"),
    ("能力中心", "Capability center"),
    ("推荐操作", "Recommended actions"),
    ("Token用量", "Token usage"),
    ("运行中对话", "Running conversations"),
    ("运行平稳", "Healthy"),
    ("批量任务队列", "Batch task queue"),
    ("运行中监听器", "Running listeners"),
    ("活跃连接", "Active connections"),
    ("开始你的安全之旅", "Start your security journey"),
    # Notifications
    ("事件通知", "Event notifications"),
    ("暂无新事件", "No new events"),
    ("最近事件", "Recent events"),
    ("查看全部", "View all"),
    ("查看更多", "View more"),
    # General UI
    ("确认操作", "Confirm action"),
    ("确认要", "Are you sure you want to"),
    ("请确认", "Please confirm"),
    ("操作已完成", "Operation completed"),
    ("操作已取消", "Operation cancelled"),
    ("正在执行", "Executing"),
    ("执行完成", "Execution complete"),
    ("暂不支持", "Not supported yet"),
    ("功能开发中", "Feature in development"),
    ("即将推出", "Coming soon"),
    ("实验性功能", "Experimental feature"),
    ("Beta", "Beta"),
    ("新功能", "New feature"),
    ("提示：", "Note: "),
    ("注意：", "Note: "),
    ("警告：", "Warning: "),
    ("错误：", "Error: "),
    ("成功：", "Success: "),
    ("当前用户", "Current user"),
    ("当前角色", "Current role"),
    ("当前项目", "Current project"),
    ("当前对话", "Current conversation"),
    ("当前任务", "Current task"),
    ("当前状态", "Current status"),
    ("最近更新", "Last updated"),
    ("最后修改", "Last modified"),
    ("创建者", "Created by"),
    ("修改者", "Modified by"),
    ("负责人", "Owner"),
    ("所属项目", "Project"),
    ("所属分类", "Category"),
    ("关联漏洞", "Related vulnerabilities"),
    ("关联资产", "Related assets"),
    ("关联任务", "Related tasks"),
    ("关联对话", "Related conversations"),
    # Form validation
    ("必须填写", "Required"),
    ("格式不正确", "Invalid format"),
    ("长度不能超过", "Length cannot exceed"),
    ("不能少于", "Cannot be less than"),
    ("不能多于", "Cannot be more than"),
    ("只能包含", "Can only contain"),
    ("不包含特殊字符", "No special characters"),
    ("只能是数字", "Numbers only"),
    ("只能是字母", "Letters only"),
    ("只能是字母和数字", "Letters and numbers only"),
    ("不是有效的IP地址", "Not a valid IP address"),
    ("不是有效的URL", "Not a valid URL"),
    ("不是有效的邮箱", "Not a valid email"),
    ("不是有效的端口", "Not a valid port"),
    ("已经存在", "Already exists"),
    ("不存在该用户", "User not found"),
    ("密码不匹配", "Passwords do not match"),
    ("密码太短", "Password too short"),
    ("密码太简单", "Password too simple"),
    # Specific to codebase patterns
    ("攻击面", "Attack surface"),
    ("攻击链步骤", "Attack chain steps"),
    ("利用路径", "Exploit path"),
    ("渗透测试", "Penetration testing"),
    ("安全测试", "Security testing"),
    ("安全评估", "Security assessment"),
    ("安全审计", "Security audit"),
    ("漏洞利用", "Vulnerability exploitation"),
    ("漏洞验证", "Vulnerability verification"),
    ("漏洞修复", "Vulnerability fix"),
    ("横向移动", "Lateral movement"),
    ("权限提升", "Privilege escalation"),
    ("持久化", "Persistence"),
    ("信息收集", "Information gathering"),
    ("侦察", "Reconnaissance"),
    ("入侵", "Intrusion"),
    ("逃逸", "Evasion"),
    ("隐蔽", "Stealth"),
    ("命令与控制", "Command & Control"),
    ("数据外泄", "Data exfiltration"),
    ("清除痕迹", "Cleanup"),
    ("应急响应", "Incident response"),
    ("修复建议", "Remediation recommendation"),
    ("整改建议", "Remediation suggestion"),
    ("影响", "Impact"),
    ("风险", "Risk"),
    ("威胁", "Threat"),
    ("攻击者", "Attacker"),
    ("受害者", "Victim"),
    ("目标系统", "Target system"),
    ("目标主机", "Target host"),
    ("内网", "Internal network"),
    ("外网", "External network"),
    ("公网", "Public internet"),
    ("隔离网络", "Isolated network"),
    ("DMZ", "DMZ"),
    ("防火墙", "Firewall"),
    ("WAF", "WAF"),
    ("IDS", "IDS"),
    ("IPS", "IPS"),
    ("SIEM", "SIEM"),
    ("SOC", "SOC"),
    ("红队", "Red team"),
    ("蓝队", "Blue team"),
    ("紫队", "Purple team"),
    ("测试", "Test"),
    ("测试连接", "Test connection"),
    ("试运行", "Dry run"),
    ("示例", "Example"),
    ("模板", "Template"),
    ("预设", "Preset"),
    ("示例参数", "Sample parameters"),
    ("测试参数", "Test parameters"),
    ("试运行结果", "Dry run result"),
    ("测试结果", "Test result"),
    ("验证结果", "Validation result"),
    ("匹配结果", "Match result"),
    ("匹配成功", "Match successful"),
    ("未匹配", "No match"),
    ("命中", "Hit"),
    ("未命中", "No hit"),
    ("规则", "Rule"),
    ("规则名称", "Rule name"),
    ("规则描述", "Rule description"),
    ("规则列表", "Rule list"),
    ("规则顺序", "Rule order"),
    ("正则表达式", "Regular expression"),
    ("匹配模式", "Match pattern"),
    ("匹配类型", "Match type"),
    ("匹配范围", "Match scope"),
    ("匹配文本", "Match text"),
    ("拦截", "Block"),
    ("拦截规则", "Block rule"),
    ("拦截策略", "Block policy"),
    ("拦截提醒", "Block message"),
    ("调用拦截", "Call intercept"),
    ("工具拦截", "Tool block"),
    ("已拦截", "Blocked"),
    ("拦截成功", "Blocked successfully"),
    # Misc remaining
    ("刷新数据", "Refresh data"),
    ("跟随系统", "Follow system"),
    ("跟随默认通道", "Follow default channel"),
    ("跟随系统设置", "Follow system settings"),
    ("不指定", "Not specified"),
    ("自动检测", "Auto-detect"),
    ("手动配置", "Manual configuration"),
    ("自动配置", "Auto configure"),
    ("继承", "Inherit"),
    ("覆盖", "Override"),
    ("合并", "Merge"),
    ("追加", "Append"),
    ("替换", "Replace"),
    ("插入", "Insert"),
    ("移动", "Move"),
    ("复制到", "Copy to"),
    ("移动到", "Move to"),
    ("导入到", "Import to"),
    ("导出到", "Export to"),
    ("发送到对话", "Send to chat"),
    ("发送到任务", "Send to task"),
    ("快速扫描", "Quick scan"),
    ("深度扫描", "Deep scan"),
    ("自定义扫描", "Custom scan"),
    ("扫描配置", "Scan config"),
    ("扫描进度", "Scan progress"),
    ("扫描完成", "Scan completed"),
    ("正在扫描", "Scanning"),
    ("扫描队列", "Scan queue"),
    ("扫描历史", "Scan history"),
    ("扫描报告", "Scan report"),
    ("修改记录", "Change log"),
    ("变更记录", "Change record"),
    ("操作记录", "Operation record"),
    ("历史记录", "History"),
    ("版本历史", "Version history"),
    ("回滚", "Rollback"),
    ("撤销", "Undo"),
    ("重做", "Redo"),
    ("格式化", "Format"),
    ("美化", "Prettify"),
    ("压缩", "Compress"),
    ("加密", "Encrypt"),
    ("解密", "Decrypt"),
    ("编码", "Encode"),
    ("解码", "Decode"),
    ("哈希", "Hash"),
    ("签名", "Signature"),
    ("证书", "Certificate"),
    ("密钥", "Key"),
    ("令牌", "Token"),
    ("凭证", "Credential"),
    ("会话令牌", "Session token"),
    ("访问令牌", "Access token"),
    ("刷新令牌", "Refresh token"),
    ("API令牌", "API token"),
    ("API密钥", "API key"),
    ("生成", "Generate"),
    ("生成中", "Generating"),
    ("生成成功", "Generated successfully"),
    ("生成失败", "Generation failed"),
    ("重新生成", "Regenerate"),
    ("撤销令牌", "Revoke token"),
    ("刷新令牌", "Refresh token"),
    ("令牌已过期", "Token expired"),
    ("令牌无效", "Invalid token"),
    ("请求超时", "Request timed out"),
    ("响应超时", "Response timed out"),
    ("响应", "Response"),
    ("请求", "Request"),
    ("响应结果", "Response result"),
    ("请求参数", "Request parameters"),
    ("响应内容", "Response content"),
    ("响应状态", "Response status"),
    ("状态码", "Status code"),
    ("返回码", "Return code"),
    ("错误码", "Error code"),
    ("错误信息", "Error message"),
    ("错误详情", "Error details"),
    ("错误堆栈", "Error stack"),
    ("异常信息", "Exception message"),
    ("调用栈", "Call stack"),
    ("调试信息", "Debug info"),
    ("调试日志", "Debug log"),
    ("系统日志", "System log"),
    ("访问日志", "Access log"),
    ("错误日志", "Error log"),
    ("操作日志", "Operation log"),
    ("安全日志", "Security log"),
    ("事件日志", "Event log"),
    ("清理存储", "Clean storage"),
    ("存储清理", "Storage cleanup"),
    ("磁盘空间", "Disk space"),
    ("内存使用", "Memory usage"),
    ("CPU使用", "CPU usage"),
    ("系统状态", "System status"),
    ("系统信息", "System info"),
    ("关于", "About"),
    ("帮助", "Help"),
    ("文档", "Documentation"),
    ("教程", "Tutorial"),
    ("入门指南", "Getting started"),
    ("用户手册", "User manual"),
    ("API文档", "API documentation"),
    ("更新日志", "Changelog"),
    ("发布说明", "Release notes"),
    ("已知问题", "Known issues"),
    ("反馈", "Feedback"),
    ("报告问题", "Report issue"),
    ("功能建议", "Feature request"),
    ("联系我们", "Contact us"),
    ("获取支持", "Get support"),
    ("在线支持", "Online support"),
    ("技术支持", "Technical support"),
    ("商业支持", "Commercial support"),
    ("开源许可证", "Open source license"),
    ("版权", "Copyright"),
]

def translate_file(path):
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        content = f.read()
    
    before = len(re.findall(r'[\u4e00-\u9fff]', content))
    if before == 0:
        return 0, 0
    
    for zh, en in REPLACEMENTS:
        content = content.replace(zh, en)
    
    after = len(re.findall(r'[\u4e00-\u9fff]', content))
    replaced = before - after
    
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    
    return before, after

total_before = 0
total_after = 0
files_processed = 0

for root, dirs, files in os.walk("web/static/js"):
    dirs[:] = [d for d in dirs if d != "vendor"]
    for fname in sorted(files):
        if not fname.endswith((".js", ".cjs")):
            continue
        path = os.path.join(root, fname)
        before, after = translate_file(path)
        if before > 0:
            total_before += before
            total_after += after
            files_processed += 1
            if after > 0:
                print(f"  PARTIAL {path}: {before} -> {after} remaining")

print(f"\nDone: {files_processed} files processed")
print(f"Total Chinese chars: {total_before} -> {total_after} remaining")
print(f"Replaced: {total_before - total_after} chars")
