#!/usr/bin/env python3
"""
Smart final pass: for each remaining Chinese line in JS files,
extract just the Chinese characters with context and build replacements.
"""
import re, os

# Strategy: find all remaining Chinese-containing lines,
# group them by file, and for comments: try to just remove/replace 
# the remaining Chinese words that are stuck in mixed text.

# These are Chinese words/characters that commonly appear in mixed comments
# They should be translated or just dropped (if they're just particles)
FINAL_CLEANUP = [
    # Particles / connecting words often left orphaned  
    ("的", ""),         # possessive/structural particle
    ("了", ""),         # completion particle
    ("也", "also"),
    ("都", "all"),
    ("也就是说", "that is"),
    ("或者", "or"),
    ("并且", "and"),
    ("但是", "but"),
    ("虽然", "although"),
    ("因为", "because"),
    ("所以", "therefore"),
    ("如果", "if"),
    ("否则", "otherwise"),
    ("只有", "only when"),
    ("才能", "can"),
    ("以便", "so that"),
    ("以避免", "to avoid"),
    ("以确保", "to ensure"),
    ("从而", "thus"),
    ("通过", "through"),
    ("对于", "for"),
    ("关于", "about"),
    ("根据", "based on"),
    ("由于", "due to"),
    ("为了", "in order to"),
    ("在此", "here"),
    ("此时", "at this point"),
    ("此处", "here"),
    ("此后", "thereafter"),
    ("之前", "before"),
    ("之后", "after"),
    ("之间", "between"),
    ("之外", "outside"),
    ("之内", "inside"),
    ("其中", "among which"),
    ("其他", "other"),
    ("其余", "remaining"),
    ("其实", "actually"),
    ("其次", "secondly"),
    ("首先", "first"),
    ("然后", "then"),
    ("最后", "finally"),
    ("目前", "currently"),
    ("当前", "current"),
    ("现在", "now"),
    ("之前", "before"),
    ("已经", "already"),
    ("仍然", "still"),
    ("仍旧", "still"),
    ("仍会", "still will"),
    ("即可", "is sufficient"),
    ("即时", "immediately"),
    ("立即", "immediately"),
    ("直接", "directly"),
    ("同时", "simultaneously"),
    ("并发", "concurrently"),
    ("逐个", "one by one"),
    ("逐步", "step by step"),
    ("依次", "in order"),
    ("按顺序", "in order"),
    ("按照", "according to"),
    ("根据", "based on"),
    ("基于", "based on"),
    ("用于", "for"),
    ("用来", "used to"),
    ("用作", "used as"),
    ("用作", "used as"),
    ("作为", "as"),
    ("作用", "function"),
    ("适用", "applicable"),
    ("适当", "appropriate"),
    ("合适", "suitable"),
    ("正确", "correct"),
    ("准确", "accurate"),
    ("精确", "precise"),
    ("完整", "complete"),
    ("完全", "fully"),
    ("完成", "complete"),
    ("结束", "end"),
    ("开始", "start"),
    ("启动", "start"),
    ("停止", "stop"),
    ("暂停", "pause"),
    ("继续", "continue"),
    ("恢复", "resume"),
    ("重新", "re-"),
    ("重置", "reset"),
    ("重试", "retry"),
    ("重复", "repeat"),
    ("重叠", "overlap"),
    ("覆盖", "override"),
    ("覆写", "overwrite"),
    ("替换", "replace"),
    ("替代", "replace"),
    ("代替", "replace"),
    ("取代", "replace"),
    ("更新", "update"),
    ("修改", "modify"),
    ("改变", "change"),
    ("改动", "change"),
    ("变更", "change"),
    ("切换", "switch"),
    ("转换", "convert"),
    ("转化", "transform"),
    ("转为", "convert to"),
    ("转成", "convert to"),
    ("格式化", "format"),
    ("解析", "parse"),
    ("分析", "analyse"),
    ("处理", "process"),
    ("操作", "operation"),
    ("执行", "execute"),
    ("运行", "run"),
    ("调用", "call"),
    ("触发", "trigger"),
    ("激活", "activate"),
    ("启用", "enable"),
    ("禁用", "disable"),
    ("关闭", "close"),
    ("打开", "open"),
    ("显示", "show"),
    ("隐藏", "hide"),
    ("渲染", "render"),
    ("绘制", "draw"),
    ("更新", "update"),
    ("刷新", "refresh"),
    ("加载", "load"),
    ("上传", "upload"),
    ("下载", "download"),
    ("导入", "import"),
    ("导出", "export"),
    ("保存", "save"),
    ("存储", "store"),
    ("缓存", "cache"),
    ("清除", "clear"),
    ("清空", "empty"),
    ("删除", "delete"),
    ("移除", "remove"),
    ("添加", "add"),
    ("插入", "insert"),
    ("追加", "append"),
    ("合并", "merge"),
    ("分割", "split"),
    ("拆分", "split"),
    ("提取", "extract"),
    ("获取", "get"),
    ("查询", "query"),
    ("搜索", "search"),
    ("查找", "find"),
    ("过滤", "filter"),
    ("筛选", "filter"),
    ("排序", "sort"),
    ("分页", "paginate"),
    ("跳转", "navigate"),
    ("跳过", "skip"),
    ("忽略", "ignore"),
    ("检查", "check"),
    ("验证", "validate"),
    ("测试", "test"),
    ("调试", "debug"),
    ("监控", "monitor"),
    ("跟踪", "track"),
    ("记录", "record"),
    ("日志", "log"),
    ("统计", "statistics"),
    ("计算", "calculate"),
    ("生成", "generate"),
    ("构建", "build"),
    ("编译", "compile"),
    ("打包", "bundle"),
    ("部署", "deploy"),
    ("发布", "publish"),
    ("安装", "install"),
    ("卸载", "uninstall"),
    ("更新", "update"),
    ("升级", "upgrade"),
    ("回滚", "rollback"),
    ("备份", "backup"),
    ("恢复", "restore"),
    ("重置", "reset"),
    ("初始化", "initialise"),
    ("配置", "configure"),
    ("设置", "set"),
    ("获取", "get"),
    ("发送", "send"),
    ("接收", "receive"),
    ("响应", "respond"),
    ("请求", "request"),
    ("连接", "connect"),
    ("断开", "disconnect"),
    ("关联", "associate"),
    ("绑定", "bind"),
    ("解绑", "unbind"),
    ("注册", "register"),
    ("注销", "deregister"),
    ("订阅", "subscribe"),
    ("取消订阅", "unsubscribe"),
    ("监听", "listen"),
    ("广播", "broadcast"),
    ("通知", "notify"),
    ("提示", "hint"),
    ("警告", "warn"),
    ("错误", "error"),
    ("异常", "exception"),
    ("失败", "fail"),
    ("成功", "succeed"),
    ("完成", "complete"),
    ("取消", "cancel"),
    ("中止", "abort"),
    ("超时", "timeout"),
    ("等待", "wait"),
    ("阻塞", "block"),
    ("队列", "queue"),
    ("堆栈", "stack"),
    ("线程", "thread"),
    ("进程", "process"),
    ("协程", "coroutine"),
    ("异步", "async"),
    ("同步", "sync"),
    ("并发", "concurrent"),
    ("并行", "parallel"),
    ("顺序", "sequential"),
    ("优先级", "priority"),
    ("权重", "weight"),
    ("分数", "score"),
    ("计数", "count"),
    ("数量", "quantity"),
    ("总数", "total"),
    ("合计", "total"),
    ("平均", "average"),
    ("最大", "max"),
    ("最小", "min"),
    ("范围", "range"),
    ("限制", "limit"),
    ("阈值", "threshold"),
    ("间隔", "interval"),
    ("延迟", "delay"),
    ("防抖", "debounce"),
    ("节流", "throttle"),
    ("批量", "batch"),
    ("单个", "single"),
    ("多个", "multiple"),
    ("全部", "all"),
    ("部分", "partial"),
    ("少量", "few"),
    ("大量", "many"),
    ("空", "empty"),
    ("非空", "non-empty"),
    ("有效", "valid"),
    ("无效", "invalid"),
    ("合法", "legal"),
    ("非法", "illegal"),
    ("安全", "safe"),
    ("不安全", "unsafe"),
    ("加密", "encrypt"),
    ("解密", "decrypt"),
    ("签名", "sign"),
    ("验签", "verify signature"),
    ("哈希", "hash"),
    ("编码", "encode"),
    ("解码", "decode"),
    ("压缩", "compress"),
    ("解压", "decompress"),
    ("序列化", "serialise"),
    ("反序列化", "deserialise"),
    ("格式", "format"),
    ("类型", "type"),
    ("模式", "mode"),
    ("策略", "strategy"),
    ("算法", "algorithm"),
    ("模板", "template"),
    ("规则", "rule"),
    ("模式", "pattern"),
    ("结构", "structure"),
    ("布局", "layout"),
    ("样式", "style"),
    ("主题", "theme"),
    ("颜色", "colour"),
    ("字体", "font"),
    ("大小", "size"),
    ("位置", "position"),
    ("坐标", "coordinates"),
    ("宽度", "width"),
    ("高度", "height"),
    ("边距", "margin"),
    ("内边距", "padding"),
    ("边框", "border"),
    ("圆角", "border radius"),
    ("阴影", "shadow"),
    ("透明度", "opacity"),
    ("层叠", "stacking"),
    ("叠加", "overlay"),
    ("浮动", "float"),
    ("定位", "positioning"),
    ("对齐", "align"),
    ("居中", "centre"),
    ("左对齐", "left-align"),
    ("右对齐", "right-align"),
    ("垂直居中", "vertically centre"),
    ("水平居中", "horizontally centre"),
    ("间距", "spacing"),
    ("换行", "line break"),
    ("折行", "word wrap"),
    ("溢出", "overflow"),
    ("截断", "truncate"),
    ("省略", "ellipsis"),
    ("展示", "display"),
    ("视图", "view"),
    ("视口", "viewport"),
    ("滚动", "scroll"),
    ("缩放", "zoom"),
    ("旋转", "rotate"),
    ("翻转", "flip"),
    ("动画", "animation"),
    ("过渡", "transition"),
    ("渐变", "gradient"),
    ("模糊", "blur"),
    ("清晰", "sharp"),
    ("图片", "image"),
    ("图标", "icon"),
    ("按钮", "button"),
    ("链接", "link"),
    ("输入", "input"),
    ("输出", "output"),
    ("文本", "text"),
    ("标签", "label"),
    ("标题", "title"),
    ("描述", "description"),
    ("内容", "content"),
    ("正文", "body"),
    ("摘要", "summary"),
    ("详情", "details"),
    ("信息", "info"),
    ("数据", "data"),
    ("参数", "parameter"),
    ("返回值", "return value"),
    ("属性", "property"),
    ("字段", "field"),
    ("键", "key"),
    ("值", "value"),
    ("名称", "name"),
    ("标识符", "identifier"),
    ("唯一标识", "unique identifier"),
    ("索引", "index"),
    ("列表", "list"),
    ("数组", "array"),
    ("字典", "dictionary"),
    ("映射", "map"),
    ("集合", "set"),
    ("对象", "object"),
    ("实例", "instance"),
    ("类", "class"),
    ("方法", "method"),
    ("函数", "function"),
    ("变量", "variable"),
    ("常量", "constant"),
    ("引用", "reference"),
    ("指针", "pointer"),
    ("回调", "callback"),
    ("钩子", "hook"),
    ("事件", "event"),
    ("监听器", "listener"),
    ("处理器", "handler"),
    ("中间件", "middleware"),
    ("插件", "plugin"),
    ("扩展", "extension"),
    ("模块", "module"),
    ("包", "package"),
    ("库", "library"),
    ("框架", "framework"),
    ("依赖", "dependency"),
    ("版本", "version"),
    ("兼容性", "compatibility"),
    ("接口", "interface"),
    ("协议", "protocol"),
    ("规范", "specification"),
    ("约定", "convention"),
    ("标准", "standard"),
    ("最佳实践", "best practice"),
    ("文档", "documentation"),
    ("注释", "comment"),
    ("说明", "description"),
    ("示例", "example"),
    ("教程", "tutorial"),
    ("指南", "guide"),
    ("参考", "reference"),
    ("附录", "appendix"),
    ("词汇表", "glossary"),
    ("索引", "index"),
    ("目录", "table of contents"),
    # Also handle remaining untranslated words in context
    "浏览器": "browser",
    "前台": "foreground",
    "后台": "background",
    "前端": "frontend",
    "后端": "backend",
    "服务端": "server",
    "客户端": "client",
    "代理": "proxy",
    "接口": "interface/API",
    "请求": "request",
    "响应": "response",
    "流": "stream",
    "管道": "pipeline",
    "通道": "channel",
    "队列": "queue",
    "缓冲区": "buffer",
    "缓冲": "buffer",
    "锁": "lock",
    "锁定": "lock",
    "解锁": "unlock",
    "竞争": "race",
    "冲突": "conflict",
    "同步": "sync",
    "异步": "async",
    "阻塞": "block",
    "非阻塞": "non-blocking",
    "并发": "concurrent",
    "并行": "parallel",
    "串行": "serial",
    "原子": "atomic",
    "事务": "transaction",
    "提交": "commit",
    "回滚": "rollback",
    "快照": "snapshot",
    "镜像": "mirror",
    "复制": "replicate",
    "同步": "sync",
    "差量": "delta",
    "增量": "incremental",
    "全量": "full",
    "分布式": "distributed",
    "集群": "cluster",
    "节点": "node",
    "主节点": "master node",
    "从节点": "slave node",
    "主副": "primary/secondary",
    "分片": "shard",
    "分区": "partition",
    "路由": "route/router",
    "负载均衡": "load balancing",
    "故障转移": "failover",
    "高可用": "high availability",
    "容错": "fault tolerance",
    "降级": "fallback",
    "熔断": "circuit breaking",
    "限流": "rate limiting",
    "防重放": "replay protection",
    "幂等": "idempotent",
    "乐观锁": "optimistic lock",
    "悲观锁": "pessimistic lock",
    "分布式锁": "distributed lock",
    "消息队列": "message queue",
    "发布订阅": "pub/sub",
    "推送": "push",
    "拉取": "pull",
    "轮询": "polling",
    "长轮询": "long polling",
    "WebSocket": "WebSocket",
    "服务器发送事件": "server-sent events",
    "流式传输": "streaming",
    "分块": "chunked",
    "编码": "encoding",
    "解码": "decoding",
    "压缩": "compression",
    "加密": "encryption",
    "签名": "signing",
    "认证": "authentication",
    "授权": "authorisation",
    "鉴权": "auth",
    "权限": "permission",
    "令牌": "token",
    "密钥": "key",
    "证书": "certificate",
    "会话": "session",
    "状态": "state/status",
    "持久化": "persistence",
    "序列化": "serialisation",
    "反序列化": "deserialisation",
    "编解码": "codec",
    "压缩算法": "compression algorithm",
    "哈希算法": "hash algorithm",
    "加密算法": "encryption algorithm",
    "签名算法": "signing algorithm",
    "摘要算法": "digest algorithm",
    "随机数": "random number",
    "种子": "seed",
    "盐值": "salt",
    "向量": "vector",
    "密文": "ciphertext",
    "明文": "plaintext",
    "加密文本": "encrypted text",
    "加密数据": "encrypted data",
    "敏感数据": "sensitive data",
    "敏感信息": "sensitive information",
    "隐私数据": "private data",
    "个人信息": "personal information",
    "用户数据": "user data",
    "业务数据": "business data",
    "配置数据": "configuration data",
    "系统数据": "system data",
    "临时数据": "temporary data",
    "缓存数据": "cached data",
    "持久数据": "persistent data",
    "历史数据": "historical data",
    "实时数据": "real-time data",
    "元数据": "metadata",
    "原始数据": "raw data",
    "清洗数据": "cleaned data",
    "结构化数据": "structured data",
    "非结构化数据": "unstructured data",
    "半结构化数据": "semi-structured data",
    "二进制数据": "binary data",
    "文本数据": "text data",
    "图像数据": "image data",
    "音频数据": "audio data",
    "视频数据": "video data",
    "多媒体数据": "multimedia data",
}

def apply_final_cleanup(content):
    result = content
    for zh, en in sorted(WORD_MAP.items(), key=lambda x: -len(x[0])):
        if zh:
            result = result.replace(zh, en)
    return result

# Also convert FINAL_CLEANUP tuples
for entry in FINAL_CLEANUP:
    if len(entry) == 2:
        zh, en = entry
        if zh not in WORD_MAP:
            WORD_MAP[zh] = en

total_before = 0
total_after = 0

for root, dirs, files in os.walk("web/static/js"):
    dirs[:] = [d for d in dirs if d != "vendor"]
    for fname in sorted(files):
        if not fname.endswith((".js", ".cjs")):
            continue
        path = os.path.join(root, fname)
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            content = f.read()
        
        before = len(re.findall(r"[\u4e00-\u9fff]", content))
        if before == 0:
            continue
        
        new_content = apply_final_cleanup(content)
        after = len(re.findall(r"[\u4e00-\u9fff]", new_content))
        
        total_before += before
        total_after += after
        
        with open(path, "w", encoding="utf-8") as f:
            f.write(new_content)
        
        if after > 0:
            print(f"  {after:5d} remaining: {path}")

print(f"\nTotal: {total_before} -> {total_after} ({total_before - total_after} replaced)")
