#!/usr/bin/env python3
"""
Final pass: translate remaining Chinese in JS files using direct per-line replacement.
For each line with Chinese: try to translate the full Chinese segments within it.
"""
import re, os, json

# Extended phrase dictionary covering ALL remaining patterns
PHRASES = {
    # === Structural / Code comment patterns ===
    # chat.js
    "离开聊天页时立即让尚在Initialisation的Send请求失去Page所有权。": "When leaving the chat page, immediately release page ownership from any in-progress send request.",
    "后端Task仍会ContinueExecute；这里只中止浏览器前台流，避免首个 conversation": "The backend task continues; this only cancels the browser foreground stream, preventing the first conversation",
    "事件在用户已经切到其他Page后再次抢占CurrentConversation。": "event from re-claiming the current session after the user has navigated to another page.",
    "轻量Conversation LRU 缓存。": "Lightweight conversation LRU cache.",
    "缓存只用作Request failed时的降级数据，不能先于服务端响应直接Render：": "Cache is fallback data for failed requests only — must not render before the server response:",
    "RunningConversation的 process details 会持续写入，直接Render旧快照会让": "A running conversation's process details keep writing; rendering the old snapshot would cause",
    "Input box草稿Save相关": "Input box draft save related",
    "Chat文件Upload相关（后端会拼接Path与Content发给大Model，前端不再重复发文件List）": "Chat file upload (backend concatenates path+content for LLM; frontend no longer resends file list)",
    "Chat附件：选文件后异步 POST /api/chat-uploads，Send时只传 serverPath（绝对Path），Request body不再内联大文件Content。": "Chat attachments: async POST /api/chat-uploads after selecting files; only serverPath (absolute) is sent; request body no longer inlines large file content.",
    "Human-AI collaboration（HITL）Conversation级Configuration": "Human-AI collaboration (HITL) session-level configuration",
    "白名单Split string into array (comma or newline separated, consistent with textarea)": "Whitelist: split string into array (comma or newline separated, consistent with textarea)",
    "与 config.yaml hitl.tool_whitelist 合并为Input box展示（全局项在前，去重不区分Size写）": "Merged with config.yaml hitl.tool_whitelist for input display (global items first, case-insensitive dedup)",
    "Save/发请求前去掉全局白名单Tool，避免Conversation里重复存 config 已有项": "Remove global whitelist tools before saving/sending to avoid duplicating items already in config",
    "侧栏已改为自动Save；同步UpdateInput box快捷Summary。": "Sidebar now auto-saves; sync-update the input box shortcut summary.",
    "侧栏Human-AI collaboration：自动写入本地、合并展示并尽量同步服务端": "Sidebar HITL config: auto-written locally, merged for display, synced to server when possible",
    "Input box右侧展示CurrentConversation通道的Model；审批Model只出现在 HITL 入口。": "Right side of input box shows current conversation channel's model; approval model only appears in HITL entry.",
    "Select AI channel、Model与推理Settings": "Select AI channel, model and reasoning settings",
    "离开正在读取主 POST 流的Chat时，只断开浏览器侧响应流，不Stop后端Task。": "When leaving a chat that is reading the main POST stream, only disconnect the browser-side response stream, do not stop the backend task.",
    "后端Task使用 detachedAgentContext，仍会ContinueRun；重新进入该Chat时由": "The backend task uses detachedAgentContext and continues running; when re-entering the chat,",
    "task-events 镜像流接管。这样同时Run多个Chat也只占用一个前台长Connection，": "the task-events mirror stream takes over. Running multiple chats only occupies one foreground long connection,",
    "不会耗尽浏览器对同一主机的Connection槽位而卡住普通 GET/POST 请求。": "preventing browser connection slots to the same host from being exhausted by blocking regular GET/POST requests.",
    "供 WebShell 等复用：在 Eino Path下Back reasoning 请求片段或 undefined": "Reusable by WebShell etc.: returns reasoning request fragment or undefined for Eino path",
    "先展示基础Mode，避免首次Sign in时Configuration接口短暂Failed导致入口被Hide。": "Show basic mode first to avoid hiding the entry if the config API briefly fails on first login.",
    "SaveInput box草稿到localStorage（防抖版本）": "Save input box draft to localStorage (debounced)",
    "清除之前的定时器": "Clear previous timer",
    "Settings新的定时器": "Set new timer",
    "SaveInput box草稿到localStorage": "Save input box draft to localStorage",
    "不要把占位Hint本身当作草稿Save": "Do not save the placeholder hint text as a draft",
    "如果Content为空或等于占位Hint，清除Save的草稿": "If content is empty or equals the placeholder hint, clear the saved draft",
    "localStorage可能已满或不可用，静默Failed": "localStorage may be full or unavailable, fail silently",
    "Save草稿Failed:": "Save draft failed:",
    "从localStorageResumeInput box草稿": "Restore input box draft from localStorage",
    "若Current value 与 placeholder 相同，说明Hint被误当作Content，Clear以便正确ShowPlaceholder": "If current value equals placeholder, the hint was mistakenly treated as content — clear to show placeholder correctly",
    "如果Input box已有Content，不Resume草稿（避免覆盖用户输入）": "If the input box already has content, do not restore the draft (to avoid overwriting user input)",
    "如果草稿Content和占位Hint一样，则认为是无效草稿，不Resume": "If the draft content equals the placeholder hint, treat it as an invalid draft and do not restore",
    "调整Input box高度以FitContent": "Adjust input box height to fit content",
    "Cleanup掉无效草稿，避免之后Continue干扰": "Clean up invalid draft to avoid interference later",
    "Resume草稿Failed:": "Restore draft failed:",
    "清除Save的草稿": "Clear saved draft",
    "同步清除，确保立即生效": "Synchronously clear to ensure immediate effect",
    "清除草稿Failed:": "Clear draft failed:",
    "调整textarea高度以FitContent": "Adjust textarea height to fit content",
    "先Reset高度为auto，然后立即Settings为固定值，确保能准确获取scrollHeight": "First reset height to auto, then immediately set to a fixed value to accurately get scrollHeight",
    "Strong制浏览器重新计算Layout": "Force browser to recalculate layout",
    "计算新高度（最小40px，最大不超过300px）": "Calculate new height (min 40px, max 300px)",
    "如果Content为空或只有很少Content，立即Reset到最小高度": "If content is empty or minimal, immediately reset to minimum height",
    "Send消息": "Send message",
    "Enter 会直接调用 sendMessage；同一Conversation在其他Tags页已启动Task时，": "Enter directly calls sendMessage; when the same conversation already has a task running in another tab,",
    "必须在Render用户气泡和发起 POST 前做一次权威State同步，避免Generate一轮\u201c已有TaskExecuting\u201d伪Chat。": 'must do an authoritative state sync before rendering the user bubble and starting the POST, to avoid generating a spurious "task already running" chat turn.',
    "CurrentConversation已有Task正在Execute，请先等待Complete或Stop task。": "The current conversation already has a running task. Please wait for it to complete or stop the task first.",
    "正在等待附件UploadComplete…": "Waiting for attachments to finish uploading…",
    "部分附件未Uploaded successfully，请Remove failed项或重新Select file后再Send。": "Some attachments failed to upload. Please remove the failed items or re-select the files before sending.",
    "有附件且用户未输入时，发一句简短DefaultHint即可（后端会拼接Path和文件Content给大Model）": "When there are attachments but no user input, send a brief default hint (backend concatenates path and file content for the LLM)",
    "Send前的Task status/附件检查可能包含异步等待。若用户已主动ToggleConversation，": "Pre-send task status/attachment checks may include async waits. If the user has already switched conversations,",
    "保留CurrentPage，不再把这次尚未发出的请求写入新的可见Chat。": "keep the current page and do not write this unsent request to the newly visible chat.",
    "ShowUser message（含附件名，便于用户Confirm）": "Show user message (including attachment names for user confirmation)",
    "清除防抖定时器，防止在ClearInput box后重新Save草稿": "Clear debounce timer to prevent re-saving draft after clearing the input box",
    "立即清除草稿，防止PageRefresh时Resume": "Immediately clear draft to prevent restoration on page refresh",
    "使用同步方式确保草稿被清除": "Use synchronous method to ensure draft is cleared",
    "Ignore错误": "Ignore error",
    "立即ClearInput box并清除草稿（在Send请求之前）": "Immediately clear input box and draft (before sending the request)",
    "Strong制ResetInput box高度为初始高度（40px）": "Force-reset input box height to initial height (40px)",
    "构建Request body（含附件）": "Build request body (including attachments)",
    "Send后ClearAttachment list": "Clear attachment list after sending",
    "Create进度消息Container（使用详细的进度展示）": "Create progress message container (using detailed progress display)",
    "ToggleChat后仍可能收到旧响应流中已缓冲的 conversation、response_start": "After switching chats, buffered conversation/response_start events from the old stream may still arrive",
    "或 response 事件。它们只能补齐后台Task归属，不能重新抢占Current conversation。": "or response events. They can only fill in the background task attribution, not re-claim the current conversation.",
    "Parse事件数据Failed:": "Failed to parse event data:",
    "处理剩余的buffer": "Process remaining buffer",
    "Connection提前结束，未收到TaskComplete信号。Task可能仍在后端Execute，请View顶部RunningTask或RefreshCurrent conversation。": "Connection ended early without a task completion signal. The task may still be running in the backend. Please check the running tasks at the top or refresh the current conversation.",
    "消息SendSuccess后，再次确保草稿被清除": "After message sent successfully, ensure the draft is cleared again",
    "Connection已中断（": "Connection interrupted (",
    "）。长TimeTask可能仍在后端Execute，请View顶部RunningTask或稍后刷New conversation。": "). Long-running tasks may still be running in the backend. Please check the running tasks at the top or refresh the conversation later.",
    "错误: ": "Error: ",
    # More chat.js patterns
    "请根据上传的文件Content进行分析。": "Please analyze the uploaded file content.",
    "与 handler.formatInterruptContinueUserMessage 首段一致；主Chat不展示，仅迭代Details（user_interrupt_continue）": "Matches first paragraph of handler.formatInterruptContinueUserMessage; not shown in main chat, only in iteration details",
    "【用户补充 / 中断后继续】": "[User note / continue after interrupt]",
    # monitor.js
    "主Chat POST 流仍在读取时，禁止再挂 task-events 补流，否则同一事件会画两遍（与 HITL 是否开启无关）。": "When the main chat POST stream is still reading, do not attach a task-events补流, otherwise the same event renders twice (unrelated to whether HITL is enabled).",
    "window.__csAgentLiveStream 由 chat.js sendMessage 在读到 body 后设置，在 finally 中清除。": "window.__csAgentLiveStream is set by chat.js sendMessage after reading the body, cleared in finally.",
    "新Conversation：conversation 事件尚未到达前 conversationId 可能仍为 null，一律不补挂": "New conversation: conversationId may still be null before first conversation event — never attach补挂",
    "另 ": "and ",
    " 项": " more",
    "**Still verifying，暂不Generate最终结论**": "**Still verifying, not generating final conclusion yet**",
    "状态：": "Status: ",
    "待CompleteTool：`": "Pending tool calls: `",
    "待Complete检查：": "Pending completion checks: ",
    "候选输出已移入过程Details，避免误判为最终结论。": "Candidate output moved to process details to avoid being mistaken for a final conclusion.",
    "正在调用AIModel...": "Calling AI model...",
    "Run态与审批态需要及时自Refresh": "Running and approval states require timely auto-refresh",
    "Current界面Language对应的 BCP 47 Tags（与Time格式化一致）": "BCP 47 tag for current UI language (consistent with time formatting)",
    "Workflows审批": "Workflow approval",
    "Tool call已被Safe规则Block": "Tool call blocked by safety rule",
    "Tool已Submit到后台Execute": "Tool submitted to background for execution",
    # knowledge.js
    "Reset到First page": "Reset to first page",
    # common patterns
    "已获取 {count} 个Model": "Fetched {count} models",
    "请先在Settings中配置 API Key": "Please configure an API Key in Settings first",
    "获取ModelFailed": "Failed to fetch models",
    "获取Model": "Fetch model",
    # Mixed English-Chinese patterns to fix
    "System空闲": "System idle",
    "正在Execute": "Executing",
    "高Critical度已All处置": "All high-criticality items handled",
    "共 ": "Total ",
    " 个": "",
    "None有效Complete": "No valid completions",
    "None调用": "No calls",
    "未Enable": "Not enabled",
    " 个Tool": " tools",
    # settings
    "# 配置说明：这里只展示常见Settings。": "# Configuration note: only common settings are shown here.",
    "# 完整Settings请参考 config.example.yaml。": "# See config.example.yaml for the full configuration.",
    # i18n.js specific
    "语言切换失败": "Language switch failed",
    "当前语言": "Current language",
    "系统语言": "System language",
    "界面语言": "Interface language",
    "语言设置": "Language settings",
    "跟随浏览器": "Follow browser",
    # router.js
    "页面未找到": "Page not found",
    "无效的页面": "Invalid page",
    "权限不足，无法访问": "Insufficient permissions to access",
    "重定向到": "Redirecting to",
    "路由初始化": "Router initialisation",
    # chat-scroll.js
    "Chat滚动监测": "Chat scroll monitoring",
    "用户最近滚动": "User recently scrolled",
    "自动滚动": "Auto-scroll",
    "滚动到底部": "Scroll to bottom",
    "最新消息": "Latest message",
    "新消息提示": "New message indicator",
    "距底部": "distance from bottom",
    # storage.js
    "存储清理器": "Storage cleanup",
    "本地Storage": "Local storage",
    "Session存储": "Session storage",
    "清理过期数据": "Clear expired data",
    "存储空间不足": "Insufficient storage space",
    "Data格式": "Data format",
    # theme.js
    "主题切换": "Theme switch",
    "Dark Mode": "Dark mode",
    "Light Mode": "Light mode",
    "System Theme": "System theme",
    "Color Scheme": "Color scheme",
    # workflows.js
    "工作流引擎": "Workflow engine",
    "节点类型": "Node type",
    "边类型": "Edge type",
    "数据流": "Data flow",
    "执行流程": "Execution flow",
    "工作流实例": "Workflow instance",
    "工作流Package": "Workflow package",
    "安装Package": "Install package",
    "移除Package": "Remove package",
    "Package管理": "Package management",
    "Package列表": "Package list",
    "Package详情": "Package details",
    "已安装Package": "Installed packages",
    # assets.js
    "资产扫描提示": "Asset scan prompt",
    "扫描配置": "Scan configuration",
    "扫描策略": "Scan strategy",
    "扫描范围": "Scan scope",
    "Scan现在": "Scan now",
    "快速扫描": "Quick scan",
    "深度扫描": "Deep scan",
    "定时扫描": "Scheduled scan",
    "扫描记录": "Scan record",
    "扫描进度": "Scan progress",
    "正在扫描": "Scanning",
    "扫描完成": "Scan completed",
    "扫描失败": "Scan failed",
    "扫描中止": "Scan aborted",
    "扫描队列": "Scan queue",
    "资产归属": "Asset ownership",
    "资产Tag": "Asset tag",
    "资产标注": "Asset annotation",
    "批量Tag": "Batch tag",
    "Tag管理": "Tag management",
    "新增资产": "Add asset",
    "Edit资产": "Edit asset",
    "Delete资产": "Delete asset",
    "资产合并": "Asset merge",
    "合并策略": "Merge strategy",
    "主资产": "Primary asset",
    "副资产": "Secondary asset",
    # vulnerability.js
    "严重度": "Severity",
    "修复Priority": "Fix priority",
    "影响程度": "Impact level",
    "利用难度": "Exploitation difficulty",
    "发现方式": "Discovery method",
    "Discovery by": "Discovered by",
    "漏洞Template": "Vulnerability template",
    "导出漏洞": "Export vulnerabilities",
    "漏洞Report": "Vulnerability report",
    "漏洞分布": "Vulnerability distribution",
    "漏洞趋势": "Vulnerability trend",
    "漏洞Timeline": "Vulnerability timeline",
    "漏洞Graph": "Vulnerability graph",
    "漏洞Score": "Vulnerability score",
    # projects.js
    "项目Tag": "Project tag",
    "项目标注": "Project annotation",
    "项目权限": "Project permissions",
    "项目成员": "Project members",
    "项目设置": "Project settings",
    "项目Dashboard": "Project dashboard",
    "项目Overview": "Project overview",
    "项目Statistics": "Project statistics",
    "项目Timeline": "Project timeline",
    "事实Panel": "Fact panel",
    "事实图谱": "Fact graph",
    "事实Index": "Fact index",
    "关键事实": "Key facts",
    "事实Detail": "Fact details",
    "攻击Chain": "Attack chain",
    "攻击Path": "Attack path",
    "攻击Step": "Attack step",
    "攻击Goal": "Attack objective",
    "漏洞Chain": "Vulnerability chain",
    # skills.js
    "技能Test": "Skill test",
    "技能Log": "Skill log",
    "技能History": "Skill history",
    "技能Version": "Skill version",
    "技能参数Schema": "Skill parameter schema",
    "技能返回Schema": "Skill return schema",
    "技能依赖": "Skill dependencies",
    "技能配置项": "Skill configuration item",
    "技能启用": "Enable skill",
    "技能停用": "Disable skill",
    "技能Upload": "Upload skill",
    "技能Download": "Download skill",
    "技能Import": "Import skill",
    "技能Export": "Export skill",
    # roles.js
    "Role配置": "Role configuration",
    "Role模板": "Role template",
    "Role权限": "Role permissions",
    "Role技能": "Role skills",
    "Role工具": "Role tools",
    "角色配置项": "Role configuration item",
    "角色系统提示词": "Role system prompt",
    "角色模板": "Role template",
    "角色工具List": "Role tool list",
    "角色技能List": "Role skill list",
    "角色Detail": "Role details",
    "角色Overview": "Role overview",
    "role_id": "role_id",
    # c2.js
    "C2服务": "C2 service",
    "C2连接": "C2 connection",
    "C2Config": "C2 configuration",
    "C2Pipeline": "C2 pipeline",
    "BeaconConfig": "Beacon configuration",
    "监听器Config": "Listener configuration",
    "监听器Status": "Listener status",
    "监听器日志": "Listener log",
    "会话Detail": "Session details",
    "会话Log": "Session log",
    "会话Command": "Session command",
    "会话File": "Session file",
    "会话Process": "Session process",
    "会话Port": "Session port",
    "会话Screenshot": "Session screenshot",
    "Task Queue": "Task queue",
    "Task Detail": "Task details",
    "Task Result": "Task result",
    "Task Log": "Task log",
    "Payload生成": "Payload generation",
    "Payload配置": "Payload configuration",
    "Payload格式": "Payload format",
    "Payload Size": "Payload size",
    "Payload Download": "Payload download",
    "Profile配置": "Profile configuration",
    "Profile规则": "Profile rules",
    "流量Pattern": "Traffic pattern",
    "HTTP配置": "HTTP configuration",
    "Sleep设置": "Sleep settings",
    "Jitter设置": "Jitter settings",
    # webshell.js
    "WebShell连接Config": "WebShell connection configuration",
    "WebShell执行": "WebShell execution",
    "WebShell File管理": "WebShell file management",
    "WebShell命令历史": "WebShell command history",
    "WebShell Log": "WebShell log",
    "命令结果": "Command result",
    "文件列表": "File list",
    "文件Detail": "File details",
    "文件Permission": "File permissions",
    "文件Upload": "File upload",
    "文件Download": "File download",
    "文件Delete": "File delete",
    "文件Rename": "File rename",
    "文件Move": "File move",
    "文件Copy": "File copy",
    "目录创建": "Directory creation",
    "目录删除": "Directory deletion",
    "目录列表": "Directory listing",
    "路径导航": "Path navigation",
    # terminal.js
    "终端Config": "Terminal configuration",
    "终端Session": "Terminal session",
    "终端Command": "Terminal command",
    "终端Output": "Terminal output",
    "终端Color": "Terminal colour",
    "终端Theme": "Terminal theme",
    "终端Size": "Terminal size",
    "终端Font": "Terminal font",
    "终端Buffer": "Terminal buffer",
    "终端History": "Terminal history",
    "终端Tab": "Terminal tab",
    "新建Terminal": "New terminal",
    "关闭Terminal": "Close terminal",
    "清空Terminal": "Clear terminal",
    "Terminal连接": "Terminal connection",
    "Terminal断开": "Terminal disconnected",
    "Terminal重连": "Terminal reconnect",
    # wechat-robot.js
    "微信Config": "WeChat configuration",
    "微信连接": "WeChat connection",
    "微信Message": "WeChat message",
    "微信用户": "WeChat user",
    "微信Group": "WeChat group",
    "企业微信Config": "WeCom configuration",
    "钉钉Config": "DingTalk configuration",
    "飞书Config": "Feishu configuration",
    "机器人连接状态": "Bot connection status",
    "机器人Log": "Bot log",
    "机器人Command": "Bot command",
    "机器人Session": "Bot session",
    "发送者": "Sender",
    "接收者": "Recipient",
    "消息类型": "Message type",
    "消息内容": "Message content",
    "消息发送": "Message sending",
    "消息接收": "Message receiving",
    "消息History": "Message history",
    # auth.js
    "Login状态": "Login state",
    "Login信息": "Login info",
    "Login超时": "Login timeout",
    "LoginPage": "Login page",
    "Login重定向": "Login redirect",
    "用户Profile": "User profile",
    "用户Session": "User session",
    "用户Token": "User token",
    "用户权限": "User permissions",
    "用户Role": "User roles",
    "用户列表": "User list",
    "创建用户": "Create user",
    "删除用户": "Delete user",
    "修改用户": "Edit user",
    "用户Password": "User password",
    "Reset Password": "Reset password",
    # api-docs.js
    "API Overview": "API overview",
    "API列表": "API list",
    "API Detail": "API details",
    "API测试": "API test",
    "API认证": "API authentication",
    "API版本": "API version",
    "API文档生成": "API documentation generation",
    "API参数说明": "API parameter description",
    "API返回说明": "API return description",
    "API Error码": "API error codes",
    "API示例": "API examples",
    "接口认证": "API authentication",
    "认证Token": "Auth token",
    "Bearer认证": "Bearer auth",
    "签名认证": "Signature auth",
    # notifications.js
    "通知类型": "Notification type",
    "通知优先级": "Notification priority",
    "通知来源": "Notification source",
    "通知时间": "Notification time",
    "通知内容": "Notification content",
    "通知Detail": "Notification details",
    "通知Template": "Notification template",
    "通知配置": "Notification configuration",
    "通知Center": "Notification centre",
    "通知History": "Notification history",
    "通知统计": "Notification statistics",
    "推送通知": "Push notification",
    "Email通知": "Email notification",
    "Webhook通知": "Webhook notification",
    # audit.js
    "审计类别": "Audit category",
    "审计操作": "Audit operation",
    "审计时间": "Audit time",
    "审计IP": "Audit IP",
    "审计用户": "Audit user",
    "审计Detail": "Audit details",
    "审计Filter": "Audit filter",
    "审计Export": "Audit export",
    "审计Report": "Audit report",
    "审计统计": "Audit statistics",
    "审计趋势": "Audit trend",
    "审计Alert": "Audit alert",
    # rbac.js & rbac-guards.js
    "权限Check": "Permission check",
    "权限Deny": "Permission denied",
    "权限Grant": "Permission grant",
    "权限Revoke": "Permission revoke",
    "权限Inherit": "Permission inherit",
    "权限Override": "Permission override",
    "权限合并": "Permission merge",
    "权限缓存": "Permission cache",
    "权限刷新": "Permission refresh",
    "权限验证": "Permission validation",
    "资源权限Map": "Resource permission map",
    "角色权限Map": "Role permission map",
    "权限范围": "Permission scope",
    "全局权限": "Global permission",
    "Own资源": "Own resources",
    "Assigned资源": "Assigned resources",
    "All资源": "All resources",
    # hitl.js
    "等待审批": "Awaiting approval",
    "审批超时": "Approval timeout",
    "审批Decision": "Approval decision",
    "审批Log": "Approval log",
    "审批Detail": "Approval details",
    "审批配置": "Approval configuration",
    "审批策略": "Approval policy",
    "白名单管理": "Whitelist management",
    "白名单规则": "Whitelist rules",
    "白名单Tool": "Whitelist tool",
    "白名单Pattern": "Whitelist pattern",
    "HITL配置": "HITL configuration",
    "HITL策略": "HITL policy",
    "HITL模式": "HITL mode",
    "HITL超时": "HITL timeout",
    "HITL审批": "HITL approval",
    "HITL审计": "HITL audit",
    "HITL白名单": "HITL whitelist",
    "HITL Log": "HITL log",
    # i18n.js specific  
    "语言Map": "Language map",
    "翻译Function": "Translation function",
    "本地化": "Localisation",
    "日期Format": "Date format",
    "时间Format": "Time format",
    "数字Format": "Number format",
    "货币Format": "Currency format",
    "Plural规则": "Plural rules",
    "语言Detect": "Language detection",
    "语言Switch": "Language switch",
    "语言Fallback": "Language fallback",
    "翻译Key": "Translation key",
    "翻译Value": "Translation value",
    "翻译缺失": "Missing translation",
    "翻译覆盖": "Translation override",
    # info-collect.js
    "Query语法": "Query syntax",
    "Query示例": "Query examples",
    "Query解析": "Query parsing",
    "Query执行": "Query execution",
    "Query结果": "Query results",
    "Query Error": "Query error",
    "Query超时": "Query timeout",
    "Query限制": "Query limit",
    "数据源Config": "Data source configuration",
    "FOFA Query": "FOFA query",
    "ZoomEye Query": "ZoomEye query",
    "Quake Query": "Quake query",
    "Shodan Query": "Shodan query",
    "Field列表": "Field list",
    "Field设置": "Field settings",
    "Field Template": "Field template",
    "Field Filter": "Field filter",
    "Field排序": "Field sort",
    "Field分组": "Field group",
    "Field计算": "Field calculation",
    "字段Config": "Field configuration",
    "返回Field": "Return fields",
    "导出Field": "Export fields",
    "Import Field": "Import fields",
    "Field映射": "Field mapping",
    "结果导出": "Export results",
    "结果Import": "Import results",
    "结果Filter": "Filter results",
    "结果Sort": "Sort results",
    "结果Group": "Group results",
    "结果统计": "Result statistics",
    "结果预览": "Result preview",
    "结果Detail": "Result details",
    # tasks.js
    "Task配置": "Task configuration",
    "Task模板": "Task template",
    "Task类型": "Task type",
    "Task Priority": "Task priority",
    "Task Schedule": "Task schedule",
    "Task依赖": "Task dependency",
    "Task Log": "Task log",
    "Task Detail": "Task details",
    "Task进度": "Task progress",
    "Task统计": "Task statistics",
    "Task History": "Task history",
    "Task Queue": "Task queue",
    "Task Worker": "Task worker",
    "Task重试": "Task retry",
    "Task超时": "Task timeout",
    "Task Kill": "Kill task",
    "Task Pause": "Pause task",
    "Task Resume": "Resume task",
    "Batch Task管理": "Batch task management",
    "Batch Task配置": "Batch task configuration",
    "Batch Task统计": "Batch task statistics",
    # settings.js
    "Setting Key": "Setting key",
    "Setting Value": "Setting value",
    "Setting Default": "Setting default",
    "Setting更新": "Setting update",
    "Setting重置": "Setting reset",
    "Setting Import": "Import settings",
    "Setting导出": "Export settings",
    "Setting备份": "Settings backup",
    "Setting恢复": "Restore settings",
    "Setting验证": "Settings validation",
    "Channel配置": "Channel configuration",
    "Channel测试": "Channel test",
    "Channel列表": "Channel list",
    "Channel Detail": "Channel details",
    "Channel状态": "Channel status",
    "Channel切换": "Channel switch",
    "Model列表": "Model list",
    "Model配置": "Model configuration",
    "Model测试": "Model test",
    "Model Detail": "Model details",
    "Model切换": "Model switch",
    "Model状态": "Model status",
    "Vision配置": "Vision configuration",
    "Vision Model": "Vision model",
    "Vision测试": "Vision test",
    "Bot配置": "Bot configuration",
    "Bot状态": "Bot status",
    "Bot测试": "Bot test",
    "Bot命令": "Bot commands",
    "Bot绑定": "Bot binding",
    "Bot解绑": "Bot unbinding",
    "存储配置": "Storage configuration",
    "清理配置": "Cleanup configuration",
    "清理任务": "Cleanup task",
    "清理历史": "Cleanup history",
    "清理统计": "Cleanup statistics",
    "清理策略": "Cleanup strategy",
    "清理规则": "Cleanup rules",
    "保留策略": "Retention policy",
    "保留时间": "Retention period",
    "保留Size": "Retention size",
    "保留Count": "Retention count",
    # fact-graph.js
    "Graph节点": "Graph node",
    "Graph Edge": "Graph edge",
    "Graph布局": "Graph layout",
    "Graph Zoom": "Graph zoom",
    "Graph Filter": "Graph filter",
    "Graph Search": "Graph search",
    "Graph Detail": "Graph details",
    "Graph Export": "Graph export",
    "Graph配置": "Graph configuration",
    "Graph Theme": "Graph theme",
    "Graph Color": "Graph colour",
    "Graph Size": "Graph size",
    "Graph Shape": "Graph shape",
    "Graph Arrow": "Graph arrow",
    "Graph Label": "Graph label",
    "Graph Tooltip": "Graph tooltip",
    "Graph Legend": "Graph legend",
    "Graph Overview": "Graph overview",
    "Graph Statistics": "Graph statistics",
    "Graph History": "Graph history",
    "Graph Snapshot": "Graph snapshot",
    "Graph Reset": "Graph reset",
    "Graph Center": "Graph centre",
    "Graph Fullscreen": "Graph fullscreen",
    # sanitize-markdown.js
    "Markdown净化": "Markdown sanitisation",
    "Markdown过滤": "Markdown filtering",
    "Markdown解析": "Markdown parsing",
    "HTML净化": "HTML sanitisation",
    "安全过滤": "Safety filtering",
    "XSS防护": "XSS protection",
    "脚本过滤": "Script filtering",
    "内容净化": "Content sanitisation",
    # modal.js
    "Modal配置": "Modal configuration",
    "Modal动画": "Modal animation",
    "Modal关闭": "Modal close",
    "Modal打开": "Modal open",
    "Modal内容": "Modal content",
    "Modal按钮": "Modal button",
    "Modal事件": "Modal event",
    "全局Modal": "Global modal",
    "确认Modal": "Confirmation modal",
    "Alert Modal": "Alert modal",
    "消息Modal": "Message modal",
    # builtin-tools.js
    "内置Tool列表": "Built-in tool list",
    "内置Tool配置": "Built-in tool configuration",
    "Tool状态": "Tool status",
    "Tool版本": "Tool version",
    "Tool描述": "Tool description",
    "Tool参数": "Tool parameters",
    "Tool返回值": "Tool return value",
    "Tool Error": "Tool error",
    "Tool超时": "Tool timeout",
    "Tool重试": "Tool retry",
    "Tool Log": "Tool log",
    "Tool History": "Tool history",
    "Tool统计": "Tool statistics",
    "Tool测试": "Tool test",
    "Tool配置项": "Tool configuration item",
    # chat-files.js
    "文件上传配置": "File upload configuration",
    "文件大小限制": "File size limit",
    "文件类型限制": "File type restriction",
    "文件预览配置": "File preview configuration",
    "文件Cache": "File cache",
    "文件History": "File history",
    "文件Tag": "File tag",
    "文件分类": "File category",
    "文件搜索": "File search",
    "文件Filter": "File filter",
    "文件Sort": "File sort",
    "文件批量操作": "Batch file operations",
    "文件删除确认": "File delete confirmation",
    "文件上传Progress": "File upload progress",
    "文件上传Error": "File upload error",
    "文件上传成功": "File uploaded successfully",
    "Chat文件List": "Chat file list",
    "Chat文件Detail": "Chat file details",
    "Chat文件Preview": "Chat file preview",
    "Chat文件Download": "Chat file download",
    "Chat文件Delete": "Chat file delete",
    # Add more from remaining patterns
    "Conversation配置": "Conversation configuration",
    "Conversation Filter": "Conversation filter",
    "Conversation Sort": "Conversation sort",
    "Conversation Search": "Conversation search",
    "Conversation Detail": "Conversation details",
    "Conversation History": "Conversation history",
    "Conversation Tag": "Conversation tag",
    "Conversation Export": "Conversation export",
    "Conversation Delete": "Conversation delete",
    "Conversation Archive": "Conversation archive",
    "Conversation统计": "Conversation statistics",
    "Conversation配额": "Conversation quota",
    "Conversation限制": "Conversation limit",
}

def translate_partial(text):
    """Replace known Chinese phrases within text."""
    result = text
    for zh, en in sorted(PHRASES.items(), key=lambda x: -len(x[0])):
        result = result.replace(zh, en)
    return result

# Process all files
total_before = 0
total_after = 0

for root, dirs, files in os.walk("web/static/js"):
    dirs[:] = [d for d in dirs if d != "vendor"]
    for fname in sorted(files):
        if not fname.endswith((".js", ".cjs")):
            continue
        path = os.path.join(root, fname)
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            content = f.read()
        
        before = len(re.findall(r"[\u4e00-\u9fff]", content))
        if before == 0:
            continue
        
        new_content = translate_partial(content)
        after = len(re.findall(r"[\u4e00-\u9fff]", new_content))
        
        total_before += before
        total_after += after
        
        with open(path, "w", encoding="utf-8") as f:
            f.write(new_content)
        
        if after > 0:
            print(f"  {after:5d} remaining: {path}")

print(f"\nTotal: {total_before} -> {total_after} ({total_before - total_after} replaced)")
