#!/usr/bin/env python3
"""
Second-pass JS translation: handles remaining Chinese phrases that
are deeply mixed into comments and string literals.
"""

import os
import re
import json

CHINESE_RE = re.compile(r'[\u4e00-\u9fff\u3400-\u4dbf\uff00-\uffef\u2e80-\u2eff\u3000-\u303f]')

def has_chinese(s):
    return bool(CHINESE_RE.search(s))

def count_chinese(s):
    return len(CHINESE_RE.findall(s))

# ── Extended phrase table (ordered longest-first) ────────────────────────────
PHRASES = [
    # ── monitor.js remaining ──────────────────────────────────────────────────
    ("解除 LLM 常用的块级 HTML 外壳（`<div>`、`<p>`、`<section>`、`<article>`、`<main>`）。", "Remove common LLM block-level HTML wrappers (`<div>`, `<p>`, `<section>`, `<article>`, `<main>`)."),
    ("整段包在块级标签里时，CommonMark 不会在块内再解析 Markdown，导致 **、` 原样显示。", "When a whole paragraph is wrapped in a block-level tag, CommonMark will not parse Markdown inside it, causing ** and ` to display literally."),
    ("将 HTML 列表 / 粘连的 `<li>` still原为 Markdown 列表行，并去掉外层 `<ul>`，便于 marked 解析行内 **、` `", "Convert HTML lists / adjacent `<li>` elements back to Markdown list lines, removing outer `<ul>`, so marked can parse inline ** and `."),
    ("行首 Unicode more items目符号 → Markdown 列表 `- `（Model常用 • 而非 `-`）", "Leading Unicode bullet symbol → Markdown list `- ` (models commonly use • instead of `-`)"),
    ("修正Model常见的强调语法偏差:", "Fix common model emphasis syntax deviations:"),
    ("1) 把 `\\*\\*文本\\*\\*` still原为 `**文本**`（常见于多层转义Output）", "1) Restore `\\*\\*text\\*\\*` to `**text**` (common in multi-level escaped output)"),
    ("2) 把 `** 文本 **` 收敛为 `**文本**`（避免分隔符内Empty格导致不生效）", "2) Normalize `** text **` to `**text**` (prevent spaces inside delimiters from breaking emphasis)"),
    ("仅处理单行内容，避免跨段落误匹配。", "Only process single-line content to avoid cross-paragraph false matches."),
    ("奇数个 `**` 往往意味着有一个孤立标记；仅清理「Empty白夹着的 **」这类高置信噪声。", "An odd number of `**` usually means an isolated marker; only clean high-confidence noise like '** surrounded by spaces'."),
    ("允许 `\\*\\*text\\*\\*` 先still原，escaped 星号本身不作为强调标记。", "Allow `\\*\\*text\\*\\*` to be restored first; escaped asterisks are not treated as emphasis markers."),
    ("内部为Empty时不改写，避免把 `****` 等Abnormal输入改坏。", "Do not rewrite when inner content is empty, to avoid corrupting abnormal inputs like `****`."),
    ("CJK/字母数字与强调标记紧邻时补边界Empty格，提升解析Stable性。", "Add boundary spaces when CJK/alphanumeric is adjacent to emphasis markers, to improve parse stability."),
    ("先still原常见 escaped strong，再做成对规范化。", "First restore common escaped strong markers, then normalize matched pairs."),
    ("解析前归一化助手 Markdown: 去掉零宽字符，NFKC 将全角 * ` _ 等转为 ASCII，", "Normalize assistant Markdown before parsing: remove zero-width characters, NFKC converts full-width * ` _ etc. to ASCII,"),
    ("避免 marked None法识别强调/行内代码而原样显示 **、反引号；", "to prevent marked from failing to recognize emphasis/inline code and displaying ** and backticks literally;"),
    ("并移除 &lt;redacted_thinking&gt; 等伪 XML 思考块、修正块级 HTML（`<div>`/`<p>`/…、`<ul>`/`<li>`）与 Unicode more items目符号 `•`，避免块级 HTML 吞掉 inline 解析。", "also remove pseudo-XML thinking blocks like &lt;redacted_thinking&gt;, fix block-level HTML (`<div>`/`<p>`/…, `<ul>`/`<li>`) and Unicode bullet `•`, to prevent block-level HTML from suppressing inline parsing."),
    ("与 internal/openai.normalizeStreamingDelta 一致: 兼容网关/ModelBack「累计全文」或整包重发，", "Consistent with internal/openai.normalizeStreamingDelta: compatible with gateway/model returning 'accumulated full text' or resending complete chunks,"),
    ("避免前端 buffer += chunk 与后端已归一化的增量叠加导致逐段重复（如「响应中显示了响应中显示了」）。", "to prevent frontend buffer += chunk combined with already-normalized backend deltas from causing repeated segments (e.g. 'response shows response shows')."),
    ("SSE data.accumulated: 服务端权威流式全文。有则直接用作 buffer，避免双端 normalize 叠字。", "SSE data.accumulated: authoritative server-side streaming full text. When present, use directly as buffer to avoid double-normalize duplication."),
    ("@returns {string|null} 有快照时Back全文；No则 null（回退 delta 归一化）", "@returns {string|null} Returns full text when snapshot exists; null otherwise (falls back to delta normalization)"),
    ("@returns {string} 合并后的 buffer", "@returns {string} merged buffer"),
    ("流式纯文本 DOM: 按帧合并Update，尽量增量 appendData，避免每条 SSE 全量 textContent 阻塞主线程", "Streaming plain text DOM: merge updates per frame, use incremental appendData when possible, to avoid each SSE fully replacing textContent and blocking the main thread"),
    ("跟踪仍有待Refresh的流式节点，便于快照时间线前一次性 flush", "Track streaming nodes still awaiting refresh, to allow a one-time flush before snapshot timeline"),
    ("流式 delta: 纯文本，避免每条全量 marked + DOMPurify", "Streaming delta: plain text, avoiding full marked + DOMPurify on every chunk"),
    ("分批处理 SSE data 行并在批间让出主线程，避免单次 read() 内数百条事件连续阻塞 UI。", "Process SSE data lines in batches and yield the main thread between batches, to avoid hundreds of consecutive events blocking the UI within a single read()."),
    ("流结束或非流式: 富文本（已消毒的 HTML 字符串）", "Stream end or non-streaming: rich text (sanitized HTML string)"),
    ("清理旧Version可能残留在气泡内的Copy按钮；新版按钮统一在时间行。", "Clean up Copy buttons that old versions may have left inside the bubble; new version buttons are unified in the timestamp row."),
    ("服务端任务注册可能比跨标签pageNotification晚一瞬，稍后由权威Task listConfirm并挂载补流。", "Server-side task registration may be slightly later than cross-tab page notification; it will be confirmed and stream-attached later by the authoritative task list."),
    ("同一Chat可能在服务重启后又启动了新任务，不能因此重新Activate旧审批。", "The same chat may start a new task after a service restart; this must not re-activate old approvals."),
    ("具体审批 ID 已不在 pending 列表时，倒计时和按钮必须保持Close。", "When a specific approval ID is no longer in the pending list, the countdown and buttons must remain closed."),
    ("顶栏「Stop task」与进度条按钮对齐时，用会话 ID 反查Currentpage的 progress 块 ID（None则弹窗内仍可按会话Cancel）", "When the top bar 'Stop task' aligns with the progress bar button, look up the current page's progress block ID by session ID (if none, the dialog can still cancel by session)"),
    ("与 MCP 监控一致: 仅终止CurrentIn progress的工具调用，工具Back后本轮推理继续（可选 reason 合并进工具结果）", "Consistent with MCP monitoring: only terminate the currently in-progress tool call; reasoning continues after the tool returns (optional reason can be merged into tool result)"),
    ("彻底Stop task（原「Stop task」行为）", "Fully stop task (original 'Stop task' behavior)"),
    ("切换进度Details显示", "Toggle progress details display"),
    ("编排器开始Output最终回复时隐藏整条进度消息（过程已迁入助手气泡的「ExpandDetails」，避免与进度卡重复）", "Hide the entire progress message when the orchestrator starts outputting the final reply (the process has been moved into the assistant bubble's 'expand details', to avoid duplication with the progress card)"),
    ("Collapse所有进度Details", "Collapse all progress details"),
    ("Collapse集成到MCP区域的Details", "Collapse details integrated into the MCP area"),
    ("Collapse独立的Details组件（ApproveconvertProgressToDetails创建的）", "Collapse standalone details components (created by convertProgressToDetails)"),
    ("查找所有以details-开头的Details组件", "Find all details components with IDs starting with 'details-'"),
    ("Collapse原始的进度消息（如果still存在）", "Collapse the original progress message (if it still exists)"),
    ("获取CurrentAssistant messageID（用于done事件）", "Get current assistant message ID (for done events)"),
    ("中断并继续失败:", "Interrupt and continue failed:"),
    ("秒", " sec"),

    # ── chat.js remaining ─────────────────────────────────────────────────────
    ("若Current value 与 placeholder 相同，说明Hint被误当作内容，Clear以便正确显示占位符", "If current value equals placeholder, the hint was mistakenly treated as content; clear it to correctly show the placeholder"),
    ("如果输入框已有内容，不Resume草稿（避免覆盖用户输入）", "If the input already has content, do not restore the draft (to avoid overwriting user input)"),
    ("如果草稿内容和占位Hint一样，则认为YesNone效草稿，不Resume", "If draft content equals the placeholder hint, treat it as an invalid draft and do not restore"),
    ("调整输入框高度以适应内容", "Adjust input height to fit content"),
    ("清理掉None效草稿，避免之后继续干扰", "Clean up invalid drafts to avoid future interference"),
    ("Resume草稿失败:", "Failed to restore draft:"),
    ("清除Save的草稿", "Clear saved draft"),
    ("同步清除，确保立即生效", "Synchronously clear to ensure immediate effect"),
    ("清除草稿失败:", "Failed to clear draft:"),
    ("调整textarea高度以适应内容", "Adjust textarea height to fit content"),
    ("先Reset高度为auto，然后立即设置为固定值，确保能准确获取scrollHeight", "First reset height to auto, then immediately set to a fixed value to accurately get scrollHeight"),
    ("强制浏览器重新计算布局", "Force browser to recalculate layout"),
    ("计算新高度（最小40px，最大不超过300px）", "Calculate new height (minimum 40px, maximum 300px)"),
    ("如果内容为Empty或只有很少内容，立即Reset到最小高度", "If content is empty or very short, immediately reset to minimum height"),
    ("Enter 会直接调用 sendMessage；同一会话在Other标签page已启动任务时，", "Enter will directly call sendMessage; when a task is already running in the same session in another tab,"),
    ("必须在渲染用户气泡和发起 POST 前做一次权威状态同步，避免Generate一轮\"已有任务Executing\"伪Chat。", "an authoritative state sync must happen before rendering the user bubble and making the POST, to avoid generating a 'task already running' false chat round."),
    ("正在等待附件UploadComplete…", "Waiting for attachments to finish uploading…"),
    ("部分附件未Upload successful，请移除失败items或重新Select file后再Send。", "Some attachments failed to upload. Please remove failed items or re-select files before sending."),
    ("有附件且用户未输入时，发一句简短DefaultHint即可（后端会拼接路径和文件内容给大Model）", "When there are attachments but no user input, send a short default hint (backend will concatenate path and file content for the model)"),
    ("Send前的Task status/附件检查可能包含异步等待。若用户已主动切换会话，", "Task status/attachment checks before sending may include async waits. If the user has already switched sessions,"),
    ("保留Currentpage面，不再把这次尚未发出的请求写入新的可见Chat。", "keep the current page and do not write this unsent request to the newly visible chat."),
    ("显示User message（含附件名，便于用户Confirm）", "Display user message (including attachment names for user confirmation)"),
    ("清除防抖定时器，防止在Clear输入框后重新Save草稿", "Clear the debounce timer to prevent re-saving the draft after clearing the input"),
    ("立即清除草稿，防止page面Refresh时Resume", "Immediately clear the draft to prevent restoration on page refresh"),
    ("使用同步方式确保草稿被清除", "Use synchronous method to ensure draft is cleared"),
    ("立即Clear输入框并清除草稿（在Send请求之前）", "Immediately clear input and draft (before sending the request)"),
    ("强制Reset输入框高度为初始高度（40px）", "Force reset input height to initial height (40px)"),
    ("构建请求体（含附件）", "Build request body (including attachments)"),
    ("Send后Clear附件列表", "Clear attachment list after sending"),
    ("创建进度消息容器（使用详细的进度展示）", "Create progress message container (using detailed progress display)"),
    ("切换Chat后仍可能收到旧响应流中已缓冲的 conversation、response_start", "After switching chats, buffered conversation and response_start events from the old stream may still arrive"),
    ("或 response 事件。它们只能补齐后台任务归属，不能重新抢占CurrentChat。", "or response events. They can only fill in the background task ownership, and must not re-hijack the current chat."),
    ("解析事件数据失败:", "Failed to parse event data:"),
    ("保留最后一个不完整的行", "Retain the last incomplete line"),
    ("处理剩余的buffer", "Process remaining buffer"),
    ("连接提前结束，未收到任务Complete信号。任务可能仍在后端Execute，请View顶部Running任务或RefreshCurrentChat。", "Connection ended early; no task completion signal received. The task may still be running on the backend. Check the running tasks at the top or refresh the current chat."),
    ("Message sent successfully后，再次确保草稿被清除", "After message sent successfully, ensure the draft is cleared again"),
    ("连接已中断（", "Connection interrupted ("),
    ("）。长时间任务可能仍在后端Execute，请View顶部Running任务或稍后RefreshChat。", "). A long-running task may still be executing on the backend. Check running tasks at the top or refresh the chat later."),
    ("Send失败时，不Resume草稿，因为消息已经显示在Chat框中了", "On send failure, do not restore the draft because the message is already shown in the chat"),
    ("Chat文件Upload ----------", "Chat file upload ----------"),
    ("Upload中…", "Uploading…"),
    ("失败", "Failed"),
    ("移除", "Remove"),
    ("移除 ", "Remove "),
    ("有附件且输入框为Empty时，填入一句DefaultHint（可Edit）；后端会单独拼接路径与内容给大Model", "When there are attachments and the input is empty, fill in a default hint (editable); backend will concatenate path and content separately for the model"),
    ("最多同时Upload ", "Maximum concurrent uploads: "),
    (" 文件，Current已选 ", " files; currently selected: "),
    (" 。", "."),
    ("addFilesToChat 已Hint", "addFilesToChat already notified"),
    ("防止点击候选items时输入框失焦", "Prevent input from losing focus when clicking candidate items"),
    ("Ignore加载Error，稍后可重试", "Ignore load error, can retry later"),
    ("RefreshTool list（Reset已加载状态，强制重新加载）", "Refresh tool list (reset loaded state, force reload)"),
    ("如果Current正在使用@功能，立即触发重新加载", "If currently using the @ feature, immediately trigger a reload"),
    ("Ignore加载Error", "Ignore load error"),
    ("将Refresh函数暴露到window对象，供Other模块调用", "Expose the refresh function to the window object for use by other modules"),
    ("检查RoleYesNo改变，如果改变则强制重新加载", "Check if the role has changed; if so, force a reload"),
    ("Generate工具的唯一标识符，用于区分同名但来源不同的工具", "Generate a unique identifier for tools, to distinguish tools with the same name but different sources"),
    ("如果Yes外部工具，使用 external_mcp::tool.name 作为唯一标识", "If it is an external tool, use external_mcp::tool.name as the unique identifier"),
    ("Upload附件 ", "Uploading attachments "),
    ("处理中...", "Processing..."),

    # ── dashboard.js remaining ────────────────────────────────────────────────
    ("Dashboardpage面: 拉取RunningChat、Vulnerability统计、批量任务、工具与 Skills 统计并渲染。", "Dashboard page: fetch running chats, vulnerability statistics, batch tasks, tools and skills statistics and render."),
    ("工程基础设施:", "Engineering infrastructure:"),
    ("dashboardState 集中SaveRun时状态（in-flight controller / Auto轮询 timer / 上次Updated time /", "dashboardState centralizes runtime state (in-flight controller / auto-poll timer / last updated time /"),
    ("已被本会话Ignore的告警条 reasons）；", "alert reasons ignored by this session);"),
    ("每次 refreshDashboard 入口 abort 上一个 controller，把 signal 传给所有 apiFetch，", "Each refreshDashboard entry aborts the previous controller and passes the signal to all apiFetch calls,"),
    ("避免快速连点 / Auto轮询触发 race condition；", "to avoid race conditions from rapid clicks or auto-polling;"),
    ("Auto轮询: startDashboardAutoRefresh() 每 60 秒拉一次；page面切走 / tab 隐藏时AutoPause，", "Auto-poll: startDashboardAutoRefresh() polls every 60 seconds; auto-pauses when the page is navigated away from or the tab is hidden,"),
    ("再切回时立即补一次Refresh（基于 lastUpdatedAt 避免None效请求）；", "and immediately refreshes on return (based on lastUpdatedAt to avoid redundant requests);"),
    ("过期检测: updateLastUpdatedNow 记录时间戳；checkDashboardStale 每 30 秒检查，", "Stale detection: updateLastUpdatedNow records the timestamp; checkDashboardStale checks every 30 seconds,"),
    ("超过 5 分钟未Refresh则在「上次Update」徽章上加 .is-stale 类（变灰 + 显示 ⚠️）。", "if not refreshed for 5 minutes, adds the .is-stale class to the 'last updated' badge (turns gray + shows ⚠️)."),
    ("Current正在进行的 fetch 的 AbortController", "AbortController for the currently ongoing fetch"),
    ("Auto轮询的 setInterval id", "setInterval id for auto-polling"),
    ("过期检查的 setInterval id", "setInterval id for stale check"),
    ("上次SuccessRefresh的时间戳（ms）", "Timestamp (ms) of the last successful refresh"),
    ("Current会话中被用户「×」掉的告警内容指纹（同样的 reasons 不再弹）", "Fingerprint of alert content dismissed by the user '×' in the current session (same reasons won't pop up again)"),
    ("上一轮关键资源快照，用于判断YesNo首次有数据 / 智能 CTA", "Previous round key resource snapshot, used to determine first-time data presence / smart CTA"),
    ("最近Vulnerability / 近期事实 Tab", "Recent Vulnerabilities / Recent Facts tab"),
    ("接入Overview Tab: c2 | webshell", "Access overview tab: c2 | webshell"),
    ("Critical程度分布Current状态Filter: '' | open | confirmed | fixed | false_positive | ignored", "Severity distribution current status filter: '' | open | confirmed | fixed | false_positive | ignored"),
    ("最近一次ProjectDashboard摘要（供 Tab 切换时重绘）", "Most recent project dashboard summary (for redraw on tab switch)"),
    ("severityTotalEl 在后续渲染逻辑中也被引用，必须在 loading 分支外声明", "severityTotalEl is also referenced in subsequent render logic; must be declared outside the loading branch"),
    ("体验优化: Auto轮询 / 已经有数据时，不再把界面闪成「…」占位，", "UX optimization: when auto-polling / data already exists, do not flash the UI to '…' placeholder;"),
    ("直接在后台拉新数据并平滑替换；只有首次加载时才显示 loading 状态。", "pull new data in the background and replace smoothly; only show loading state on first load."),
    ("防 race: abort 上一个仍在In progress的请求，再创建新 controller", "Prevent race: abort the previous in-progress request, then create a new controller"),
    ("统一封装: apiFetch + abort signal + 失败/Cancel都Back null（不抛错），", "Unified wrapper: apiFetch + abort signal + failure/cancel all return null (no throw),"),
    ("让上层可以用解构赋值平铺读取所有结果，避免一处失败导致整个 Promise.all reject", "allowing the caller to destructure all results, avoiding one failure causing the entire Promise.all to reject"),
    ("/api/vulnerabilities/stats 只给出 by_severity 与 by_status 两个独立维度，", "/api/vulnerabilities/stats only provides by_severity and by_status as independent dimensions;"),
    ("None法得到「Critical × Open」的交叉计数。这里按四档各拉一次（limit=1，仅取 total），", "Cannot get 'severity × open' cross-counts. Pull once per severity level (limit=1, only take total),"),
    ("用真实的「Open」计数驱动告警条 / KPI 副标 / 风险Overview卡的加权分，", "using real 'open' counts to drive alert bars / KPI subtitles / risk overview card weighted scores,"),
    ("避免「All修复后风险等级仍显示极高」这类语义冲突。", "to avoid semantic conflicts like 'risk level still shows critical after all are fixed'."),
    ("中/Low的「Open」计数: 用于风险Overview卡的加权风险分，使其反映\"Current未处理风险\"", "Medium/Low 'Open' counts: used for risk overview card weighted risk score, to reflect 'current unhandled risks'"),
    ("拉取 MCP 工具的「配置总数」用于「能力总览」（区别于 monitor/stats 的「有调用记录」）。", "Fetch MCP tool 'total configured count' for 'capability overview' (distinct from monitor/stats 'has call records')."),
    ("仅取 total 字段，page_size=1 减少传输；total 已涵盖内部 + External MCP + 直接注册的工具。", "Only fetch the total field, page_size=1 to reduce transfer; total covers internal + external MCP + directly registered tools."),
    ("HITL Pending approval: 用于「需要立即处理」告警条 + 推荐操作", "HITL pending approvals: used for 'needs immediate action' alert bar + recommended actions"),
    ("Notification摘要: since=0 拿Latest一批，limit 控制大小；用于「最近事件」内联展示", "Notification summary: since=0 gets the latest batch, limit controls size; used for 'recent events' inline display"),
    ("External MCP 健康度", "External MCP health"),
    ("WebShell 已建立的连接（pentest 落地后的 foothold，对运营场景非常关键）", "WebShell established connections (foothold after pentest landing, critical for operational scenarios)"),
    ("C2 Dashboard条: Listener / 会话 / Open任务（任务接口含 pending_queued_count）", "C2 dashboard bar: listeners / sessions / open tasks (task API includes pending_queued_count)"),
    ("如果在 await 期间 controller 已被 abort，说明又有新Refresh启动了，丢弃本次结果", "If the controller was aborted during await, a new refresh has started; discard this result"),
    ("RunningChat: 仅统计 Agent 循环任务；批量队列见右侧「批量任务队列」", "Running chats: only count agent loop tasks; see 'batch task queue' on the right for batch queue"),
    ("KPI 副标: AllEmpty闲 / 正在Execute", "KPI subtitle: all idle / currently executing"),
    ("解析「Open」口径的真实计数（专门拉的接口）；若该接口失败则退回 by_severity", "Parse real 'open' scope counts (from the dedicated API); fall back to by_severity if the API fails"),
    ("优先用专门拉的「Open」计数；若专items接口失败，则退回 by_severity（宁可False positive，不可漏报）", "Prefer the dedicated 'open' counts; if the dedicated API fails, fall back to by_severity (prefer false positives over missed reports)"),
    ("Vulnerability KPI 副标: 徽章/文案均使用「Open」口径", "Vulnerability KPI subtitle: both badge and text use 'open' scope"),
    ("批量任务队列: 按状态统计（优化版；running 与上方 batchRunningCount 一致）", "Batch task queue: count by status (optimized; running matches batchRunningCount above)"),
    ("SystemEmpty闲", "System idle"),
    ("正在Execute", "Executing"),
    ("暂NoneAdd风险", "No risks added yet"),
    ("高Critical度已All处置", "All high-severity items handled"),

    # ── roles.js remaining ────────────────────────────────────────────────────
    ("i18n 未就绪或词条缺失时避免把 key 暴露给用户（与 zh-CN Default一致）", "Avoid exposing keys to users when i18n is not ready or key is missing (consistent with zh-CN default)"),
    ("暂None描述", "No description"),
    ("None描述", "No description"),
    ("DefaultRole，不额外携带用户Hint词，使用DefaultMCP", "Default role, no additional user hint words, uses default MCP"),
    ("DefaultRole，不额外携带用户Hint词，使用所有工具", "Default role, no additional user hint words, uses all tools"),
    ("Role配置中的描述: trim，并把误存为 i18n key 的字面量视为Empty", "Role configuration description: trim and treat literals accidentally stored as i18n keys as empty"),
    ("RoleSearch关键词", "Role search keyword"),
    ("Search防抖定时器", "Search debounce timer"),
    ("Storage所有Tool list（用于RoleTool selection）", "Store all tool list (used for role tool selection)"),
    ("与 MCP 工具配置Total用 localStorage，便于统一运维习惯", "Shared localStorage with MCP tool configuration for unified operational habits"),
    ("本Role关联Filter: '' = All, 'role_on' = 本Role已勾选关联, 'role_off' = 本Role未关联", "This role association filter: '' = All, 'role_on' = this role is checked, 'role_off' = this role is not associated"),
    ("按Role关联Filter时缓存全量列表（匹配CurrentSearch），避免翻page丢状态", "Cache the full list when filtering by role association (matching current search), to avoid losing state on page turn"),
    ("YesNo使用客户端分page（Role关联Filter模式下为 true）", "Whether to use client-side pagination (true in role association filter mode)"),
    ("工具Search关键词", "Tool search keyword"),
    ("工具状态映射: toolKey -> { enabled: boolean, ... }", "Tool state map: toolKey -> { enabled: boolean, ... }"),
    ("标记RoleYesNo使用所有工具（当没有配置tools时）", "Flag indicating if the role uses all tools (when no tools are configured)"),
    ("Enabled的工具总数（从MCP中获取，从API响应中获取）", "Total count of enabled tools (obtained from MCP, from API response)"),
    ("仅在「None状态Filter、NoneSearch」的请求结果上Update，供统计条分母使用（避免Filter后 total 变小导致 25/9 这类Error）", "Only update on results with 'no status filter, no search', used as denominator for statistics bar (avoid filter causing total to shrink, leading to errors like 25/9)"),
    ("工具总条数（与 MCP 列表「All」一致）", "Total tool count (consistent with MCP list 'All')"),
    ("MCP 全局Enabled工具数", "MCP globally enabled tool count"),
    ("Role配置的Tool list（用于OK哪些工具应该被选中）", "Role-configured tool list (used to determine which tools should be selected)"),
    ("对Role list进行Sort: DefaultRole排在第一个，Other按名称Sort", "Sort role list: default role first, others sorted by name"),
    ("将\"Default\"Role分离出来", "Separate the 'Default' role"),
    ("OtherRole按名称Sort，保持固定顺序", "Sort other roles by name, maintain fixed order"),
    ("将\"Default\"Role放在第一个，OtherRole按Sort后的顺序跟在后面", "Put 'Default' role first, followed by other roles in sorted order"),
    ("加载所有Role", "Load all roles"),
    ("加载Role失败", "Failed to load roles"),
    ("渲染侧边栏Role list", "Render sidebar role list"),
    ("加载Role失败:", "Failed to load roles:"),
    ("Hint文案使用 i18n；若此时 i18n 尚未初始化，则回退为可读Chinese，而不Yes暴露 key（roles.loadFailed）", "Hint text uses i18n; if i18n is not yet initialized, fall back to readable Chinese rather than exposing the key (roles.loadFailed)"),
    ("加载Role失败", "Failed to load roles"),
    ("处理Role变更", "Handle role change"),
    ("Update侧边栏选中状态", "Update sidebar selected state"),
    ("当Role切换时，如果Tool list已加载，标记为需要重新加载", "When the role switches, if the tool list is loaded, mark it for reload"),
    ("这样下次触发@工具建议时会使用新的Role重新加载Tool list", "This way, the next @ tool suggestion will reload the tool list with the new role"),
    ("Approve设置一个标记来Notificationchat.js需要重新加载Tool list", "Set a flag to notify chat.js that the tool list needs to be reloaded"),
    ("UpdateRole选择器显示", "Update role selector display"),
    ("使用配置中的图标，如果没有则使用Default图标", "Use the icon from configuration; use default icon if none"),
    ("如果 icon Yes Unicode 转义格式（\\U0001F3C6），需要转换为 emoji", "If icon is in Unicode escape format (\\U0001F3C6), convert to emoji"),
    ("如果转换失败，使用Default图标", "If conversion fails, use default icon"),
    ("非DefaultRole时避免被 i18n 的 data-i18n 覆盖成\"Default\"", "For non-default roles, prevent i18n data-i18n from overwriting with 'Default'"),
    ("渲染主内容区域Role选择列表", "Render main content area role selection list"),
    ("Clear列表", "Clear list"),
    ("根据Role配置获取图标，如果没有配置则使用Default图标", "Get icon from role configuration; use default if not configured"),
    ("如果 icon Yes Unicode 转义格式（\\U0001F3C6），需要转换为 emoji", "If icon is in Unicode escape format (\\U0001F3C6), convert to emoji"),
    ("检查YesNoYes Unicode 转义格式（可能包含引号）", "Check if it is in Unicode escape format (may contain quotes)"),
    ("如果转换失败，使用原值", "If conversion fails, use original value"),
    ("如果没有配置图标，根据Role name的首字符GenerateDefault图标", "If no icon is configured, generate default icon from first character of role name"),

    # ── knowledge.js remaining ────────────────────────────────────────────────
    ("嵌入服务Reject认证。请检查Knowledge base嵌入配置的 API 密钥及服务地址，Save后重", "Embedding service rejected authentication. Check the API key and service address in the knowledge base embedding configuration, then save"),
    ("嵌入服务Reject访问。请检查账号权限及所选嵌入Model的访问权限。", "Embedding service rejected access. Check account permissions and access rights for the selected embedding model."),
    ("嵌入服务限制请求。请检查请求频率及账号可用额度，稍后重试。", "Embedding service rate limited. Check request frequency and account quota, then retry later."),
    ("嵌入服务Request timed out。请检查服务可用性、网络和Agent配置后重试。", "Embedding service request timed out. Check service availability, network and agent configuration, then retry."),
    ("None法连接嵌入服务。请检查服务地址、DNS、网络和Agent配置。", "Cannot connect to embedding service. Check the service address, DNS, network and agent configuration."),
    ("请根据上方Error检查嵌入Model和服务配置，修正后重试。", "Check the embedding model and service configuration based on the error above, then retry after correction."),
    ("Knowledge base管理相关功能", "Knowledge base management functionality"),
    ("Back「Knowledge base未Enable」Hint区块的 HTML（使用 data-i18n 以便Language switch时AutoUpdate）", "Return the HTML for the 'Knowledge base not enabled' hint block (uses data-i18n for auto-update on language switch)"),
    ("渲染「Knowledge base未Enable」状态到容器，并应用CurrentLanguage", "Render 'Knowledge base not enabled' state to container and apply current language"),
    ("防止重复Submit", "Prevent duplicate submission"),
    ("Storage检索日志数据，用于DetailsView", "Store retrieval log data for details view"),
    ("每page分类数（改为按分类分page）", "Number of categories per page (changed to paginate by category)"),
    ("Search防抖定时器", "Search debounce timer"),
    ("加载知识分类", "Load knowledge categories"),
    ("添加时间戳参数避免缓存", "Add timestamp parameter to avoid caching"),
    ("获取分类失败", "Failed to fetch categories"),
    ("检查Knowledge base功能YesNoEnable", "Check if knowledge base feature is enabled"),
    ("功能未Enable，显示友好Hint（使用 data-i18n，切换Language时会AutoUpdate）", "Feature not enabled; show friendly hint (uses data-i18n for auto-update on language switch)"),
    ("Update分类Filter下拉框", "Update category filter dropdown"),
    ("加载分类失败:", "Failed to load categories:"),
    ("只在非功能未Enable的情况下显示Error", "Only show error when feature is not simply disabled"),
    ("Knowledge base功能未Enable", "Knowledge base feature not enabled"),
    ("showNotification('加载分类失败: '", "showNotification('Failed to load categories: '"),
    ("加载Knowledge item列表（支持按分类分page，Default不加载完整内容）", "Load knowledge item list (supports pagination by category, does not load full content by default)"),
    ("Update分page状态", "Update pagination state"),
    ("构建URL（按分类分page模式，不包含完整内容）", "Build URL (category pagination mode, without full content)"),
    ("获取Knowledge item失败", "Failed to fetch knowledge items"),
    ("功能未Enable，显示友好Hint（如果still没有显示的话；使用 data-i18n，切换Language时会AutoUpdate）", "Feature not enabled; show friendly hint if not already shown (uses data-i18n for auto-update on language switch)"),
    ("处理按分类分page的响应数据", "Process response data for category-based pagination"),
    ("总分类数", "total category count"),
    ("如果选择了单个分类，不显示分page（因为只显示一个分类）", "If a single category is selected, do not show pagination (only one category is shown)"),
    ("加载Knowledge item失败:", "Failed to load knowledge items:"),
    ("渲染Knowledge item列表（按分类分page的数据结构）", "Render knowledge item list (category pagination data structure)"),
    ("暂NoneKnowledge item", "No knowledge items"),
    ("计算总items数和分类数", "Calculate total items and category count"),
    ("Update统计Info", "Update statistics info"),
    ("渲染分类及Knowledge item", "Render categories and knowledge items"),
    ("未分类", "Uncategorized"),
    ("渲染Knowledge item列表（向后兼容，用于按items分page的旧代码）", "Render knowledge item list (backward compatible, for old paginate-by-items code)"),
    ("按分类分组", "Group by category"),
    ("渲染分page控件（按分类分page）", "Render pagination controls (category-based pagination)"),
    ("totalYes总分类数", "total is the total category count"),

    # ── settings.js remaining ────────────────────────────────────────────────
    ("设置相关功能", "Settings-related functionality"),
    ("全局工具状态映射，用于Save用户在所有page面的修改", "Global tool state map for saving user changes across all pages"),
    ("key: 唯一工具标识符（toolKey），value: { enabled: boolean, is_external: boolean, external_mcp: string }", "key: unique tool identifier (toolKey), value: { enabled: boolean, is_external: boolean, external_mcp: string }"),
    ("已配置", "Configured"),
    ("未配置", "Not configured"),
    ("Generate工具的唯一标识符，用于区分同名但来源不同的工具", "Generate unique identifier for tools to distinguish same-named tools from different sources"),
    ("如果Yes外部工具，使用 external_mcp::tool.name 作为唯一标识", "If it is an external tool, use external_mcp::tool.name as the unique identifier"),
    ("如果Yes内部工具，使用 tool.name 作为标识", "If it is an internal tool, use tool.name as the identifier"),
    ("常驻工具配置Storage键（外部工具用 mcp::tool，与后端 tool_search 白名单一致）", "Persistent tool configuration storage key (external tools use mcp::tool, consistent with backend tool_search whitelist)"),
    ("从localStorage读取每page显示数量，Default为20", "Read per-page display count from localStorage, default is 20"),
    ("根据YesNoEnable多Agent，Disable/Enable机器人模式中的 Eino 编排选items", "Based on whether multi-agent is enabled, disable/enable Eino orchestration options in bot mode"),
    ("首次进入Dashboard等page面前拉一次配置，隐藏侧栏 C2（避免Disable后仍显示）", "Fetch configuration once before first entering dashboard pages, hide sidebar C2 (to avoid showing after disabled)"),
    ("根据 C2 YesNoEnable显示主导航 C2 入口与Dashboard接入Overview中的 C2 子块（与 /api/config 的 c2.enabled 一致）", "Show main navigation C2 entry and dashboard access overview C2 sub-block based on whether C2 is enabled (consistent with /api/config c2.enabled)"),
    ("切换设置分类", "Switch settings category"),
    ("Update导航items状态", "Update navigation item state"),
    ("Update内容区域显示", "Update content area display"),
    ("打开设置", "Open settings"),
    ("切换到设置page面", "Switch to settings page"),
    ("每次打开时Clear全局状态映射，重新加载Latest配置", "Clear global state map on each open, reload latest configuration"),
    ("每次打开时重新加载Latest配置（Settingspage面不需要加载Tool list）", "Reload latest configuration on each open (settings page does not need to load tool list)"),
    ("清除之前的验证Error状态", "Clear previous validation error state"),
    ("Default显示基本设置", "Show basic settings by default"),
    ("Close设置（保留函数以兼容旧代码，但现在不需要Close功能）", "Close settings (function kept for backward compatibility, but close functionality is no longer needed)"),
    ("不再需要Close功能，因为现在Yespage面而不Yes模态框", "Close functionality no longer needed since it is now a page rather than a modal"),
    ("如果需要，可以切换回Chatpage面", "If needed, can switch back to chat page"),
    ("点击模态框外部Close（只保留MCPDetails模态框）", "Click outside modal to close (only keep MCP details modal)"),
    ("加载配置", "Load configuration"),
    ("获取配置失败", "Failed to fetch configuration"),
    ("填充FOFA配置", "Fill FOFA configuration"),
    ("填充Human-in-the-loop配置", "Fill human-in-the-loop configuration"),
    ("填充Agent配置", "Fill agent configuration"),
    ("填充Knowledge base配置", "Fill knowledge base configuration"),
    ("填充Knowledge base详细配置", "Fill knowledge base detailed configuration"),
    ("基本配置", "Basic configuration"),
    ("嵌入Model配置", "Embedding model configuration"),
    ("检索配置", "Retrieval configuration"),
    ("索引配置", "Index configuration"),
    ("填充机器人配置", "Fill bot configuration"),
    ("只有在需要时才加载Tool list（MCPpage面需要，Settingspage面不需要）", "Only load tool list when needed (MCP page needs it, settings page does not)"),
    ("设置每page显示数量（会在分page控件渲染时设置）", "Set per-page display count (will be set when pagination controls render)"),
    ("加载Tool list（使用分page）", "Load tool list (with pagination)"),
    ("加载配置失败:", "Failed to load configuration:"),
    ("加载配置失败", "Failed to load configuration"),
    ("工具Search关键词", "Tool search keyword"),
    ("工具状态Filter: '' = All, 'true' = Enabled, 'false' = Disabled", "Tool status filter: '' = All, 'true' = Enabled, 'false' = Disabled"),
    ("按External MCP 来源Filter（点击左侧卡片时设置）", "Filter by external MCP source (set when clicking left-side cards)"),
    ("加载Tool list（分page）", "Load tool list (paginated)"),
    ("等待 i18n 就绪，避免快速Refresh时翻译函数未初始化导致显示占位符", "Wait for i18n to be ready, to avoid translation functions being uninitialized during fast refresh causing placeholder display"),

    # ── webshell.js remaining ────────────────────────────────────────────────
    ("WebShell 管理（类似冰蝎/蚁剑: 虚拟Terminal、Files、CommandExecute）", "WebShell management (similar to Behinder/AntSword: virtual terminal, files, command execution)"),
    ("右侧主区域（Terminal/Files）最小宽度，避免拖到中间时右边变形", "Minimum width of right main area (terminal/files) to prevent deformation when dragged to the middle"),
    ("按连接SaveCommand history，用于上下键", "Save command history per connection, for up/down arrow keys"),
    ("清屏防重入: 一次点击只Execute一次（避免多次绑定或重复触发导致多个 shell>）", "Clear screen re-entry guard: one click executes once (to avoid multiple bindings or triggers creating multiple shell> prompts)"),
    ("AI 助手: 按连接 ID SaveChat ID，便于多轮Chat", "AI assistant: save chat ID per connection ID for multi-turn chat"),
    ("AI 助手: Project绑定（已有Chat按 convId，新Chat按 connId 草稿）", "AI assistant: project binding (existing chat by convId, new chat by connId draft)"),
    ("流式打字机效果: Current会话的 response 序号，用于中止过期的打字", "Streaming typewriter effect: current session response sequence number, used to abort expired typing"),
    ("允许的响应编码，与后端 normalizeWebshellEncoding 对齐", "Allowed response encodings, aligned with backend normalizeWebshellEncoding"),
    ("归一化连接的 encoding 字段，Back 'auto' | 'utf-8' | 'gbk' | 'gb18030'（Empty/Unknown → auto）", "Normalize connection encoding field, returns 'auto' | 'utf-8' | 'gbk' | 'gb18030' (empty/unknown → auto)"),
    ("从连接对象取编码，便于透传到 /api/webshell/exec 与 /api/webshell/file", "Get encoding from connection object for passthrough to /api/webshell/exec and /api/webshell/file"),
    ("允许的目标 OS，与后端 normalizeWebshellOS 对齐", "Allowed target OSes, aligned with backend normalizeWebshellOS"),
    ("归一化连接的 os 字段，Back 'auto' | 'linux' | 'windows'（Empty/Unknown → auto）", "Normalize connection os field, returns 'auto' | 'linux' | 'windows' (empty/unknown → auto)"),
    ("从连接对象取目标 OS，便于透传到 /api/webshell/exec 与 /api/webshell/file", "Get target OS from connection object for passthrough to /api/webshell/exec and /api/webshell/file"),
    ("Generate一次性探活 token，避免固定回显值被包装时误判", "Generate a one-time probe token to avoid false positives when a fixed echo value is wrapped"),
    ("构造跨 Windows/Linux 都可Execute的探活Command", "Construct a probe command executable on both Windows and Linux"),
    ("探活Success判定: HTTP Success且Output中包含本次 token", "Probe success criterion: HTTP success and output contains this round's token"),
    ("组装 /api/webshell/file 的公Total请求体。", "Assemble the common request body for /api/webshell/file."),
    ("所有Files调用点都应走此函数，避免遗漏字段（如 connection_id）。", "All file call sites should go through this function to avoid missing fields (e.g. connection_id)."),
    ("@param {Object} conn 连接对象", "@param {Object} conn connection object"),
    ("@param {Object} extra 额外字段（action / path / content / target_path / chunk_index ...）", "@param {Object} extra extra fields (action / path / content / target_path / chunk_index ...)"),
    ("@returns {string} JSON 字符串", "@returns {string} JSON string"),
    ("当服务端探活命中目标System（仅 auto 连接首次列目录时出现）时，", "When server-side probing identifies the target system (only appears on first directory listing for auto connections),"),
    ("把结果同步到本地 webshellConnections 缓存 + 持久化到数据库。", "sync the result to local webshellConnections cache + persist to database."),
    ("后续Refresh不再探活，AI 也能直接看到正确的 OS 上下文。", "Subsequent refreshes will not probe again; AI can also see the correct OS context directly."),
    ("服务端已经回写了 DB；但极少数情况下调用方未带 connection_id，这里再兜底 PUT 一次", "Server has already written back to DB; but in rare cases the caller omits connection_id, so PUT once more as fallback"),
    ("与主Chatpage一致: Eino 模式走 /api/multi-agent/stream，body 带 orchestration", "Consistent with main chat page: Eino mode uses /api/multi-agent/stream, body includes orchestration"),
    ("WebShell AI 助手: Role + Chat模式选择器（与主「Chat」page对齐）", "WebShell AI assistant: role + chat mode selector (aligned with main 'Chat' page)"),
    ("缓存 /api/roles 结果", "Cache /api/roles result"),
    ("DefaultRole，不额外携带用户Hint词，使用所有工具", "Default role, no additional user hint words, uses all tools"),
    ("已在上方硬编码DefaultRole，Skip API Back的Defaultitems", "Default role already hardcoded above; skip default items returned by API"),
    ("使用主page的 handleRoleChange 来同步 roles.js 内部状态和 localStorage", "Use main page's handleRoleChange to sync roles.js internal state and localStorage"),
    ("Chat模式选择器", "Chat mode selector"),
    ("YesNoEnable多Agent", "Whether to enable multi-agent"),
    ("隐藏/显示多Agent选items", "Hide/show multi-agent option items"),
    ("标准化Current值", "Normalize current value"),
    ("同步主page模式选择器", "Sync main page mode selector"),
    ("WebShell AI more items目选择器（与主「Chat」page对齐）", "WebShell AI target selector (aligned with main 'Chat' page)"),
    ("不Bind project黑板", "Do not bind project blackboard"),
    ("Total享Fact board", "Shared fact board"),
    ("未命名", "Untitled"),
    ("没有匹配的Project", "No matching projects"),
    ("MoreProjectPlease enter关键字Search", "More projects - please enter a keyword to search"),
    ("加载Project失败，请重试", "Failed to load projects, please retry"),
    ("已Bind project", "Project bound"),
    ("已Unbind projec", "Project unbound"),
    ("end WebShell AI more items目选择器", "end WebShell AI target selector"),
    ("当 WebShell AI Tab 可见时Refresh选择器显示（同步主page可能的更改）", "Refresh selector display when WebShell AI tab is visible (sync possible changes from main page)"),
    ("点击面板外部Close", "Click outside panel to close"),
    ("end WebShell AI 选择器", "end WebShell AI selector"),
    ("StopCurrent WebShell AI 流式请求", "Stop current WebShell AI streaming request"),
    ("切换Send/Stop按钮状态", "Toggle send/stop button state"),
    ("从服务端（SQLite）拉取连接列表", "Fetch connection list from server (SQLite)"),
    ("读取 WebShell 连接列表失败", "Failed to read WebShell connection list"),
    ("暂不绑定", "Do not bind for now"),
    ("加载 WebShell more items目选items失败", "Failed to load WebShell target option items"),
    ("从服务端Refresh连接列表并重绘侧栏", "Refresh connection list from server and redraw sidebar"),
    ("使用 wsT 避免与全局 window.t 冲突导致None限递归", "Use wsT to avoid infinite recursion conflicting with global window.t"),
    ("WebShell 管理", "WebShell Management"),
    ("添加连接", "Add connection"),
    ("Command参数名", "Command parameter name"),
    ("用户已显式配置，尊重之", "User has explicitly configured this, respect it"),

    # ── general remaining patterns ────────────────────────────────────────────
    ("处理中...", "Processing..."),
    ("已处理 ", "Processed "),
    ("渗透TestIn progress...", "Penetration test in progress..."),
    ("任务Info尚未同步，请稍后再试。", "Task info not yet synced, please try again later."),
    ("Cancel中...", "Cancelling..."),
    ("Cancel失败", "Cancellation failed"),
    ("Submit中...", "Submitting..."),
    ("任务已中断", "Task interrupted"),
    ("任务已中断，审批Cancelled", "Task interrupted, approval cancelled"),
    ("任务已结束，审批不可用", "Task ended, approval unavailable"),
    ("处理中...", "Processing..."),
    ("；", "; "),
    ("已有任务Executing", "a task is already executing"),
    ("连接已中断（", "Connection interrupted ("),
    ("Upload中…", "Uploading…"),
    ("Upload附件", "Upload attachments"),

    # ── remaining short/fragment patterns ────────────────────────────────────
    ("暂NoneKnowledge item", "No knowledge items"),
    ("未分类", "Uncategorized"),
    ("暂不绑定", "Do not bind for now"),
    ("已Bind project", "Project bound"),
    ("已Unbind project", "Project unbound"),
]

# Sort by length descending so longer phrases match first
PHRASES.sort(key=lambda x: len(x[0]), reverse=True)

def replace_all(content):
    for cn, en in PHRASES:
        if cn in content:
            content = content.replace(cn, en)
    return content

def translate_file(path):
    text = open(path, encoding='utf-8').read()
    before = len(re.findall(r'[\u4e00-\u9fff\u3400-\u4dbf\uff00-\uffef\u2e80-\u2eff\u3000-\u303f]', text))
    if before == 0:
        return 0, 0
    new_text = replace_all(text)
    after = len(re.findall(r'[\u4e00-\u9fff\u3400-\u4dbf\uff00-\uffef\u2e80-\u2eff\u3000-\u303f]', new_text))
    if new_text != text:
        open(path, 'w', encoding='utf-8').write(new_text)
    return before, after

total_before = 0
total_after = 0

for root, dirs, files in os.walk('web/static/js'):
    dirs[:] = [d for d in dirs if d != 'vendor']
    for f in sorted(files):
        if not f.endswith('.js'):
            continue
        path = os.path.join(root, f)
        before, after = translate_file(path)
        if before > 0:
            total_before += before
            total_after += after
            reduced = before - after
            if reduced > 0:
                print(f'  {before:5d} -> {after:4d}  (-{reduced:4d})  {path}')

print(f'\nTotal: {total_before} -> {total_after} ({total_before - total_after} translated, {total_after} remaining)')
